### PR TITLE
Modified the metatype to set a minimum value for integers

### LINKED ISSUE #2754: Driver Connection Delay Can be Set to Negative Value?
If user tries to enter a negative value into the driver's Connection Delay field in Wire Graph, Kura does not report an error. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, install Wires-development-package from Eclipse Marketplace
3. Go to Wire Graph, create a wireAsset comonent and add a channel to it
4. Go to Driver tab and try to enter a negative value to Connection Delay field
5. Kura returns no errors when negative value entered

**Expected behavior**
Kura should return an error when entering a negative value.

**Screenshots**
Screenshot 2020-04-02 at 09 59 43

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2754

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this PR and Kura reports an error only if there is only dash/minus sign, after user adds a number, the error is gone (see GIF bellow). Can you please check?

**Comment by MMaiero** [comment]
Wow, the is strange!

**Comment by MMaiero** [comment]
Do you have the same issue with the example publisher or the heater demo?

**Comment by LeoNerdoG** [comment]
No, both return an error as shown in the screenshot bellow: 

Screenshot 2020-09-04 at 13 21 56

**Comment by MMaiero** [comment]
uhm, then it is not clear to me what is happening. In theory they share the same verification code...

**Comment by LeoNerdoG** [comment]
I have tried on other browsers (cleared chache and everything) and still the same behaviour...

**Comment by MMaiero** [comment]
Screenshot 2020-09-04 at 14 43 57

This is what I get in my case

**Comment by MMaiero** [comment]
Guys, can this be merged?

**Comment by LeoNerdoG** [comment]
Hey, I would merge this. I will check again in develop and if it happens there, we can talk then.

**Comment by pierantoniomerlino** [comment]
For me is ok!

**Pull request merged**
