### PR TITLE
Fixed Bgscan signal strength threshold management.

### LINKED ISSUE #2890: "Bgscan Signal Strength Threshold (dBm)" Parameter Cannot be Changed
If user has the option to change the "Bgscan Signal Strength Threshold (dBm)", the changes are not saved. 
Also there is no validation done uppon the field, so user "can" enter symbols, strings etc... without Kura validationg the field (user can click Apply, but the changes are not saveda anyway). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> TCP/IP
3. Set Status to "enabled for LAN"
4. Go to Wireless tab, connect to a access point (e.g. hotspot on phone)
5. Wait for Ip from DHCP, after that hover above the "Bgscan Signal Strength Threshold (dBm)" field
6. Try to change the strenght treshold - after clicking Apply changes are not saved.

**Expected behavior**
If user changes the strength treshold, the changes should be saved normally. 

**Screenshot:**
Screenshot 2020-05-21 at 10 44 29

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Fixes #2890

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this PR and it fixes the issue only partial. 
If user enters e.g. "#" into the field, and clicks apply, nothing happens (the field is not in error state). But if user anters a number, apply butoon works. 
Please check when you have time.

**Comment by MMaiero** [comment]
Yes, that is due to the fact that the cast fails.

**Comment by MMaiero** [comment]
I believe that to support such validation we have to refactor all the validation code in the UI. Probably that needs a specific issue and corresponding commitment.
I believe for now we can close this and open an issue to improve and unify the UI validation

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I agree with the solution. After you open the new issue regarding the refactoring, just link this issue to it, so we don't forget about it.

**Review by LeoNerdoG — APPROVED** [review]

**Pull request merged**
