### PR TITLE
Switched to sha256 hash for identity passwords 

### PR DESCRIPTION
**Pull request by nicolatimeus**
* Uses sha256 hash for identity passwords
* Also fixes possible logged exception about possible duplicate component definition

### CODE REVIEW

**Review by MMaiero — APPROVED** [review]

**Comment by miricy** [comment]
update to this commits, the console can't login with "admin:admin"
image

**Comment by LeoNerdoG** [comment]
Hey @miricy,
I have just tried to login to Kura which is the latest develop branch and it works with admin:admin, can you please delete your cache to see if that is the problem?

**Comment by miricy** [comment]
Thanks for you reply, I use the develop branch,  the develop branch online code display below:
image

Is not like you commit， It seems that your commit is not used.
image

**Comment by MMaiero** [comment]
Hi @miricy, can you please detail what you are seeing?
From a brief look it seems correct to me.

**Comment by miricy** [comment]
I   clear git cache， and rebuild it. in progress.
wait a moment. I will report the results

**Comment by LeoNerdoG** [comment]
Hey @miricy,
I have checked out the commit 7b318 and rebuild Kura and I am still able to login to my Kura normally with admin:admin so I think there is something wrong on your side. 
Don't clear the GIT cache, clear the cache in your browser(s) (Firefox, Chrome....), becasue this is the root cause for many problems. 
Nonetheless, if this does not help, please let us know.

**Comment by nicolatimeus** [comment]
Hi  @miricy, what environment are you using for testing?
Please make sure to delete xml snapshots created before this PR and start from the `snapshot_0.xml` with the modifications in this PR. Otherwise the web ui might use incorrect password configuration.
If you are testing on a physical device (e.g. Raspberry PI) remove previous kura installation completely (uninstall the deb package and then also remove the /opt/eclipse/kura folder manually) and then reinstall.

**Comment by miricy** [comment]
The platform is amlogic a113d with buildroot linux.
I clear the cache and rebuild code and remove the /opt/eclipse/kura folder.
The problem is solved.  Thank you very much.

**Pull request merged**
