### PR TITLE
Small build fixes to include wires

### PR DESCRIPTION
**Pull request by MMaiero**
Implies changes in manifest-pom and web2 bundles to build and include wires as
dependencies.

Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@ctron Since Kura 3.0.0 will go for Java 1.8 I think we need to relax the Travis bree check. Cloud you do it?

**Comment by ctron** [comment]
There is no need to relax the BREE step. Just declare the correct BREE on the bundle.

**Comment by ctron** [comment]
Let's discuss this during the project call today.

**Comment by ctron** [comment]
I think setting the proper BREE should be enough.

**Pull request merged**
