### PR TITLE
Implemented changes to prevent eth0 toggling when wlan0 is disabled.

### LINKED ISSUE #721: Unnecessary toggles eth0 interface when wlan0 interface is disabled on Raspberry Pi.
I saw this when testing release-2.1.0 on Raspberry Pi 2.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

Closes #721

@ibinshtok Could you have a look at it?

### CODE REVIEW

**Comment by ibinshtok** [comment]
@MMaiero I will take a look at this on Monday.

**Comment by ibinshtok** [comment]
@MMaiero I tried the kura_3.0.0-SNAPSHOT_raspberry-pi-2_installer.sh from the fix_eth-disable-wlan branch an it looks like eth0 interface is still toggled when wlan0 is disabled in configuration. Here is the log:
2017-03-10 11:53:28,589 [qtp2525856-31] INFO  / - org.eclipse.kura.web.server.GwtNetworkServiceImpl: Trying www resource2: /www/denali/8147BECB8FD2358AD6B8F7CD5F7AB47B.gwt.rpc
2017-03-10 11:53:28,894 [qtp2525856-31] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2017-03-10 11:53:44,980 [qtp2525856-35] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2017-03-10 11:53:45,217 [qtp2525856-35] INFO  o.e.k.n.a.v.l.WpaSupplicantConfigWriter - Network interface status for wlan0 is disabled - not overwriting wpaconfig file
2017-03-10 11:53:45,220 [qtp2525856-35] INFO  o.e.k.n.a.v.l.HostapdConfigWriter - Network interface status for wlan0 is disabled - not overwriting hostapd configuration file
2017-03-10 11:53:45,374 [qtp2525856-35] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Getting component configurations...
2017-03-10 11:53:45,412 [WifiMonitor Thread] INFO  o.e.k.n.a.m.WifiMonitorServiceImpl - monitor() :: Found a new network configuration, will check if wifi has been reconfigured ...
2017-03-10 11:53:45,463 [WifiMonitor Thread] INFO  o.e.k.n.a.m.WifiMonitorServiceImpl - WifiMonitor: configuration for wlan0 has changed
2017-03-10 11:53:45,492 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 stop
2017-03-10 11:53:45,828 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 stop returned with exit value:0
2017-03-10 11:53:45,840 [WifiMonitor Thread] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface wlan0 down
2017-03-10 11:53:46,120 [EthernetMonitor_eth0] INFO  o.e.k.n.a.m.EthernetMonitorServiceImpl - Found a new Ethernet network configuration for eth0
2017-03-10 11:53:46,233 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill pid 1653
2017-03-10 11:53:46,236 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill 1653
2017-03-10 11:53:46,272 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill 1653 returned with exit value:0
2017-03-10 11:53:46,273 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 1653
2017-03-10 11:53:46,282 [EthernetMonitor_eth0] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface eth0 down
2017-03-10 11:53:46,395 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - stopping pid=1513
2017-03-10 11:53:46,479 [EthernetMonitor_eth0] INFO  o.e.k.l.n.d.DhcpClientManager - disable() :: killing DHCP client for eth0
2017-03-10 11:53:46,576 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill pid 1513
2017-03-10 11:53:46,577 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill 1513
2017-03-10 11:53:46,672 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill -9 pid 476
2017-03-10 11:53:46,673 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill -9 476
2017-03-10 11:53:46,692 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill 1513 returned with exit value:0
2017-03-10 11:53:46,693 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 1513
2017-03-10 11:53:46,703 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill -9 476 returned with exit value:0
2017-03-10 11:53:46,705 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 476
2017-03-10 11:53:46,873 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifdown eth0

2017-03-10 11:53:47,842 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifdown eth0
 returned with exit value:0
2017-03-10 11:53:47,844 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifconfig eth0 down

2017-03-10 11:53:47,952 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifconfig eth0 down
 returned with exit value:0
2017-03-10 11:53:48,250 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifdown wlan0

2017-03-10 11:53:48,285 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifdown wlan0
 returned with exit value:0
2017-03-10 11:53:48,286 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifconfig wlan0 down

2017-03-10 11:53:48,291 [qtp2525856-35] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2017-03-10 11:53:48,325 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifconfig wlan0 down
 returned with exit value:0
2017-03-10 11:53:48,749 [EthernetMonitor_eth0] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface eth0 up
2017-03-10 11:53:48,750 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: dhclient -r eth0

2017-03-10 11:53:48,762 [qtp2525856-35] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 0...
2017-03-10 11:53:48,945 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - dhclient -r eth0
 returned with exit value:0
2017-03-10 11:53:49,091 [qtp2525856-35] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1489168428871.xml...
2017-03-10 11:53:49,133 [EthernetMonitor_eth0] INFO  o.e.k.l.n.d.DhcpClientManager - enable() :: Starting DHCP client for eth0

**Comment by MMaiero** [comment]
Uhm, strange. It never happened to me. I'll try to have another look. Thanks for trying.

**Comment by nicolatimeus** [comment]
I've tested it now and it seems to be working, no eth0 toggles: 

```
2017-03-13 14:52:43,176 [EventAdmin Async Event Dispatcher Thread] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2017-03-13 14:52:43,177 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 stop
2017-03-13 14:52:43,224 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 stop returned with exit value:0
2017-03-13 14:52:51,660 [DnsMonitorServiceImpl] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2017-03-13 14:52:57,058 [qtp1300559-34] INFO  o.e.k.n.a.v.l.WpaSupplicantConfigWriter - Network interface status for wlan0 is disabled - not overwriting wpaconfig file
2017-03-13 14:52:57,058 [qtp1300559-34] INFO  o.e.k.n.a.v.l.HostapdConfigWriter - Network interface status for wlan0 is disabled - not overwriting hostapd configuration file
2017-03-13 14:52:57,093 [qtp1300559-34] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Getting component configurations...
2017-03-13 14:52:57,112 [EventAdmin Async Event Dispatcher Thread] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2017-03-13 14:52:57,113 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 stop
2017-03-13 14:52:57,162 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 stop returned with exit value:0
2017-03-13 14:52:57,206 [WifiMonitor Thread] INFO  o.e.k.n.a.m.WifiMonitorServiceImpl - monitor() :: Found a new network configuration, will check if wifi has been reconfigured ...
2017-03-13 14:52:57,243 [WifiMonitor Thread] INFO  o.e.k.n.a.m.WifiMonitorServiceImpl - WifiMonitor: configuration for wlan0 has changed
2017-03-13 14:52:57,278 [WifiMonitor Thread] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface wlan0 down
2017-03-13 14:52:57,310 [WifiMonitor Thread] INFO  o.e.k.l.n.d.DhcpClientManager - disable() :: killing DHCP client for wlan0
2017-03-13 14:52:57,341 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill -9 pid 10520
2017-03-13 14:52:57,342 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill -9 10520
2017-03-13 14:52:57,354 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill -9 10520 returned with exit value:0
2017-03-13 14:52:57,355 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 10520
2017-03-13 14:52:57,413 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - stopping pid=10511
2017-03-13 14:52:57,442 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill pid 10511
2017-03-13 14:52:57,442 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill 10511
2017-03-13 14:52:57,449 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill 10511 returned with exit value:0
2017-03-13 14:52:57,450 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 10511
2017-03-13 14:52:57,474 [qtp1300559-34] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1489416749873...
2017-03-13 14:52:57,561 [qtp1300559-34] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1489416777523.xml...
2017-03-13 14:52:57,611 [qtp1300559-34] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1489416777523.xml... Done.
2017-03-13 14:52:59,578 [WifiMonitor Thread] INFO  o.e.k.n.a.m.WifiMonitorServiceImpl - monitor() :: No enabled wifi interfaces - shutting down monitor thread
2017-03-13 14:52:59,587 [EventAdmin Async Event Dispatcher Thread] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2017-03-13 14:52:59,588 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 stop
2017-03-13 14:52:59,634 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 stop returned with exit value:0
2017-03-13 14:53:51,678 [DnsMonitorServiceImpl] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2
```

**Comment by MMaiero** [comment]
@ibinshtok Could you give it a test? I've done some slight changes.

**Comment by ibinshtok** [comment]
@MMaiero will do

**Review by ibinshtok — APPROVED** [review]
@MMaiero it works now. Tested on Pi2 and RG 10-20.

**Pull request merged**
