### PR TITLE
AssetService and DriverService separated in two different bundles

### PR DESCRIPTION
**Pull request by amitjoy**
This enables easy replacement of bundles at runtime

### CODE REVIEW

**Comment by ctron** [comment]
You will also need to update the "distrib" project. Maybe you can use this [1] as a guide.

[1] https://github.com/eclipse/kura/wiki/Adding-a-new-bundle-to-Kura

**Comment by amitjoy** [comment]
@ctron My Bad! I forgot to add the bundles to distribution. 👍

**Comment by ctron** [comment]
I just added a comment Karaf in the Wiki page. That has to be done as well.

**Comment by amitjoy** [comment]
Also fixes #1022

**Review by ctron — APPROVED** [review]
Looks good to me

**Comment by MMaiero** [comment]
Merged

**Pull request merged**
