### PR TITLE
Solves antrun build warnings by reordering plugin invocations.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
Closes #619

**Comment by cdealti** [comment]
@MMaiero we agreed on not creating new PRs before rewriting the history. I propose to postpone (close) it.

**Comment by ctron** [comment]
I don't think we need to close. Keeping it open doesn't hurt at all.

**Comment by cdealti** [comment]
Closing due to history rewrite

**Pull request closed without merging**
