### PR TITLE
Added reset confirmation in settings tabs

### LINKED ISSUE #3002: No Prompt When Reseting Changes in Settings Services
When user clicks "Reset" button, there is normally a confirmation prompt that gives user one last chance to change his mind. But this is not the case for several services listed bellow. I think this should be unified, because it is always good to have a confirmation box in case reset was clicked by accident (it can happen, believe me). 
Affected tabs:
 - Settings -> SSL Configuration (Already reported with issue #2729)
 - Settings -> Server SSL Certificate (Already reported with issue #2729)
 - Settings -> Device SSL Certificate (Already reported with issue #2729)
 - Settings -> Command User 

**Testflow:**
1. Login to kura as admin/admin
2. Go to service/tab as listed above and try to press reset button after you amde some changes
3. Observe the lack of confirmation prompt

**Expected behavior**
See above. 

**Screenshots**
/

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: latest develop branch (July 27th, 2020)

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #3002

### CODE REVIEW

**Comment by MMaiero** [comment]
@mstankovic Can you give a look also at this?

**Comment by mstankovic** [comment]
@MMaiero tests have passed:
- also checked issue manually and confirming that is fixed.

**Comment by mstankovic** [comment]
@MMaiero there are few things here:

1
- different behavior for those two tabs: SSL Configuration and Server SSL Certificate
- i change value for some field and remove focus to enable Reset button
- click on Reset button and click on No (on Confirmation dialog)
- for SSL Configuration tab i have Reset button enabled and for Server SSL tab its disabled

2
- for moving from tab to tab
- i have some field modified and try to change active tab
- I have 2nd confirmation dialog although I confirmed moving on the first confirmation dialog

3
- i am on Server SSL Certificate, Device SSl Certificate or Command User tab
- i have modified some field
- click on Reset button and press **No** from confirmation dialog
- try to change active tab
-> missing Confirmation dialog

im not sure if those are new issues

**Comment by MMaiero** [comment]
I will have a look at those

**Comment by MMaiero** [comment]
@mstankovic Issues should be gone now. Please double check.

**Review by pierantoniomerlino — APPROVED** [review]

**Pull request merged**
