### PR TITLE
Fixed Internet Explorer EventSource streaming

### PR DESCRIPTION
**Pull request by amitjoy**

### CODE REVIEW

**Comment by MMaiero** [comment]
Tested on IE 11: it does not work

**Comment by amitjoy** [comment]
So far what I have found, [1] indicates the problem about IE 9. Not sure if it is different in IE10+.

[1] - https://blogs.msdn.microsoft.com/ieinternals/2010/04/05/comet-streaming-in-internet-explorer/

**Comment by MMaiero** [comment]
Can we close this in favour of #1152?

**Comment by amitjoy** [comment]
@MMaiero We can close this as #1151 provides generic support for streaming OSGi events to Server Sent Events clients in all the browsers inclusive of Internet Explorer.

**Pull request closed without merging**
