### PR TITLE
Updated Equinox OSGi to equinox-SDK-4.17

### LINKED ISSUE #3140: Update Equinox dependency
**Is your feature request related to a problem? Please describe.**
The Equinox instance bundled with Kura should be updated to leverage the latest features of the framework and APIs.

**Describe the solution you'd like**
The current available version of the Equinox SDK is 4.17

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@mstankovic Can you have a run of this PR?

**Comment by mstankovic** [comment]
@MMaiero I checked this PR. Kura is building successfully and installing without errors. Able to access web UI and some basic tests are passing. 
Also noted that user_workspace_archive_x.y.z.zip is missing in distrib/target/ folder - is that expected?

If we need Kura DEv workspace to be tested we could ask @LeoNerdoG to help as?

**Comment by MMaiero** [comment]
I didn't pay attention to the workspace. I'll try to build it and see if it is broken.

**Comment by MMaiero** [comment]
I have not tested it, but it is built.

**Comment by MMaiero** [comment]
@mstankovic I have just tested the dev-env produced by the build of this branch and it works for me.

**Review by nicolatimeus — APPROVED** [review]

**Pull request merged**
