### PR TITLE
Revert "#408 Let service tracker only track relevant services"

### PR DESCRIPTION
**Pull request by MMaiero**
Reverts eclipse/kura#409
As discussed, I'm reverting this PR in order to merge the PRs that I've merged locally

### CODE REVIEW

**Comment by ctron** [comment]
So there was no "discussion" around that. Just a decision from your side. Which btw conflicted with the actual discussion we had on the project call.

**Comment by MMaiero** [comment]
I'm sorry for the misunderstanding. That was not my original plan but, while trying to perform the merges of the various pull requests, this commit caused me many troubles. So, I thought that the best option was to revert your commit and push in `merge_pull_requests` all the PRs that we want to merge (it carries also #408 with a fix) before the rewriting, in the order that generated less conflicts.

**Comment by dwoodard1** [comment]
@MMaiero Maybe you could explain better. Are you saying that the original PR #408 was included in #659? Are the changes introduced by @ctron in #408 now merged successfully in develop?

**Comment by MMaiero** [comment]
@dwoodard1 Yes

**Comment by cdealti** [comment]
> So there was no "discussion" around that. Just a decision from your side. Which btw conflicted with the actual discussion we had on the project call.

@ctron you are right. However I asked Matteo to manually merge 6 pull requests before the history rewrite because I wanted to make sure we could fix any conflicts occurring during the merge and avoid asking the authors to rebase their PR again.
If you check your inbox I sent you an email on October 18th with the list of pull requests. #409 was in that list.

**Pull request merged**
