### PR TITLE
Added login background.

### PR DESCRIPTION
**Pull request by MMaiero**
Updated css.

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by kartben** [comment]
fwiw you may not want to use the Eclipse *IDE* logo :-)

**Comment by MMaiero** [comment]
You are right! 
Thanks for pointing that out! :-)

**Comment by MMaiero** [comment]
Screenshots:
Screenshot 2019-06-19 at 15 56 08

**Comment by kartben** [comment]
@MMaiero nice!

**Comment by MMaiero** [comment]
A possible alternative background page:
Eclipse_IoT_Kura_Login_Background

**Comment by ctron** [comment]
I do understand the use of the "Eclipse IoT" logo here, what I don't understand is the use of the "Eclipse Foundation" logo. In any case, before using a logo like that, I would get formal approval by the brand team and/or EMO:

* marketing@eclipse.org
* https://www.eclipse.org/legal/logo_guidelines.php
* https://www.eclipse.org/legal/documents/eclipse_foundation_branding_guidelines.pdf

**Comment by MMaiero** [comment]
Hi, thanks for the feedback.
We are already in contact with the Eclipse Foundation and with Frederic as well.
Actually, they already have seen and approved the usage of the first version.

Best regards,
Matteo

**Review by nicolatimeus — APPROVED** [review]

**Pull request merged**
