### PR TITLE
Updated spring dependency to 4.3.20

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Do not merge! Wait for CQs!

### CODE REVIEW

**Comment by MMaiero** [comment]
@mstankovic Can you please give a run of this issue? Thanks

**Review by pierantoniomerlino — APPROVED** [review]

**Comment by MMaiero** [comment]
CQs created, waiting for approval

**Comment by mstankovic** [comment]
@MMaiero there are few failing tests but nothing related to this change.

**Comment by MMaiero** [comment]
As suggested by the PMC team, the CQs are not needed since Spring project uses semantic versioning and there are already approved CQs for 4.3.x releases. The PR can then be merged.

**Pull request merged**
