### PR TITLE
First implementation of Triton inference engine

### PR DESCRIPTION
**Pull request by pierantoniomerlino**
This is the implementation of the ai inference APIs for the Nvidia Triton Server.

Signed-off-by: Merlino <pierantonio.merlino@eurotech.com>

### CODE REVIEW

**Comment by pierantoniomerlino** [comment]
Below are the screenshots for the dependencies taken from ClearyDefined.

Screenshot 2022-02-18 at 17 30 13
Screenshot 2022-02-18 at 17 20 42
Screenshot 2022-02-18 at 17 21 30
Screenshot 2022-02-18 at 17 22 13
Screenshot 2022-02-18 at 17 22 39
Screenshot 2022-02-18 at 17 23 02
Screenshot 2022-02-18 at 17 23 25
Screenshot 2022-02-18 at 17 23 57
Screenshot 2022-02-18 at 17 25 30
Screenshot 2022-02-18 at 17 26 42
Screenshot 2022-02-18 at 17 27 48

**Comment by pierantoniomerlino** [comment]
Awaiting [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23956)

**Comment by MMaiero** [comment]
Build is failing. Please check

**Comment by pierantoniomerlino** [comment]
For testing:

Screenshot 2022-02-21 at 11 19 41

**Comment by pierantoniomerlino** [comment]
Moved to https://github.com/pierantoniomerlino/kura/tree/edge_ai

**Pull request closed without merging**
