### PR TITLE
Switch default behavior to only track relevant services

### PR DESCRIPTION
**Pull request by ctron**
Also change private fields to new Kura style.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by cdealti** [comment]
Maybe we could use this PR to also remove some wrong registered services.
Examples need to only provide ConfigurableComponent. Registering an implementation class does not makes sense.
See https://github.com/eclipse/kura/commit/c88cce61fe9f7d3370a0f464d66fd61ecedd1f59

**Comment by ctron** [comment]
Sure, I can amend this PR.

**Comment by ctron** [comment]
On a second thought, maybe we keep this as is not to break accidentally anything. Because this change cannot be reversed by changing a system property.

**Comment by ctron** [comment]
We will create a new PR for removing the double registration.

**Comment by MMaiero** [comment]
Merging. Let's see what happens 😂

**Pull request merged**
