### PR TITLE
Modified log message in ConfigurationServiceImpl.java

### PR DESCRIPTION
**Pull request by MMaiero**
Modified the logging message in registerComponentOCD to not log the OCD definition
when the logger is in info. Added a more complete message that will be logged when
the logger is in debug.

Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@markoer Is there a particular requirement for the toStrings in OCD-related classes?

**Comment by markoer** [comment]
Only that a few tests rely on it. If you delete toString()s, tests will fail. Nothing serious.

**Comment by MMaiero** [comment]
Do you think we can have the tests working without that toString? I would prefer not exposing that stuff.

**Comment by markoer** [comment]
Merge the PR and I'll update the tests. It seems to me that the build is configured so that failing tests don't fail the build itself.

**Pull request merged**
