### PR TITLE
Kura container management (Container Provider - Factory) [depends on PR 1] #2

### PR DESCRIPTION
**Pull request by GregoryIvo**
This PR contains a bundle which uses the org.eclipse.kura.container.orchestraion.provider, and provides a configurable-component factory that allows the user to define containers.

Description of the solution adopted:
This solution utilizes a bundle (org.eclipse.kura.container.orchestration.provider) added in a previous PR

Parameters set in a configurable component generates a org.eclipse.kura.container.orchestration.provider.ContainerDescriptor, that is then past to the container-api to instruct a getaways docker-engine to make containers.

Screenshots: If applicable, add screenshots to help explain your solution

image

Any side note on the changes made: Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by GregoryIvo** [comment]
Builds successfully once merged with PR 1:

image

**Comment by MMaiero** [comment]
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23950 created

**Comment by MMaiero** [comment]
@GregoryIvo Can you please rebase? Thanks

**Comment by MMaiero** [comment]
Please check this branch as the build fails due to the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (raspberry-pi-ubuntu-20-jars) on project distrib: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/jenkins/agent/workspace/multibranch_PR-3795/kura/kura/distrib/src/main/ant/build_equinox_distrib.xml:198: The following error occurred while executing this line:
[ERROR] Target "container-orchestration-config" does not exist in the project "build_equinox_distrib". 
[ERROR] around Ant part ...<ant antfile="/home/jenkins/agent/workspace/multibranch_PR-3795/kura/kura/distrib/src/main/ant/build_equinox_distrib.xml" target="dist-linux"/>... @ 17:146 in /home/jenkins/agent/workspace/multibranch_PR-3795/kura/kura/distrib/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by GregoryIvo** [comment]
> Please check this branch as the build fails due to the following error:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (raspberry-pi-ubuntu-20-jars) on project distrib: An Ant BuildException has occured: The following error occurred while executing this line:
> [ERROR] /home/jenkins/agent/workspace/multibranch_PR-3795/kura/kura/distrib/src/main/ant/build_equinox_distrib.xml:198: The following error occurred while executing this line:
> [ERROR] Target "container-orchestration-config" does not exist in the project "build_equinox_distrib". 
> [ERROR] around Ant part ...<ant antfile="/home/jenkins/agent/workspace/multibranch_PR-3795/kura/kura/distrib/src/main/ant/build_equinox_distrib.xml" target="dist-linux"/>... @ 17:146 in /home/jenkins/agent/workspace/multibranch_PR-3795/kura/kura/distrib/target/antrun/build-main.xml
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> ```

This should be fixed now. 

Edit: Ready to go!

**Comment by MMaiero** [comment]
Great! Thanks

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
