### PR TITLE
ci: switch to Java 17 for CI builds

### PR DESCRIPTION
**Pull request by MMaiero**
This PR switches to Java17 for CI builds

This PR additionally performs the following:
1. Adds the Surefire rerun policy to our CI build.
2. Disable failing tests on Java17. See list below for details.
3. Removes the DP packages from the `buildAll` target
4. Updates our main README to only refer to Java 17

#### Details
 
This PR started off as a simple update to the `manve-surefire-plugin` rerun policy. We later found out that we need to switch to Java 17 for it to work properly and decided to do so since we needed it anyway (see: #5478)

Then we found out that some tests fails in the Java17 profile which prompted us to disable them and address the issue at a later date (see: https://eurotech.atlassian.net/browse/ECESF-8549)

Finally, we removed all `.dp` from the `buildAll` target since we cannot generate `.dp` packages with Java17 and the `distrib` build would fail since it was looking for them (see https://eurotech.atlassian.net/browse/ECESF-3770)

#### Disabled tests

1. DeploymentAgentTest
7. LinuxNetworkUtilTest
8. ~NMDbusConnectorTest~ fixed in 4481dd471abea19ef7252e737887d8723dbc24e5
9. PackagesRestServiceTest

### CODE REVIEW

**Review by mattdibi — CHANGES_REQUESTED** [review]
This doesn't seem to be working 🤔 

For some reason, even on `develop`, the test reports are duplicated... but this is a separate issue.

Looking at the test reports I can't see the failing tests being re-run (apart from the duplication mentioned above).

**Comment by mattdibi** [comment]
Tested locally on a modified **unit** test and it seems to be working correctly:

image

image

It doesn't seem to be working correctly for **integration** tests... some further investigation is needed

**Comment by MMaiero** [comment]
There it could be on the java version used that dictate the tycho plugin used.
If building java 8, it is using an old version of the plugin that it may have no support for such property

**Comment by mattdibi** [comment]
@MMaiero 🤔  in the CI we're building with Java8, see: https://github.com/eclipse-kura/kura/blob/27b8caa7a9f2551be6a8fb1601e7e3c06ec6f14b/Jenkinsfile#L21

**Comment by mattdibi** [comment]
@MMaiero I tested it locally on a Java17 installation. It does work simply by adding `-Dsurefire.rerunFailingTestsCount` in the test run command.

How do we want to proceed now?
1. Personally I would prefer enabling the `rerun` in the CLI command rather than modifying the POM. During development I want my tests to fail fast and not be re-ran since they might simply be broken because we're developing them. Having the `rerun` in the CLI command is much more flexible. What do you think?
2. Should we switch to Java17 for CI builds? It'll become a necessary shortly with #5478 right?

**Comment by MMaiero** [comment]
Yes to both. Le't's use the command line instead of the configuration in pom files.
Let's start the switch to java 17 as baseline

**Comment by mattdibi** [comment]
Good news is that it's working:

image

Bad news is that there are broken tests since we are not running them regularly and we'll need to fix them...

**Comment by mattdibi** [comment]
For documentation purposes: we decided to disable the failing tests for now and fix them at a later date.

**Review by mattdibi — DISMISSED** [review]

**Review by mattdibi — APPROVED** [review]

**Comment by marcellorinaldo** [comment]
Do not merge yet, have to check something...

**Review by marcellorinaldo — APPROVED** [review]
Looks good to me

**Comment by mattdibi** [comment]
@salvatore-coppola if you don't see any issues I would proceed with merging this

**Pull request merged**
