### PR TITLE
Modified checksum calculation.

### LINKED ISSUE #523: [Speed up build] Checkums are generated multiple times
To me it looks the process of generating checksums (which is rather time consuming and CPU intensive) is generating checksums of the same artifacts over and over again during one build process:

The following snippet from a standard Kura build shows that both executions (raspberry-pi-2-deb-checksums and raspberry-pi-2-nn-deb-checksums) generate the checksums for the same files.

So instead of generating N checksums for N device profiles, it actually generated N² checksums.

```
[INFO] --- checksum-maven-plugin:1.3:files (raspberry-pi-2-deb-checksums) @ distrib ---
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2-nn_installer.deb - MD5 : bae6a0fbdabc1684884f193238619295
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2-nn_installer.deb - SHA-1 : 38ebdc386952efc00d1561e6e95630d480ee0d91
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi_installer.deb - MD5 : b2b21eb4e8007d56a984a1ba8542c2ba
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi_installer.deb - SHA-1 : cae98a14696750d4381338a14aff58f0521c7a04
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus-nn_installer.deb - MD5 : 290f5c962a6ef692c9ad4d2aec09131b
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus-nn_installer.deb - SHA-1 : 472e55def127bf1f253fa7f76106771d67e6f02d
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-nn_installer.deb - MD5 : 5b0a6a79e5b738cdf04434e83da03834
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-nn_installer.deb - SHA-1 : 6dbf91462aac859f5eb5291bcc9c64bd327fc5df
[INFO] kura_2.1.0-SNAPSHOT_beaglebone_debian_installer.deb - MD5 : f3191b0fa3254a1dd5d04093ca05ecfa
[INFO] kura_2.1.0-SNAPSHOT_beaglebone_debian_installer.deb - SHA-1 : a8ede9162e604a72dc2b8ea6ce50e35535408204
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus_installer.deb - MD5 : ffc87478cde16528d4ffb7520f37777f
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus_installer.deb - SHA-1 : 13c39f24f976be96f470e2d040e57bf1bda5a8c6
[INFO] kura_2.1.0-SNAPSHOT_beaglebone-nn_debian_installer.deb - MD5 : ba0185b7825fb3e50099bff3600457ac
[INFO] kura_2.1.0-SNAPSHOT_beaglebone-nn_debian_installer.deb - SHA-1 : 674ac35b631cf75fccac7770be915946b7282ebd
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2_installer.deb - MD5 : a4b4d322a1a47c406a84488e568ad195
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2_installer.deb - SHA-1 : 18275d78bd5fa3269098f9184fb284739e6a61ef
[INFO] 
[INFO] --- checksum-maven-plugin:1.3:files (raspberry-pi-2-nn-deb-checksums) @ distrib ---
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2-nn_installer.deb - MD5 : bae6a0fbdabc1684884f193238619295
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2-nn_installer.deb - SHA-1 : 38ebdc386952efc00d1561e6e95630d480ee0d91
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi_installer.deb - MD5 : b2b21eb4e8007d56a984a1ba8542c2ba
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi_installer.deb - SHA-1 : cae98a14696750d4381338a14aff58f0521c7a04
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus-nn_installer.deb - MD5 : 290f5c962a6ef692c9ad4d2aec09131b
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus-nn_installer.deb - SHA-1 : 472e55def127bf1f253fa7f76106771d67e6f02d
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-nn_installer.deb - MD5 : 5b0a6a79e5b738cdf04434e83da03834
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-nn_installer.deb - SHA-1 : 6dbf91462aac859f5eb5291bcc9c64bd327fc5df
[INFO] kura_2.1.0-SNAPSHOT_beaglebone_debian_installer.deb - MD5 : f3191b0fa3254a1dd5d04093ca05ecfa
[INFO] kura_2.1.0-SNAPSHOT_beaglebone_debian_installer.deb - SHA-1 : a8ede9162e604a72dc2b8ea6ce50e35535408204
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus_installer.deb - MD5 : ffc87478cde16528d4ffb7520f37777f
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-bplus_installer.deb - SHA-1 : 13c39f24f976be96f470e2d040e57bf1bda5a8c6
[INFO] kura_2.1.0-SNAPSHOT_beaglebone-nn_debian_installer.deb - MD5 : ba0185b7825fb3e50099bff3600457ac
[INFO] kura_2.1.0-SNAPSHOT_beaglebone-nn_debian_installer.deb - SHA-1 : 674ac35b631cf75fccac7770be915946b7282ebd
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2_installer.deb - MD5 : a4b4d322a1a47c406a84488e568ad195
[INFO] kura_2.1.0-SNAPSHOT_raspberry-pi-2_installer.deb - SHA-1 : 18275d78bd5fa3269098f9184fb284739e6a61ef
```

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

Closes #523 

@ctron

### CODE REVIEW

**Comment by ctron** [comment]
Ok .. that overlapped :wink: ... #527 

My intention was to make it less specific not more specific. Problem is that the plugin which is being used has an issue with having "no files".

If you want to specific a single file I would check the "file" goal of the plugin [1]. But this will probably not work as expected since will always overwrite the ".csv" file.

If you don't like the "dummy" file approach from #527, which I could understand, then I suggest to make a simple "javascript" or "groovy" approach and do it "manually".

[1] http://nicoulaj.github.io/checksum-maven-plugin/file-mojo.html

**Comment by MMaiero** [comment]
Currently, for our needs the .csv file is not necessary: we use only the .md5 and .sha1 files that contain the checksums.
I've looked at [1] but I don't think there is a big difference on that. Furthermore the [1] description reports: "Compute specified file checksum digest for all supported checksum algorithms." and it's not we currently need.

**Comment by ctron** [comment]
Then please set `csvSummary` to `false`

**Comment by ctron** [comment]
+1

**Pull request merged**
