### PR TITLE
Wire Service Implementation and Wire Configuration Refactoring

### PR DESCRIPTION
**Pull request by amitjoy**

### CODE REVIEW

**Comment by MMaiero** [comment]
Could you please rebase this into a single commit since are all related and cannot be separate one each other?
Furthermore, I would suggest you to keep consistency with the existing Kura code and not order methods in WireServiceImpl.java by name.

**Comment by amitjoy** [comment]
@MMaiero You can also squash the commits while merging.

I personally prefer following naming convention that I find it useful to track in a class and that's why I order the methods in alphabetical order. And Eclipse Platform developers has surveyed this need and provided the option. I am not sure if Kura has such restrictions on method ordering. If yes, would you kindly refer me to it? I would then follow it from the next time onwards.

**Comment by MMaiero** [comment]
Which is the option you used to setup that ordering?
It's better if you perform the squashing of your commits.

**Comment by amitjoy** [comment]
`Member Sort Order` Option in Eclipse Preferences

**Comment by MMaiero** [comment]
This one?

schermata 2017-02-14 alle 12 10 28

I have Mars and it is not reordering methods. Is it a new feature?

**Comment by MMaiero** [comment]
However, I think that this was an implicit assumption that all the Kura developers followed to have the same structuring throughout all the project.
We had never the need to formalize it. (Maybe also there was no option at that time, but I may be wrong).

If needed we can formalize it, otherwise it becomes a mess.

**Comment by amitjoy** [comment]
bildschirmfoto 2017-02-14 um 12 13 00 pm

Check in `Save Actions`

**Comment by amitjoy** [comment]
It would also be good to formalize the placement of the methods in Kura documentation.

**Comment by amitjoy** [comment]
Squashed it to single commit

**Comment by MMaiero** [comment]
This is mine:
schermata 2017-02-14 alle 13 51 00

**Pull request merged**
