### PR TITLE
fix: Fixed kura archetype-metadata

### LINKED ISSUE #4340: Kura archetype-metadata is incorrect
**Describe the bug**
Mandi fantats!

The target platform information contained in the archetype-metadata conf file is incorrect: it still references equinox_3.11.1 and there's no mention to the test-deps p2.

**To Reproduce**
N/A

**Expected behavior**
Target platform references should be corrected

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - Any

**Additional context**

### PR DESCRIPTION
**Pull request by iacco**
Fixed kura archetype-metadata by adding the correct target platform information.

**Related Issue:** This PR fixes/closes #4340 

**Description of the solution adopted:** N/A

**Screenshots:** N/A

**Any side note on the changes made:** N/A

### CODE REVIEW

**Comment by marcellorinaldo** [comment]
@iacco Can you please give a quick try? It has been a while since last used....

Compile tools, install the archetype to your local .m2:

```shell
mvn install:install-file -Dfile=<path-to-archetype-jar>.jar -DgroupId=org.eclipse.kura -DartifactId=example-archetype -Dversion=0.4.0-SNAPSHOT -Dpackaging=jar
```

Then test the archetype:

```shell
mvn archetype:generate -DarchetypeArtifactId=example-archetype -DarchetypeGroupId=org.eclipse.kura -DarchetypeVersion=0.4.0-SNAPSHOT
```

**Comment by iacco** [comment]
Oilala!

Actually I did test it before pushing it, on the release tag for 5.2.1, and it generated the JAR correctly, even without your latest commit.
Do you have trouble building it?

There is something wrong _at build time of the example archetype_, since it is expected that:
- groupId and artifactId are set to **example** 
- version is set to **1.0.0-SNAPSHOT**

Also, I had some issues with the pom of the example, on the _format_ tag on the tycho packaging plugin:
```
<plugin>
    <groupId>org.eclipse.tycho</groupId>
    <artifactId>tycho-packaging-plugin</artifactId>
    <version>1.6.0</version>
    <configuration>
        <archive>
            <compress>false</compress>
        </archive>
        <format>'${kura.build.version}'</format>
        <strictVersions>true</strictVersions>
    </configuration>
</plugin>
```
By removing that conf, and if the values are set correctly, it works fine!

I did not however try to build it and use it from a clean env, so if you have trouble building maybe that could be a difference... should I do a "clean" run?

Also, available to talk about this in front of a _taj_ in tavola di Carnia this Thursday! 😉 

Mandi,
iacco

**Comment by marcellorinaldo** [comment]
> Oilala!
> 
> Actually I did test it before pushing it, on the release tag for 5.2.1, and it generated the JAR correctly, even without your latest commit. Do you have trouble building it?

Yes, but I forgot to build distrib with dev-env profile. Already reverted the changes.

> 
> There is something wrong _at build time of the example archetype_, since it is expected that:
> 
> * groupId and artifactId are set to **example**
> * version is set to **1.0.0-SNAPSHOT**
> 
> Also, I had some issues with the pom of the example, on the _format_ tag on the tycho packaging plugin:
> 
> ```
> <plugin>
>     <groupId>org.eclipse.tycho</groupId>
>     <artifactId>tycho-packaging-plugin</artifactId>
>     <version>1.6.0</version>
>     <configuration>
>         <archive>
>             <compress>false</compress>
>         </archive>
>         <format>'${kura.build.version}'</format>
>         <strictVersions>true</strictVersions>
>     </configuration>
> </plugin>
> ```
> 
> By removing that conf, and if the values are set correctly, it works fine!

Feel free to remove it if it works.

> 
> I did not however try to build it and use it from a clean env, so if you have trouble building maybe that could be a difference... should I do a "clean" run?

Don't think it is necessary if everything works.

> 
> Also, available to talk about this in front of a _taj_ in tavola di Carnia this Thursday! 😉

Let's talk on thursday then!

> 
> Mandi, iacco

**Comment by MMaiero** [comment]
The issues with the build are now sorted.
@marcellorinaldo on you for the review

**Review by marcellorinaldo — APPROVED** [review]

**Pull request merged**
