### PR TITLE
feat(web2): Wpa enterprise EAP-TLS certificate support frontend

### PR DESCRIPTION
**Pull request by GregoryIvo**
This PR adds front-end support for: https://github.com/eclipse/kura/pull/4872

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped

**Screenshots:** If applicable, add screenshots to help explain your solution

**Manual Tests**: Optional description of the tests performed to check correct functioning of changes, useful for an efficient review

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by GregoryIvo** [comment]
V1 Web UI
image


I am now testing to see if dropdowns with key stores are possible now.

**Comment by GregoryIvo** [comment]
Almost ready for review:
Just need to add a default password value

**Comment by mattdibi** [comment]
Tested this at d4d9c2e03ba614777d7f0cafc7f364aa18deb320 in #4872. Looking good so far!

@GregoryIvo one question: do we really need two different fields for passing the client key if they are the same?

image

... or did I do something wrong?

**Comment by GregoryIvo** [comment]
This is correct, and expected. I was thinking about that too but am torn because I like the potential flexibility

**Comment by mattdibi** [comment]
> This is correct, and expected. I was thinking about that too but am torn because I like the potential flexibility

As a user I find it confusing... Why should I set the same for both if I added it as a single Pub/Priv key pair? Also I have a hard time imagining a situation in which this flexibility could be taken advantage of? Can you explain to me a scenario where these two separated fields can be useful? 🤔

**Comment by mattdibi** [comment]
Superseded by #4895

**Pull request closed without merging**
