### PR TITLE
feat(asset.provider): Added type for Scale and Offset in Channels

### PR DESCRIPTION
**Pull request by salvatore-coppola**
Added new field for Channel, scaleoffset.type which assign a type (Double, Float, Integer or Long) to scale and offset value used in the channel.

### CODE REVIEW

**Review by nicolatimeus — DISMISSED** [review]
Looks ok to me, we can merge once the Ci passes

**Comment by MMaiero** [comment]
Quality gate issues here. Can you give it a look? https://sonarcloud.io/summary/new_code?id=org.eclipse.kura%3Akura&branch=PR-5418
@salvatore-coppola

**Comment by salvatore-coppola** [comment]
> Quality gate issues here. Can you give it a look? https://sonarcloud.io/summary/new_code?id=org.eclipse.kura%3Akura&branch=PR-5418 @salvatore-coppola

why is there no longer a separate control on the github ui like before (I mean in the list)?

**Comment by MMaiero** [comment]
> > Quality gate issues here. Can you give it a look? https://sonarcloud.io/summary/new_code?id=org.eclipse.kura%3Akura&branch=PR-5418 @salvatore-coppola
> 
> why is there no longer a separate control on the github ui like before (I mean in the list)?

For what I can tell due to the organisation move

**Review by nicolatimeus — APPROVED** [review]

**Review by MMaiero — APPROVED** [review]

**Comment by MMaiero** [comment]
Forcing merge. Currently the Eclipse Jenkins instance is not working properly. We are going to merge the PRs and then perform a full build on Eclipse release-5.6.0 maintenance branch with, eventually, a following PR to fix remaining issues

**Pull request merged**
