### PR TITLE
The banner content cannot be empty.

### LINKED ISSUE #2852: Should Empty Login Banner be Allowed?
If user sets "Access Banner Enabled" to True and there is no content in "Access Banner Content" the message displayed upon login is empty - should this be allowed or not? What is the point to show an empty message? 

Also the banner's dialogue box should not be named "Warning" but "Info". It makes more sense?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to WebConsole Service and change "Access Banner Enabled" to True
3. Leave "Access Banner Content" empty
4. Logout and observe the empty banner message (screenshot bellow)

**Expected behavior**
See above.

**Screenshot:**
Screenshot 2020-05-06 at 07 44 36

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

### PR DESCRIPTION
**Pull request by MMaiero**
The banner content field is now a text area

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2852

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
hey @MMaiero,
I have checked this and I don't know if this is the reuslt of this PR or not, but anything I enter into the Banner field, I get an error "404 ProxyServlet: /admin/denali/xsrf " (sceenshot bellow). Can you please take a look at this if you can recreate the issue? 

Screenshot 2020-06-18 at 09 44 33

**Comment by MMaiero** [comment]
Just built and I have no issues like the one you reported

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I get this error in the kura.log when I change banner (banner is enabled):
Screenshot 2020-06-18 at 13 06 46

(text): 

> 2020-06-18T12:04:55,194 [qtp19431749-481] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1592478295056.xml...
2020-06-18T12:04:55,214 [qtp19431749-481] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1592478295056.xml... Done.
2020-06-18T12:04:55,228 [ConfigurationListener Event Queue] INFO  o.e.k.w.s.s.FileServlet - Servlet org.eclipse.kura.web.server.servlet.FileServlet destroyed
2020-06-18T12:05:18,948 [ConfigurationListener Event Queue] INFO  o.e.k.w.s.s.FileServlet - Servlet org.eclipse.kura.web.server.servlet.FileServlet initialized
2020-06-18T12:05:18,949 [ConfigurationListener Event Queue] INFO  o.e.k.w.s.s.FileServlet - DiskFileItemFactory.DEFAULT_SIZE_THRESHOLD: 10240
2020-06-18T12:05:18,949 [ConfigurationListener Event Queue] INFO  o.e.k.w.s.s.FileServlet - DiskFileItemFactory: using size threshold of: 10240
2020-06-18T12:06:21,603 [qtp19431749-486] WARN  o.e.k.w.s.s.SkinServlet - Failed to load skin resource, Resource File /skin.css does not exist
2020-06-18T12:06:21,618 [qtp19431749-481] WARN  o.e.k.w.s.s.SkinServlet - Failed to load skin resource, Resource File /skin.js does not exist
2020-06-18T12:06:21,648 [qtp19431749-1234] WARN  o.e.k.w.s.s.SkinServlet - Failed to load skin resource, Resource File /skin.js does not exist
2020-06-18T12:06:21,921 [qtp19431749-485] INFO  o.e.j.s.h.C.ROOT - org.eclipse.kura.web.server.GwtExtensionServiceImpl: Trying /www/login/7C9432B858408D227000923979407AE3.gwt.rpc
2020-06-18T12:06:21,968 [qtp19431749-1234] INFO  o.e.j.s.h.C.ROOT - org.eclipse.kura.web.server.GwtBannerServiceImpl: Trying /www/login/EE520C4015805E5EC9179F92F04A929F.gwt.rpc
2020-06-18T12:06:27,210 [qtp19431749-479] INFO  o.e.j.s.h.C.ROOT - org.eclipse.kura.web.server.GwtPasswordAuthenticationServiceImpl: Trying /www/login/069AF6548D557744519AAA48DBA5F908.gwt.rpc
2020-06-18T12:06:27,214 [qtp19431749-479] INFO  o.e.k.w.s.GwtPasswordAuthenticationServiceImpl - UI Login - Success - Login for user: admin, session id: node0yk8sdwgdx9491e12yipp8ov4o0, request IP: 10.19.40.101
2020-06-18T12:06:27,303 [qtp19431749-485] WARN  o.e.k.w.s.s.SkinServlet - Failed to load skin resource, Resource File /skin.css does not exist

**Comment by MMaiero** [comment]
It can be related to the fact that the web ui is reloaded from the web server.
So that may be the reason why you see an error because indeed the backend is reloading.
But the changes should be applied correctly.

**Comment by LeoNerdoG** [comment]
Yes, all the changes indeed are applied correctly, I can see the banner's text if the banner is enabled so from this standpoint the PR is good to merge. 
If you cannot reproduce the 404 error, I will keep digging, but in the meantine this PR can be merged, as it fixes the original issue.

**Review by LeoNerdoG — APPROVED** [review]

**Pull request merged**
