### PR TITLE
ci: Backport version automation 

### PR DESCRIPTION
**Pull request by MMaiero**
> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

### CODE REVIEW

**Comment by MMaiero** [comment]
@mattdibi Ok to merge?

**Comment by mattdibi** [comment]
@MMaiero this PR is also needed: https://github.com/eclipse/kura/pull/4037

**Comment by MMaiero** [comment]
Done

**Review by mattdibi — APPROVED** [review]
LGTM

**Comment by MMaiero** [comment]
Merging.
The build is failing in Jenkins because it is trying to rebuild Kura 5.1.2 that has been released.
This PR is instrumental in updating the maintenance branch for 5.1.3-SNAPSHOT

**Pull request merged**
