### PR TITLE
Disabled apparmor at framework installation.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
AppArmor seems to prevent dhcpd and bind9/named execution

**Comment by MMaiero** [comment]
@dwoodard1 Could you do some tests on your device?

**Comment by cdealti** [comment]
@dwoodard1 can you give it a try please? However, I do not like having to disable Apparmor

**Review by dwoodard1 — APPROVED** [review]

**Comment by dwoodard1** [comment]
The changes work for me.

**Pull request merged**
