### PR TITLE
Fixed centos installation.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by ctron** [comment]
@MMaiero Could you explain what changes you did?

**Comment by MMaiero** [comment]
As you can see from the diff, there were many bugs in the existing distribution, probably also caused by the restructuring made. I've tried to keep consistency in the interfaces configuration trying to match what did by @dwoodard1 for Ubuntu. Plus other minor improvements.
This PR will be closed in favour of one that @pierantoniomerlino will make and that will have my commits plus some other commits he made for tinyB, in order to have it working on the target system.

**Comment by ctron** [comment]
> This PR will be closed in favour of one that @pierantoniomerlino will make …

So I can ignore this one?

**Comment by pierantoniomerlino** [comment]
@ctron Yes. Please take a look at #2238

**Pull request closed without merging**
