### PR TITLE
Fix for dialog on Modem help text.

### PR DESCRIPTION
**Pull request by dwoodard1**
Fix for #242

### CODE REVIEW

**Comment by MMaiero** [comment]
@dwoodard1 I would do the same also for the wireless tab

**Comment by MMaiero** [comment]
@dwoodard1 However, I see that if you reduce the browser window width, the help text box disappears

**Comment by dwoodard1** [comment]
@MMaiero I will check the wireless tab, thought I had checked them all. Not sure what to do about the small screens. Where would the dialog go? I think this would be a bigger design change than should be covered in this PR.

**Comment by cdealti** [comment]
@MMaiero Shall we merge?

**Pull request merged**
