### PR TITLE
Restore Javadoc generation

### LINKED ISSUE #812: [Kura 2.1.0] Restore Javadoc generation
There was a first refactor by me where this worked:
https://github.com/eclipse/kura/commit/242e8b969767c82ed50517d8b74dee0bb715e65e

But the change was partially reverted in this merge:
https://github.com/eclipse/kura/commit/76054e125f318865f888b98253bbbe923768d58c

### PR DESCRIPTION
**Pull request by cdealti**
Fix #812:
* Have the build fail on Javadoc generation errors
* Added noextend custom tag to maven-javadoc-plugin
* Fixed tons of Javadoc problems

Signed-off-by: Cristiano De Alti <cristiano.dealti@eurotech.com>

### CODE REVIEW

**Comment by cdealti** [comment]
@dwoodard1 please review

**Comment by cdealti** [comment]
@ctron any idea why this fails?

```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9:aggregate (aggregate) on project kura: An error has occurred in JavaDocs report generation:
```

**Comment by ctron** [comment]
I looks a little bit like you somehow enforced external documentation links but did not provide all the references. I never really went that deep into JavaDoc.

**Comment by cdealti** [comment]
OK thanks. We will address this for 3.0.0. Just strange that it happens only for the Camel bundle.

**Pull request merged**
