### PR TITLE
for issue #2240

### PR DESCRIPTION
**Pull request by spnettec**
see [https://github.com/eclipse/kura/issues/2240](url)

### CODE REVIEW

**Comment by spnettec** [comment]
How to get rid of invalid Signed-off-by footers?

**Comment by MMaiero** [comment]
As reported in the document shared: https://www.eclipse.org/contribute/
you need to sign the Eclipse Contributor Agreement and sign your commits with the email associated with your eclipse account.

**Comment by spnettec** [comment]
The test needs to be cleaned otherwise the test will fail due to the interruption of the previous test.

**Comment by spnettec** [comment]
Ip-validation fail.Should I recreate a PR?

**Comment by MMaiero** [comment]
All your commits should be signed with the email you used to sign the ECA. Please rework them in order to fit Eclipse requirements.

Best regards,
Matteo

**Comment by spnettec** [comment]
Closed to create an other PR

**Pull request closed without merging**
