### PR TITLE
Added QA test for position service

### PR DESCRIPTION
**Pull request by pierantoniomerlino**
Signed-off-by: pierantoniomerlino <pierantonio.merlino@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@markoer Could you have a look at this?

**Comment by markoer** [comment]
DEN-POS-003 says 'Repeat step DEN-POS-003...' when it should likely be 'Repeat step DEN-POS-002...'. The rest seems OK.

**Comment by pierantoniomerlino** [comment]
No, it should be 001... I'll update the PR.

**Comment by MMaiero** [comment]
Great. Merging then

**Pull request merged**
