### PR TITLE
Update to 4.1.2 snapshot

### PR DESCRIPTION
**Pull request by MMaiero**

### CODE REVIEW

**Comment by nicolatimeus** [comment]
There are still references to 4.1.1 in the following files:

* `kura/distrib/pom.xml`
* `kura/tools/archetype/example/pom.xml`
* `kura/tools/archetype/pom.xml`

**Comment by MMaiero** [comment]
Thanks for catching that!

**Comment by nicolatimeus** [comment]
Is the change done in #2917 needed in this PR as well?

**Comment by MMaiero** [comment]
Correct. Done in a new commit.

**Comment by MMaiero** [comment]
@nicolatimeus Can this be merged?

**Review by nicolatimeus — APPROVED** [review]

**Pull request merged**
