### PR TITLE
Replaced Preconditions with Java 8 Styles

### LINKED ISSUE #959: Replace Preconditions references with Objects
To extract Preconditions to Utility bundle, Preconditions references in API must be replaced with Objects.

### PR DESCRIPTION
**Pull request by amitjoy**
1. Precondition references are replaced with Java 8
2. Asset and Driver Lister interface are now annotated with Functional
Interface
3. API and Wires Bundles' EE have been set to 1.8
4. getServiceReferences method in ServiceUtil is modified
5. Added missing preconditions to Wire Support

Fixes #959

### CODE REVIEW

**Comment by ctron** [comment]
But I think the build errors should be fixed before merging!

**Comment by amitjoy** [comment]
Yeah I saw it. I am on it.

**Comment by ctron** [comment]
Sorry. Looks good. I was  too curious ;-)

**Comment by amitjoy** [comment]
@ctron Done.

**Pull request merged**
