### PR TITLE
Add missing dependencies after the Kura Wires merge

### PR DESCRIPTION
**Pull request by ctron**
Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by amitjoy** [comment]
👍

**Comment by dwoodard1** [comment]
@ctron This only addresses the Oomph setup, correct? Do we need the same change for the *.launch files and the system distributions (kura/distrib/src/main/osgi)?

**Comment by ctron** [comment]
Correct. I don't know that. I never use them. Maybe Amit could make another PR for those.

**Comment by dwoodard1** [comment]
Ok, we will create another PR. Out of curiosity, how do you update Eclipse using Oomph? I understand the initial setup, but I am unsure about how to update when changes are made like in this PR.

**Comment by ctron** [comment]
Well the update comes with Git. Oomph only sets up git for you.

**Pull request merged**
