### PR TITLE
Added IntelliJ Git ignores.

### PR DESCRIPTION
**Pull request by hekonsek**
Clean version of #70. With proper branch and signed commits.

Signed-off-by: Henryk Konsek <hekonsek@gmail.com>

### CODE REVIEW

**Comment by kartben** [comment]
Would be nice to merge this PR, no?

**Comment by hekonsek** [comment]
Yeah, any chance to got it merged? :) Thanks!

**Comment by dwoodard1** [comment]
It would be great if you could post something on how you are working with Kura in IntelliJ. For example, how are you handling the target platform?

**Comment by hekonsek** [comment]
Many thanks! 

Actually I'm not handling target platform now. I'm just adding dependencies on required jars to the module I'm currently working with. I will let you guys know when I will work on some better practices for IntelliJ and Kura.

**Pull request merged**
