### PR TITLE
Attempt to fix spurious lifecycle messages on shutdown

### PR DESCRIPTION
**Pull request by nicolatimeus**
Signed-off-by: Nicola Timeus <nicola.timeus@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@salvatore-coppola @marcellorinaldo @mstankovic Can you please have a review of the code and perform some stress testing of this set of changes?

**Comment by MMaiero** [comment]
We have agreed on back porting the change to 5.0.0

**Comment by MMaiero** [comment]
@salvatore-coppola @marcellorinaldo @mstankovic Ok on merging this?

**Comment by salvatore-coppola** [comment]
I performed some test on rg 10-12 and everything went fine. From my point of view in can be merged.

**Comment by marcellorinaldo** [comment]
> @salvatore-coppola @marcellorinaldo @mstankovic Ok on merging this?

Still need to test it

**Review by marcellorinaldo — APPROVED** [review]
@MMaiero @nicolatimeus I have tested the behaviour before and after those changes. Everything seems fine, much less messages (only 2 vs. 28 of before) are published on stop.

**Comment by MMaiero** [comment]
Great news, thanks. @mstankovic any updates from you?

**Comment by mstankovic** [comment]
@MMaiero I have performed stress test and everything went fine.

**Pull request merged**
