### PR TITLE
Added Generic Servlet to stream any OSGi Event to SSE clients

### PR DESCRIPTION
**Pull request by amitjoy**
This feature allows streaming OSGi events and their associated properties to Server Sent Events (aka EventSource) clients. Consumers can make use of any Event Source supported language to build their own client application to receive OSGi event notifications. A simple javascript client can be written as follows:

```
var eventSource = new EventSource("http://<IP>:<PORT>/sse?topic=org/osgi/framework/*");
eventSource.onmessage = function(event) {
  var data = JSON.parse(event.data);
  console.log(data);
};
```

Kura Wires uses this feature to subscribe to Wire Component emit events to update the Composer Canvas UI in an asynchronous way.

This uses the following Jetty subproject and JS Module to support EventSource in IE:

[1] Binary: https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-servlets/9.3.9.v20160517
[2] Sources: http://search.maven.org/remotecontent?filepath=org/eclipse/jetty/jetty-servlets/9.3.9.v20160517/jetty-servlets-9.3.9.v20160517-sources.jar
[3] https://github.com/remy/polyfills/blob/master/EventSource.js

### CODE REVIEW

**Comment by MMaiero** [comment]
Did you have the chance to test this with IE?

**Comment by amitjoy** [comment]
I have tested the polyfill EventSource in IE and it works but didn't get a chance to test the complete Kura Wires with it. But it should work too. I checked the polyfill in Opera Mini as well and it works too.

**Comment by amitjoy** [comment]
As I cannot avail an IE browser quite a often, I have only tested this complete solution to stream OSGi events in Safari, Chrome and Opera in my Mac and it seems to be very lightweight solution.

**Comment by amitjoy** [comment]
Just finished testing this feature in few SSE incompatible Mobile Browsers (Opera Mini, Firefox for Android and Opera for Android). SSE in Kura Wires works in these browsers too.

**Comment by amitjoy** [comment]
Fixes #1000 and #1113

**Comment by cdealti** [comment]
@MMaiero shall we give this a try?

> [3] https://github.com/remy/polyfills/blob/master/EventSource.js

CQ needed (redistribution in source and binary form)

**Comment by MMaiero** [comment]
Closing, for now, as it is too far behind develop.
We will recover it, if needed

**Pull request closed without merging**
