### PR TITLE
feat: added support for container state in inventory API

### PR DESCRIPTION
**Pull request by GregoryIvo**
> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to inderstand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by GregoryIvo** [comment]
note for review.

I decided to not include the container state in the un-marshaler. 
1) When a container is un-marshalled, Kura will use the name to query locally for the container and populate its own fields
2) the mapping of the container state, to Kura bundle state is not symmetrical, so we cannot trust the un marshed state

**Comment by GregoryIvo** [comment]
Inventory Get Container Request:
image

Returned Container String:
```
eyJjb250YWluZXJzIjpbeyJuYW1lIjoiTWFuYWdlZENvbnRhaW5lcjEiLCJ2ZXJzaW9uIjoibmdpbng6bGF0ZXN0IiwidHlwZSI6IkRPQ0tFUiIsInN0YXRlIjoiYWN0aXZlIn0seyJuYW1lIjoibmdpbngiLCJ2ZXJzaW9uIjoibmdpbng6bGF0ZXN0IiwidHlwZSI6IkRPQ0tFUiIsInN0YXRlIjoidW5pbnN0YWxsZWQifSx7Im5hbWUiOiIxLXRlc3QiLCJ2ZXJzaW9uIjoibmdpbng6bGF0ZXN0IiwidHlwZSI6IkRPQ0tFUiIsInN0YXRlIjoidW5pbnN0YWxsZWQifV19
```

Converted String:
```
{"containers":[{"name":"ManagedContainer1","version":"nginx:latest","type":"DOCKER","state":"active"},{"name":"nginx","version":"nginx:latest","type":"DOCKER","state":"uninstalled"},{"name":"1-test","version":"nginx:latest","type":"DOCKER","state":"uninstalled"}]}
```

**Comment by GregoryIvo** [comment]
Inventory EXEC (Stop Container Request):
image


Base64 String:
```
eyJuYW1lIjoiTWFuYWdlZENvbnRhaW5lcjEiLCJ2ZXJzaW9uIjoibmdpbng6bGF0ZXN0IiwidHlwZSI6IkRPQ0tFUiIsInN0YXRlIjoiYWN0aXZlIn0=
```

Decoded String:
```
{"name":"ManagedContainer1","version":"nginx:latest","type":"DOCKER","state":"active"}
```

**Comment by GregoryIvo** [comment]
Reviewer Note:
These changes still work with the current version of kapua. (Start and stop still work!)

image

**Review by pierantoniomerlino — APPROVED** [review]

**Pull request merged**
