### PR TITLE
Kura Asset Model and Kura Wires

### PR DESCRIPTION
**Pull request by amitjoy**
This comprises all the necessary APIs and implementations for Kura Asset Model and Kura Wires. This doesn't include the changes in Web Bundle as it would be done in the forthcoming PR.

### CODE REVIEW

**Comment by LucaDazi** [comment]
CQ #12025 has been created for approval.

**Comment by amitjoy** [comment]
@LucaDazi @MMaiero @cdealti @ctron Could any one of you label this PR as Kura Wires? It would be easy to track.

**Comment by amitjoy** [comment]
@cdealti @LucaDazi Any update on this PR?

**Comment by cdealti** [comment]
It has been approved but the Quartz CQ is still pending waiting for the stripped-down source code package containing only the core and jobs modules.

**Comment by cdealti** [comment]
@amitjoy I've updated the Quartz CQ.
The plan is to wait for the Quartz CQ approval and merge this PR on develop before we rewrite the repository history.
Then we will create the release-2.1.0 branch from the commit just before this PR merge commit... hopefully.

**Comment by ctron** [comment]
That could take a few weeks!

**Comment by cdealti** [comment]
CQ for Quartz has been approved

**Comment by ctron** [comment]
That was quick!

**Pull request merged**
