### PR TITLE
Added modal to confirm reset

### LINKED ISSUE #2729: No Confrmation When Trying to Reset SSL Configurations
If user tries to reset certain configuration (e.g. in WireService) Kura always askas the user if he is sure that he wants to do that, but there is no pop-up window when user tries to reset SSL configuration - when Reset button is pressed, everything gets reset immediatelly. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Settings -> SSL Configuration/Server SSL Certificate/Device SSL Certificate
3. Enter something in any of the fields and then click Reset button
4. Observe the lack of pop-up confirmation window.

**Expected behavior**
When Reset button is pressed, a pop-up windows should show up in order for user to confirm the choice or not. 

**Screenshot (example of confirmation windows from Wire Service):**
Screenshot 2020-03-27 at 11 11 25

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2729

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
hey @MMaiero
I have checked this and if user changes service view (goes from Settings to e.g. CloudService), Kura asks the user if he wants to discard changes (which is OK), but if user clicks YES and then returns, this is the case:
Screenshot 2020-07-06 at 10 51 23


But: if user changes a tab in the SSL configuration, the changes are actually reverted.
Can you please check this?

**Comment by MMaiero** [comment]
Made an improvement on top of that. Please have a look.

**Comment by LeoNerdoG** [comment]
Hey,
I have checked this and not there is no prompt for discarding changes if user changes tabs (from SSL configuration to e.g. Device SSL certificate), but the changes are automatically discarded. Is this desired behaviour?

**Comment by MMaiero** [comment]
No, it is not desired. Let's open a new issue for that and let's try to finalise this one.

**Comment by MMaiero** [comment]
Closing in favour of #2978

**Pull request closed without merging**
