### PR TITLE
[Windows] Fix Windows build and add 32-bit support

### PR DESCRIPTION
**Pull request by malikm**
- Fixes Windows files after history rewrite
- Add x86/32-bit build
- Additional updates to build process

Signed-off-by: Martin Malik martin.malik@eurotech.com

### CODE REVIEW

**Comment by cdealti** [comment]
Didn't we agree on removing MinGW and NSIS [1]?

[1] https://github.com/eclipse/kura/issues/637

**Comment by malikm** [comment]
AFAIK this was about removing the binaries produced by those tools, but source code should be OK.
Am I wrong ?

**Comment by cdealti** [comment]
My understanding is that we want the native libraries built with Visual Studio and the Wix installer.
In this way the Windows installer can be downloaded from eclipse.org.

**Comment by malikm** [comment]
Or keep NSIS and MinGW without binary files and let them build locally by users until a CQ for those is done ?
@ctron Is a CQ for NSIS and MinGW not feasible ? If Windows tools are approved, why something like NSIS and MinGW would not be possible ?

**Comment by cdealti** [comment]
I'll leave the final word to @ctron. However we have time to file **full** CQs for NSIS and MinGW if you insist using those.

**Comment by ctron** [comment]
So I we would go the way @malikm proposes we would still need a CQ, but a "works-with" would suffice IMHO. So Kura can be used without that, even on windows. And people could build it themselves. I don't even think we do need a CQ for MinGW, since there should be nothing MinGW specific those parts.

But then you would be able to distribute those binaries (installer, EXE) from Eclipse download servers.

Going with a complete CQ would allow exactly that. But it would take more time and has the probability to fail completely.

The Eclipse Foundation sometimes grants "exempt" pre-requisite CQs. Those are not always formalized, which is a point for improvement. Nobody is perfect :wink: The idea behind that is simply some sort of risk management. So for example Java can be used without a CQ, but also it cannot be distributed. Looking at Visual Studio, and here comes my personal opinion, nothing official, it is probably the fact that Microsoft has a clean IP record. So the chance to get sues for using the Visual Studio compiler is pretty unlikely. However the situation with MinGW may be different. Must not, but could be. Now when you want to bet on it, which horse would you pick?

**Comment by ctron** [comment]
To sum it up. If you want to distribute it, you need a full CQ before merging. If you don't want to distribute the binaries, a works-with request would suffice.

If you go with Visual Studio and WiX you simple need to add this to the build and test CQ and are done as long as you don't use any WiX addons which actually add external content to the final MSI (like DLLs or images).

**Comment by malikm** [comment]
Due to the disadvantages of using WiX and MSVC mentioned in #637, I'd prefer to stay with NSIS and MinGW.
If everybody agrees, can we start the CQ process ?

**Comment by cdealti** [comment]
As @ctron already mentioned it's unlikely MinGW would be approved [1], [2].

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=8773
[2] https://wiki.eclipse.org/Tools_PMC_Meeting_2014-11-12

**Comment by malikm** [comment]
My understanding wasn't "unlikely", but less strict. If it's really "unlikely" we might go ahead without pre-compiled and shipped binaries. Later compile using MSVC, but need to add the MSVC redistributable package are a pre-requisite.
Do we need to distribute the whole Windows package ? If not, is there anything else preventing accepting this PR ?

**Comment by cdealti** [comment]
Closing as no decision has been made for what compiler and installer to use.

**Pull request closed without merging**
