### PR TITLE
Modified emulator launch.

### PR DESCRIPTION
**Pull request by MMaiero**
Removed *registry bundles that miss some dependencies. Enabled commons.exec.
Enabled one example publisher.

Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@markoer Could you give it a check, please?

**Comment by markoer** [comment]
The new bundles get deployed and are activated.

org.eclipse.kura.camel.xml.XmlRouterComponent has issues with Java 1.8, although it's run with Java 1.8.

Web bundle is active, but GUI doesn't start.

**Comment by MMaiero** [comment]
What exception you get?

**Comment by markoer** [comment]
I'm happy to report a false alarm. I performed a new Eclipse installation and code checkout and the emulator runs without issues, now. Example publisher works. You may merge the PR, if you ask me.

**Review by markoer — APPROVED** [review]

**Pull request merged**
