### PR TITLE
Fix concurrency issue in command service

### PR DESCRIPTION
**Pull request by ctron**
The command service was implemented in a way that it did execute all
command written out to a single shell script. This can cause the issue
that two requests issued at the same time would fail.

This change does write out seperate script files using the
Files.createTempFile method. It also does not fork "chmod" and
"dos2unix" since those operations can be performed inside Java which
saves two additional process forks.

Also is the "cd" statement not necessary when the ProcessBuilder
is instructed to change the directory first. For this the process
started can now accept an optional working directory.

This change also includes a unit test for the command service.

Signed-off-by: Jens Reimann jreimann@redhat.com

### CODE REVIEW

**Comment by hekonsek** [comment]
Hi Jens, 

I'd like to merge the PR, but you should downgrade Java to 1.6 before I do that. We should stick for Java 1.6 for a while. Can you do this?

Thanks!

**Comment by ctron** [comment]
In theory: yes

But rather than rewriting those "try-with-resources" sections and bloating the source code again, I would suggest we make a decision on #330.

Kura itself needs Java 7 already. And I don't see any advantage in sticking with Java 6 for the source code. But maybe I just don't see it.

If we come to conclusion that Java 6 is still a requirement I will re-work the patch for Java 6.

**Comment by dwoodard1** [comment]
@ctron Why does Kura need Java 7?

**Comment by dwoodard1** [comment]
@ctron Apologies, I just saw the note in #330 about Apache Camel, I will respond there.

**Comment by hekonsek** [comment]
Jens, I propose to downgrade this pull request to use Java 6 for a while. When are are done with Java 7 upgrade, then we could create an another PR to make this code more Java 7 friendly.

Is that OK?

**Comment by ctron** [comment]
Well the changes make use of the Java 7 NIO2 methods like for example `Files.setPosixFilePermissions`.

I would like to spend a bit more time on making a decision/plan about Java 7. I think this PR can wait little while longer. If Java 6 is a hard requirement, then we can still rework it. But of possible I would like to save the time.

**Comment by hekonsek** [comment]
I guess that @cdealti is concerned (#330) about customers using Java 6 in production. I would say that we should migrate this PR to 1.6 then, if you ask me :) .

**Comment by ctron** [comment]
Superseded by #868

**Pull request closed without merging**
