### PR TITLE
Installer script fixes

### LINKED ISSUE #990: Script error in installer
Running a recently built 3.0.0 version of the the Kura installer generates the following error:

```
[root@localhost ~]# ./kura_3.0.0-SNAPSHOT_fedorapi_installer.sh 
./kura_3.0.0-SNAPSHOT_fedorapi_installer.sh: line 123: [: too many arguments
```

### PR DESCRIPTION
**Pull request by nicolatimeus**
Improved robustness of java version check
Improved glob expansion in backup file list
Fixed issues when running sysctl -p to disable ipv6 with set -e enabled

Closes #990 

Signed-off-by: nicolatimeus <nicola.timeus@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@ctron Could you have a look at this?

**Comment by ctron** [comment]
I can test this for fedora25.

**Comment by MMaiero** [comment]
Thanks

**Comment by ctron** [comment]
Running on a plain Fedora 25 installation this causes:

```
[jreimann@jreimann-pi ~]$ ./kura_3.0.0-SNAPSHOT_fedora25_installer.sh 
./kura_3.0.0-SNAPSHOT_fedora25_installer.sh: line 34: which: command not found
java not found, please install it
```

**Comment by ctron** [comment]
Looks good on Fedora 25 otherwise:

```
[jreimann@jreimann-pi ~]$ sudo ./kura_3.0.0-SNAPSHOT_fedora25_installer.sh 

Installing Kura...
Creating backup...

Extracting Kura files

Removing backup...

Finished.  Kura has been installed to /opt/eclipse/kura and will start automatically after a reboot
```

**Review by ctron — APPROVED** [review]

**Comment by nicolatimeus** [comment]
Ok thanks, can you please try to reboot and check if Kura starts correcly?

**Comment by ctron** [comment]
No it doesn't. The box becomes unreachable after rebooting.

**Comment by ctron** [comment]
Ok .. it did came up. But after quite a while. But I guess this isn't an issue created by the installer change.

**Comment by MMaiero** [comment]
So all agree on merging?

**Pull request merged**
