### PR TITLE
Changed login modal title to note logins as errors.

### LINKED ISSUE #2837: Warning/Error Dialogue Box Problem When Logging in With Wrong Credentials
If user enters invalid login credentials Kura reports a "Warning" but should really be an "Error", since the text is on red background. 

**Testflow:**
1. Open https://[kura-ip]
2. Enter invalid login credentials 
3. Press Login and observe the warning/error.

**Expected behavior**
Dialogue box that appears should be renamed to "Error" or the background of the message should be changed to yellow. 

**Screenshot:**
Screenshot 2020-05-05 at 13 55 26

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

### PR DESCRIPTION
**Pull request by MMaiero**
Added a reset button to clear the form.

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2837

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have tested this PR and found two interesting issues 😄 
1. 
If you enter invalid usernam and/or password into the username/password fields and simultaneously press Login button with you mouse and ESC key on you keyboard, after a while the Error message will not appear if you jsut click Login button when credentials are wrong. 



2. if you click on username/password field (so focus is on them) and press ESC key on your keyboard, the Login prompt goes away. 



Can you please check?

**Comment by MMaiero** [comment]
The last one I believe is already documented as an issue.
For the first one, I don't believe that is a frequent case that can happen.

**Comment by MMaiero** [comment]
Can this be merged?

**Comment by LeoNerdoG** [comment]
As you stated above, second one is already reported, first one is not a blocker so i think this can be merged.

**Pull request merged**
