### PR TITLE
Fix private members

### PR DESCRIPTION
**Pull request by ctron**
Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by cdealti** [comment]
@dwoodard1 can we agree that this kind of changes do not require a PR?

**Comment by MMaiero** [comment]
If the changes does not modify the code behavior, I agree.

**Comment by dwoodard1** [comment]
I agree. However, if we are modifying code for this purpose, shouldn't we also clean up the other style issues. For example, the use of m_* for member names? But, that shouldn't need a PR either. Since it is not modifying code behavior.

**Comment by cdealti** [comment]
I agree.

**Comment by ctron** [comment]
Can we do this outside of a PR as Cristiano suggested?

**Comment by dwoodard1** [comment]
Yes

**Pull request merged**
