### PR TITLE
fix(linux.usb): memory leak on non-usb udev events

### PR DESCRIPTION
**Pull request by marcellorinaldo**
This PR calls `udev_device_unref` at the end of the loop, not only inside the `if` positive branch. It also adds `udev_unref` as per [udev example](https://github.com/robertalks/udev-examples/tree/master). Without these fixes a memory leak occurs on udev events that are not caught by the `dev_parent`.

**Related Issue:** N/A.

**Description of the solution adopted:** N/A.

**Screenshots:** N/A.

**Manual Tests**: N/A.

**Any side note on the changes made:** N/A.

### CODE REVIEW

**Comment by marcellorinaldo** [comment]
Results on a long running test. Test consists of having a systemd unit using the `mmc` tool every 1ms producing a series of udev events.

image

**Comment by MMaiero** [comment]
Is this an issue affecting also Kura 4?

**Comment by marcellorinaldo** [comment]
> Is this an issue affecting also Kura 4?

Yes

**Comment by MMaiero** [comment]
Can we make a back port for that version? (As it is still supported)

**Review by pierantoniomerlino — APPROVED** [review]

**Pull request merged**
