### PR TITLE
Disabled systemd-timedated.service and isc-dhcp-server6.service

### PR DESCRIPTION
**Pull request by salvatore-coppola**

### CODE REVIEW

**Comment by nicolatimeus** [comment]
@mattdibi are some of these changes needed also for Jetson nano?

**Comment by mattdibi** [comment]
@nicolatimeus Just checked with @salvatore-coppola and shouldn't be needed. `systemd-timedated` is already disabled. `isc-dhcp-server6` didn't cause any problem from what I remember. It could also be missing on the Nano from what I can remember.

For me it could be ok as it is right now.

**Comment by nicolatimeus** [comment]
On rpi Rasbian disabing `systemd-timedated` seems to have no effect, what was the reason for disabing it?

```
root@raspberrypi:~# systemctl status systemd-timedated
● systemd-timedated.service - Time & Date Service
     Loaded: loaded (/lib/systemd/system/systemd-timedated.service; static)
     Active: inactive (dead)
       Docs: man:systemd-timedated.service(8)
             man:localtime(5)
             man:org.freedesktop.timedate1(5)
root@raspberrypi:~# systemctl disable systemd-timedated
root@raspberrypi:~# systemctl status systemd-timedated
● systemd-timedated.service - Time & Date Service
     Loaded: loaded (/lib/systemd/system/systemd-timedated.service; static)
     Active: inactive (dead)
       Docs: man:systemd-timedated.service(8)
             man:localtime(5)
             man:org.freedesktop.timedate1(5)
root@raspberrypi:~# systemctl stop systemd-timedated
root@raspberrypi:~# systemctl status systemd-timedated
● systemd-timedated.service - Time & Date Service
     Loaded: loaded (/lib/systemd/system/systemd-timedated.service; static)
     Active: inactive (dead)
       Docs: man:systemd-timedated.service(8)
             man:localtime(5)
             man:org.freedesktop.timedate1(5)
root@raspberrypi:~# timedatectl 
               Local time: Thu 2022-03-31 10:06:21 BST
           Universal time: Thu 2022-03-31 09:06:21 UTC
                 RTC time: n/a
                Time zone: Europe/London (BST, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
root@raspberrypi:~# systemctl status systemd-timedated
● systemd-timedated.service - Time & Date Service
     Loaded: loaded (/lib/systemd/system/systemd-timedated.service; static)
     Active: active (running) since Thu 2022-03-31 10:06:21 BST; 6s ago
       Docs: man:systemd-timedated.service(8)
             man:localtime(5)
             man:org.freedesktop.timedate1(5)
   Main PID: 807 (systemd-timedat)
      Tasks: 1 (limit: 1597)
        CPU: 201ms
     CGroup: /system.slice/systemd-timedated.service
             └─807 /lib/systemd/systemd-timedated

Mar 31 10:06:21 raspberrypi systemd[1]: Starting Time & Date Service...
Mar 31 10:06:21 raspberrypi systemd[1]: Started Time & Date Service.
root@raspberrypi:~#
```

**Comment by mattdibi** [comment]
@nicolatimeus @salvatore-coppola As you pointed out disabling `systemd-timedated` doesn't have any effect. The reason for it being disabled in the Jetson Nano might have been excess of zeal (I started disabling all time-related services because I was having conflicts with Kura).

We can leave it as-is right now (as it doesn't have any effect) or we can remove the disable from all the installers.

**Comment by salvatore-coppola** [comment]
I'll close the PR.

**Comment by mattdibi** [comment]
@nicolatimeus Should I open a PR for removing the line from the Jetson Nano installer?

**Review by nicolatimeus — APPROVED** [review]

**Pull request merged**
