### PR TITLE
fix(net.configuration): Added missing ADs in getDefinition method

### PR DESCRIPTION
**Pull request by pierantoniomerlino**
> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

This PR adds some missing ADs in the `getDefinition` method of the `NetworkConfigurationServiceCommon`.

**Related Issue:** This PR fixes/closes N/A

**Description of the solution adopted:** The following ADs are added:

- net.interface.<interface>.config.pdpType
- net.interface.<interface>.config.activeFilter
- net.interface.<interface>.config.resetTimeout
- net.interface.<interface>.config.lcpEchoFailure
- net.interface.<interface>.config.pppNum
- net.interface.<interface>.config.password
- net.interface.<interface>.config.authType
- net.interface.<interface>.config.lcpEchoInterval
- net.interface.<interface>.config.idle
- net.interface.<interface>.config.diversityEnabled
- net.interface.<interface>.config.persist
- net.interface.<interface>.config.enabled
- net.interface.<interface>.config.apn
- net.interface.<interface>.config.dialString
- net.interface.<interface>.config.gpsEnabled
- net.interface.<interface>.config.maxFail
- net.interface.<interface>.config.wifi.infra.bgscan
- net.interface.<interface>.config.wifi.infra.pingAccessPoint
- net.interface.<interface>.config.wifi.infra.ignoreSSID
- net.interface.<interface>.config.wifi.master.ignoreSSID
- net.interface.<interface>.config.ip4.status

### CODE REVIEW

**Comment by nicolatimeus** [comment]
I think I have found the following inconsistencies between Kura documentation at https://eclipse.github.io/kura/docs-develop/gateway-configuration/network-configuration and the code in this PR:

* `net.interface.<interface>.type` is documented but no AD is returned
* `net.interface.<interface>.config.ip4.dnsServers` is documented but no AD is returned. Is it returned as `net.interface.<interface>.config.dnsServers` instead?
* `net.interface.<interface>.config.wifi.master.driver` is documented but no AD is returned.
* `net.interface.<interface>.config.wifi.master.mode` is documented but no AD is returned.
* `net.interface.<interface>.config.wifi.infra.driver` is documented but no AD is returned.
* `net.interface.<interface>.config.wifi.infra.mode` is documented but no AD is returned.
* An AD for `net.interface.<interface>.config.wifi.master.broadcast` is returned but not documented
* An AD for `net.interface.<interface>.config.wifi.master.hardwareMode` is returned but not documented
* An AD for `net.interface.<interface>.config.wifi.infra.hardwareMode` is returned but not documented
* An AD for `net.interface.<interface>.config.wifi.infra.radioMode` is returned but not documented
* An AD for `net.interface.<interface>.config.dnsServers` is returned but not documented
* An AD for `net.interface.<interface>.config.winsServers` is returned but not documented
* An AD for `net.interface.<interface>.config.driver` is returned but not documented
* An AD for `net.interface.<interface>.config.autoconnect` is returned but not documented
* An AD for `net.interface.<interface>.config.mtu` is returned but not documented

Not all of them are necessarily issues but we should review them and fix the code and/or the docs if needed.

**Comment by pierantoniomerlino** [comment]
I tried to review the propertie definition as follows:

- net.interface.\<interface\>.type is documented but no AD is returned: **added to code**
- net.interface.\<interface\>.config.ip4.dnsServers is documented but no AD is returned. Is it returned as net.interface.\<interface\>.config.dnsServers instead?: **the correct name is `ip4.dnsServers`; fixed in the code**
- net.interface.\<interface\>.config.wifi.master.driver is documented but no AD is returned.: **to be removed from docs**
- net.interface.\<interface\>.config.wifi.master.mode is documented but no AD is returned.: **to be removed from docs**
- net.interface.\<interface\>.config.wifi.infra.driver is documented but no AD is returned.: **to be removed from docs**
- net.interface.\<interface\>.config.wifi.infra.mode is documented but no AD is returned.: **to be removed from docs**
- An AD for net.interface.\<interface\>.config.wifi.master.broadcast is returned but not documented: **to be added to the docs**
- An AD for net.interface.\<interface\>.config.wifi.master.hardwareMode is returned but not documented: **removed from code**
- An AD for net.interface.\<interface\>.config.wifi.infra.hardwareMode is returned but not documented: **removed from code**
- An AD for net.interface.\<interface\>.config.wifi.infra.radioMode is returned but not documented: **to be added to the docs**
- An AD for net.interface.\<interface\>.config.dnsServers is returned but not documented: **replaced by `ip4.dnsServers'**
- An AD for net.interface.\<interface\>.config.winsServers is returned but not documented: **replaced by `ip4.dnsServers'; to be added to the docs**
- An AD for net.interface.\<interface\>.config.driver is returned but not documented: **removed from code**
- An AD for net.interface.\<interface\>.config.autoconnect is returned but not documented: **to be added to the docs**
- An AD for net.interface.\<interface\>.config.mtu is returned but not documented: **to be added to the docs**

If it's ok, I'll open a task for updating the documentation.

**Comment by nicolatimeus** [comment]
Are we removing properties from the docs because the docs were not correct or because the properties have actually been removed from the code at some point?

**Comment by pierantoniomerlino** [comment]
@nicolatimeus I'll remove the properties from the docs because actually they are not used in the code, nor the AD is returned. In particular, both driver and mode are read-only.

**Review by nicolatimeus — APPROVED** [review]

**Pull request merged**
