### PR TITLE
Updated snapshot 0 with latest changes to kura codebase for cloud con…

### PR DESCRIPTION
**Pull request by MMaiero**
…nections.

This will prevent an empty list in cloud connections when restoring snapshot 0.

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@markoer Any thoughts? Can this be merged?
Thanks

**Review by markoer — CHANGES_REQUESTED** [review]
I guess you'll have to merge with http service changes. It's not active and https doesn't work.

**Comment by MMaiero** [comment]
Yes, this branch was developed before the https merging. In theory, since there are no conflicts the merge will be done automatically closing the pull request. 
In any case, I can rebase the branch, if needed, but the issue should be visible and proven to be fixed even without the https part.

**Review by markoer — APPROVED** [review]
True, merge should go through OK.

**Pull request merged**
