### PR TITLE
Initial support for building a version for PC Engines APU / Debian 8

### PR DESCRIPTION
**Pull request by unverbraucht**
(Re-submit of PR 371 against a clean fork)

Dear Kura team,

I have added initial support for the embedded x86_64 APU platform from PC Engines running Debian. For now there's no reason why the resulting DEB shouldn't run on any x86_64 Debian system since I haven't added the GPIOs yet. This is a quick "port" in the sense that's its a mixture between the Intel Edison and the Raspbian profiles. I'll flesh it out if I find the time, right now it's running nicely and it's not a primary target for us.

Signed-off-by: Kevin Read me@kevin-read.com

### CODE REVIEW

**Comment by ctron** [comment]
Very cool. Thanks.

Could you amend the PR with a "Signed-off-by" header. It is required for the Eclipse CLA check. Thanks

**Comment by unverbraucht** [comment]
@ctron done :)

**Comment by ctron** [comment]
Thanks .. IP validation passed now!

**Comment by ctron** [comment]
I was just browsing through the files. I do think you should update the copyright headers. I you did copy and customize them, then add "Eurotech and others" and put yourself in the list of contributors.

**Comment by cdealti** [comment]
@unverbraucht due to the need of rewriting the history please update the PR ASAP as requested by @ctron. Otherwise you will have troubles having it merged after the history rewrite.
This will happen by the end of the week.

**Comment by ctron** [comment]
+1 from me

**Comment by unverbraucht** [comment]
@ctron @cdealti sorry for the delay, updated the headers of those files I changed. See you soon at EclipseCon :)

**Comment by cdealti** [comment]
+1. Thanks!

**Pull request merged**
