### PR TITLE
Fixed Invalid returned GPS Position and event firing missing.

### PR DESCRIPTION
**Pull request by salvatore-coppola**
Now GpsdPositionProvider return 0 in every field if no data are available.
Now GpsdPositionProvider fire the onLockStatusChanged correctly.

### CODE REVIEW

**Comment by nicolatimeus** [comment]
Zero is now shown instead of NaN before getting the first lock, I got a PositionLockedEvent on fix but I'm not getting any event if I disconnect the GPS antenna, the old position is still reported and no event is fired.

**Comment by salvatore-coppola** [comment]
I have tested again and i got the event, the antenna takes a while to lost the fix, can you do another test waiting more and monitoring when gpsd actually loose the fix with `gpsd -w` ?

**Review by nicolatimeus — APPROVED** [review]

**Comment by nicolatimeus** [comment]
This change restores the PositionLocked/LostEvents, the reported behavior is probably due to https://lists.gnu.org/archive/html/gpsd-dev/2017-09/msg00027.html, we might want to address that in a follow-up PR

**Comment by salvatore-coppola** [comment]
@MMaiero why the project for this pr is Kura 5.2.0 ?

**Comment by MMaiero** [comment]
Because it is merged in develop that will be 5.2.0. Once merged, the corresponding back port will be merged in 5.1.0 and that PR will be associated to the 5.1.0 project

**Pull request merged**
