### PR TITLE
remove erase and graphics rendition ANSI sequences

### PR DESCRIPTION
**Pull request by Erwan-S**
cf. https://github.com/eclipse/kura/issues/372

### CODE REVIEW

**Comment by dwoodard1** [comment]
Hello, thanks for the contribution. Please note, before we can review/consider the PR, you must sign the Eclipse CLA and also sign your commit. I would recommend you read the [contributing guidelines](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md) .

**Comment by Erwan-S** [comment]
It's done.

**Comment by ctron** [comment]
I don't fully understand the change TBH. But wouldn't it be simpler to set the TERM variable to something which doesn't use ANSI?

**Comment by Erwan-S** [comment]
@ctron : I, first, tried your solution and it didn't work. Furthermore, why adding a system configuration dependency ?

**Comment by ctron** [comment]
What kind of dependency do you mean? You can set environment variables when starting an application.

**Comment by Erwan-S** [comment]
Do you think that is better to change kura launch script than remove ansi character in gatttool response handler ? 

Anyhow, as I previously said, xterm solution doesn't work. When it creates response, gatttool doesn't consider xterm value (You can see that in interactive.c from gatttool source code).

**Comment by cdealti** [comment]
This PR has been screwed up by the Git history rewrite and needs to be resubmitted.

**Pull request closed without merging**
