### PR TITLE
#603: remove dependency on JSON 20090211

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by amitjoy** [comment]
I believe the `Bundle-Vendor` manifest header must be `Eclipse Foundation`, instead of `Eclipse Kura`

**Comment by ctron** [comment]
I can be either "Eclipse.org" or the full project name, You can have a look at the Eclipse software installation dialog on the tab "Plugins".

**Comment by ctron** [comment]
At least the Bundle Manifest has been updated, that should be reflected in a version uptick.

**Comment by amitjoy** [comment]
@ctron The `Provider` in the plugins sections actually shows it in different way and I agree with it. It is actually taken from the `feature.xml`. It would be nice to provide the real name of the vendor of the product. My personal opinion would be to go with `Eclipse Foundation` instead of `Eclipse.org` or `Eclipse Kura` as this doesn't logically belong to the `Bundle-Vendor`

**Comment by amitjoy** [comment]
Apart from it, I agree with @MMaiero as the Bundle version is also a part of semantic versioning scheme and if there is no functional change in the code, I believe we should not uptick the versions.

**Comment by ctron** [comment]
@amitjoy Why not follow the way other Eclipse projects do it? Why create a special way?

The problem is with the current build system then in this case changes will not get pulled in into the next build.

**Comment by MMaiero** [comment]
@ctron Could you explain me what you mean with "The problem is with the current build system then in this case changes will not get pulled in into the next build."?

**Comment by amitjoy** [comment]
@ctron That was just my opinion. If everyone agrees with `Eclipse.org`, I am also okay with it.

**Comment by ctron** [comment]
I just looked into the Eclipse guide for versions [1]

> For example, a bug has been fixed in the code, the plug-in manifest has changed, documentation has changed, compiler settings have changed.

I think we touched two of these points for this change.

[1] https://wiki.eclipse.org/Version_Numbering#When_to_change_the_service_segment

**Comment by ctron** [comment]
@amitjoy I don't say there is anything wrong with your opinion. But I also think that this an Eclipse project and it should follow the path other Eclipse projects follow for years. Putting in `Eclipse Foundation` does not add any value to the project IMHO, so I don't see the necessity for a special way.

**Comment by amitjoy** [comment]
@ctron Then we would go for it. I would suggest you to make a single commit with all the `Bundle-Vendor` changes in all the existing bundles. It would be nice to do it this way instead of doing it in different commits.

**Comment by ctron** [comment]
I would let GitHub to the job and issue "Squash and merge" for this PR.

**Comment by MMaiero** [comment]
For what I know, till now we used [this](https://www.osgi.org/wp-content/uploads/SemanticVersioning.pdf) as reference for semantic versioning as reported also [here](https://github.com/eclipse/kura/issues/226). 
If we want to change to [this](https://wiki.eclipse.org/Version_Numbering#When_to_change_the_service_segment) we need to be fully adherent and not using only parts.

However, I don't see a big problem if we continue to follow the approach used till now: the changes to bundle manifests will be in the code base and will go into production when the bundle code will be updated. It will take few Kura versions, but I don't think that people will complain if the bundle-vendor is not updated...

**Comment by ctron** [comment]
I don't really see how this conflicts with the upticking of the micro-version:

> A difference in the micro part does not signal any backward compatibility issues. The micro 
number is used to fix bugs that do not affect either consumers or providers of the API.

So something in the build got fixed (dependency + manifest). The project's source code advanced and no longer matches the build tag.

I will contact EMO and ask their interpretation on [1]. If there is a need to change then bundle vendor, then we should do that. If not we can wait another version or two.

[1] https://www.eclipse.org/legal/guidetolegaldoc2.php

**Comment by cdealti** [comment]
@ctron the point here is that you don't need to change the versions ``kura/distrib/config/kura.build.properties`` **right now** only due to this change. The next Kura release will not have new bundle versions unless in the meantime there is a real bugfix.

**Comment by ctron** [comment]
@cdealti I understand that. That is why I did ask EMO of the Bundle-Vendor should be updated or not. If it should be, then that would be a bug fix. Otherwise I can downtick the version in the properties file.

**Comment by ctron** [comment]
Beside that, the POM files of this version have to be released with the Nexus repository. Since they do contain the dependency and trigger a wrapper bundle on Karaf:

```
Feature contains followed bundles:
  mvn:org.eclipse.kura/org.eclipse.kura.linux.bluetooth/1.0.6-SNAPSHOT start-level=80
  mvn:org.eclipse.kura/org.eclipse.kura.linux.clock/1.0.7-SNAPSHOT start-level=80
  wrap:mvn:org.json/json/20090211 start-level=80
```

**Comment by ctron** [comment]
So I did get back a pointer from EMO [1]. It clearly states:
> Bundle manifests contains a "Bundle-Vendor" entry set to "Eclipse &lt;project name&gt;"

So we are required to set the field to "Eclipse Kura". Not "Eclipse Foundation", "Eclipse.org" or anything else.

Since there where no objections to other parts of this PR, I would to go on and merge this.

[1] https://wiki.eclipse.org/Development_Resources/HOWTO/Release_Reviews#Checklist

**Pull request merged**
