### PR TITLE
build: create kura dev container

### PR DESCRIPTION
**Pull request by GregoryIvo**
dev container environment with java 8 and maven pre-installed.

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by GregoryIvo** [comment]
with this change, we are able to launch a dev-container that is ready to build kura on the Cloud!!! ☁️ 


Configured with java 8 and Maven.

image

**Comment by salvatore-coppola** [comment]
I got this error during the build:

```
#3 [internal] load metadata for docker.io/library/alpine:latest
#3 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
#3 CANCELED
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "${BASE_IMAGE_KURA}": invalid reference format: repository name must be lowercase
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17:12 min
[INFO] Finished at: 2023-02-23T11:49:08+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "can" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project distrib: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by GregoryIvo** [comment]
> I got this error during the build:
> 
> ```
> #3 [internal] load metadata for docker.io/library/alpine:latest
> #3 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
> #3 CANCELED
> failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "${BASE_IMAGE_KURA}": invalid reference format: repository name must be lowercase
> [ERROR] Command execution failed.
> org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
>     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
>     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
>     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
>     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
>     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  17:12 min
> [INFO] Finished at: 2023-02-23T11:49:08+01:00
> [INFO] ------------------------------------------------------------------------
> [WARNING] The requested profile "can" could not be activated because it does not exist.
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project distrib: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> ```

hi @salvatore-coppola.

That error you have there should be fixed in PR #4400.

This PR just modifies the Codespaces environment when you create a new one here: 
image

**Comment by salvatore-coppola** [comment]
> > I got this error during the build:
> > ```
> > #3 [internal] load metadata for docker.io/library/alpine:latest
> > #3 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
> > #3 CANCELED
> > failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "${BASE_IMAGE_KURA}": invalid reference format: repository name must be lowercase
> > [ERROR] Command execution failed.
> > org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
> >     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
> >     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
> >     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
> >     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
> >     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
> >     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
> >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
> >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
> >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
> >     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
> >     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
> >     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
> >     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
> >     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
> >     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
> >     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
> >     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
> >     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
> >     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
> >     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
> >     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
> >     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
> >     at java.lang.reflect.Method.invoke (Method.java:498)
> >     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
> >     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
> >     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
> >     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> > [INFO] ------------------------------------------------------------------------
> > [INFO] BUILD FAILURE
> > [INFO] ------------------------------------------------------------------------
> > [INFO] Total time:  17:12 min
> > [INFO] Finished at: 2023-02-23T11:49:08+01:00
> > [INFO] ------------------------------------------------------------------------
> > [WARNING] The requested profile "can" could not be activated because it does not exist.
> > [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project distrib: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> > [ERROR]
> > [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> > [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> > [ERROR]
> > [ERROR] For more information about the errors and possible solutions, please read the following articles:
> > [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> > ```
> 
> hi @salvatore-coppola.
> 
> That error you have there should be fixed in PR #4400.
> 
> This PR just modifies the Codespaces environment when you create a new one here: image

ok, we will merge after  #4400

**Comment by mattdibi** [comment]
Will look into it. This gets me excited! 🔝

**Comment by mattdibi** [comment]
So... here's my thoughts.

I like the direction where this is going (i.e. lowering the barrier of entry for new contributors) but I feel like, at its current state, it might be incomplete.

Let me explain.

Github dev containers are designed to work with [Github Codespaces](https://docs.github.com/en/codespaces/overview) to provide a complete development environment in the browser using a VSCode in-browser instance. With this PR a new contributor would be able to make small changes and build Kura within the environment... but _without any code completion, references, diagnostics..._.

This isn't an easy task to solve: to be able to craft a codespace providing project-wise autocompletion we need to be able to correctly configure VSCode.

To configure VSCode to provide autocompletion for Kura we need:

- [Language Support for Java by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java): which provides [JDTLS](https://github.com/eclipse/eclipse.jdt.ls)
- [Debugger for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug)
- [Java Test Runner](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test)
- [Eclipse PDE support for VS Code](https://github.com/testforstephen/vscode-pde) which needs [to be configured correctly](https://github.com/testforstephen/vscode-pde#auto-import-eclipse-pde-projects).

Up until recently we had trouble in setting this system up since the JDTLS version shipped with VSCode requires Java17 to run IIRC... but thanks to #4206 we should be able to overcome that issue.

Furthermore, in our previous attempts, we didn't really figure out how to correctly configure [vscode-pde](https://github.com/testforstephen/vscode-pde) for Kura.

If we are able to overcome these issues we would be able to provide a one-click deploy dev environment for new contributors, effectively removing any barrier for entry to Kura. Unfortunately I wasn't able to go further than this in my exploration but this could be a great first issue for newcomers to the project and we could also ask for help from the community.

As for this PR: as I already said, this can help newcomers and, for me, could be merged as-is, but I feel like we should dig a little bit more into this to express the full potential of the underlying technologies.

<sub><sup>P.S. sorry for my usual wall of text</sup></sub>

**Comment by GregoryIvo** [comment]
image
Kura in a dev container!

**Pull request closed without merging**
