### PR TITLE
Modified Wire Envelope schema

### PR DESCRIPTION
**Pull request by amitjoy**
1. Modified `Wire Field` representations
2. Modified Emit and Write operations in `Asset` to comply with new schema

In Progress for `Cloud Publisher` and `Cloud Subscriber` changes. There will be new commits for further changes.

Made the PR for quick reviews.

In progress to solve #1041

### CODE REVIEW

**Comment by amitjoy** [comment]
`Cloud Subscriber` changes added

**Comment by amitjoy** [comment]
`Cloud Publisher` changes added

**Comment by amitjoy** [comment]
@MMaiero @cdealti Could you have a look at it? 

According to our previous discussion, every Wire Field will now have `.v` and `.e` suffix based on the Severity Level. All the collected Wire Records are now published all at once.

**Comment by cdealti** [comment]
Superseded by #1081. Closing.

**Pull request closed without merging**
