### PR TITLE
fix(web2): Added missing wifi password content check.

### PR DESCRIPTION
**Pull request by salvatore-coppola**
Now empty password is considered a placeholder.

### CODE REVIEW

**Review by mattdibi — CHANGES_REQUESTED** [review]
@salvatore-coppola ~please apply the correct Kura formatting so that formatting changes don't pollute the diff.~ Nevermind... it is correct now, the issue was there before your PR. I would prefer not polluting the PR with formatting changes but if you don't want to update it it's ok for me.

**Comment by salvatore-coppola** [comment]
> @salvatore-coppola ~please apply the correct Kura formatting so that formatting changes don't pollute the diff.~ Nevermind... it is correct now, the issue was there before your PR. I would prefer not polluting the PR with formatting changes but if you don't want to update it it's ok for me.

i prefer to set the right formatting.

**Comment by mattdibi** [comment]
Running tests on RPi Raspberry Pi OS 64bit.

**Before this PR**: 

I set the wlan0 interface in station mode and connected to my laptop AP. Then disabled it.
When re-enabling and setting as dhcp and station mode the user is eased in the operation with some pre-configured fields. One of those fields seems to be the password.
Applying the configuration, it will not connect as previously, also the check password verification fails with the error:

```
2023-05-17T08:51:36,995 [ConfigurationListener Event Queue] INFO  o.e.k.i.l.n.c.NetInterfaceConfigSerializationServiceImpl - Not rewriting network interfaces file because it is the same
2023-05-17T08:51:36,999 [ConfigurationListener Event Queue] ERROR o.e.k.n.a.v.l.WpaSupplicantConfigWriter - Failed to configure WPA Supplicant
2023-05-17T08:51:37,000 [ConfigurationListener Event Queue] ERROR o.e.k.n.a.NetworkConfigurationServiceImpl - Error updating the configuration
org.eclipse.kura.KuraException: An internal error occurred.
	at org.eclipse.kura.KuraException.internalError(KuraException.java:123)
	at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.writeAndMoveFile(WpaSupplicantConfigWriter.java:192)
	at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.writeConfig(WpaSupplicantConfigWriter.java:146)
	at org.eclipse.kura.net.admin.visitor.linux.AbstractLinuxConfigWriter.visit(AbstractLinuxConfigWriter.java:71)
	at org.eclipse.kura.net.admin.visitor.linux.WifiConfigWriter.visit(WifiConfigWriter.java:43)
	at org.eclipse.kura.net.admin.visitor.linux.LinuxWriteVisitor.visit(LinuxWriteVisitor.java:51)
	at org.eclipse.kura.core.net.NetworkConfiguration.accept(NetworkConfiguration.java:163)
	at org.eclipse.kura.net.admin.NetworkConfigurationServiceImpl.executeVisitors(NetworkConfigurationServiceImpl.java:317)
	at org.eclipse.kura.net.admin.NetworkConfigurationServiceImpl.updated(NetworkConfigurationServiceImpl.java:262)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeModifiedMethod(SingleComponentManager.java:836)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.modify(SingleComponentManager.java:791)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:709)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:673)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:435)
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:316)
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:118)
	at org.eclipse.equinox.internal.cm.EventDispatcher$1.run(EventDispatcher.java:92)
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:40)
Caused by: org.eclipse.kura.KuraException: An internal error occurred. the passwd can not be null
	at org.eclipse.kura.KuraException.internalError(KuraException.java:108)
	at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.updateWPA(WpaSupplicantConfigWriter.java:307)
	at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.generateWpaSupplicantConf(WpaSupplicantConfigWriter.java:216)
	at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.writeAndMoveFile(WpaSupplicantConfigWriter.java:187)
	... 26 more
2023-05-17T08:51:37,033 [qtp1000748266-1554] INFO  o.e.k.w.s.n.GwtNetworkServiceImpl - Get Wifi Country Code impl
2023-05-17T08:51:37,072 [qtp1000748266-1554] INFO  o.e.k.l.n.u.IwCapabilityTool - Get Wifi Country Code Output = global
2023-05-17T08:51:37,073 [qtp1000748266-1554] INFO  o.e.k.l.n.u.IwCapabilityTool - Get Wifi Country Code Output = country 00: DFS-UNSET
```

Looking at the snapshot it seems that the corresponding property is empty:

```xml
<esf:property array="false" encrypted="true" name="net.interface.wlp1s0.config.wifi.infra.passphrase" type="Password">
                <esf:value/>
            </esf:property>
```

Setting again the password, makes the system capable to connect again to the Wi-Fi AP configured

**After this PR**:

Upon re-enabling the wifi interface no error is thrown in the log and the device connects correctly to the AP without user intervention.

Additionally, when first connecting to an AP, you'll be warned about the empty password field with the following error:

image

@salvatore-coppola I feel like a message about the empty password field would help with the UX. At this time there's no message in the log nor anything that tells the user what spawned the error. Maybe I missed it?

**Review by mattdibi — APPROVED** [review]
> @salvatore-coppola I feel like a message about the empty password field would help with the UX. At this time there's no message in the log nor anything that tells the user what spawned the error. Maybe I missed it?

After a quick chat with @salvatore-coppola  we decided that adding this info to the shown error in not possible and logging anything related to this error would be out of scope.

LGTM

**Pull request merged**
