### PR TITLE
Updated references for new Eclipse broker.

### LINKED ISSUE #2483: Update Eclipse MQTT server reference
**Is your feature request related to a problem? Please describe.**
Eclipse is changing the MQTT endpoint from iot.eclipse.org to mqtt.eclipse.org.

**Describe the solution you'd like**
The mqttdatatransport needs to be updated with the new references

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2483

### CODE REVIEW

**Comment by ralight** [comment]
I would hold off on this for a while until we confirm which ports the websockets support will be on. As far as I remember iot.eclipse.org didn't have websockets support before...

**Comment by MMaiero** [comment]
Yes, we will keep this on hold since it is giving issues with certificates.

Regarding ws it should be currently supported. This is what I find in https://iot.eclipse.org/getting-started/#sandboxes

> You can also use MQTT over WebSockets, both plain and secured, using the following connection URIs (respectively): ws://iot.eclipse.org:80/ws and wss://iot.eclipse.org:443/ws

**Comment by MMaiero** [comment]
Hello @ralight, any update on this?
The switch completed, but I've seen that there is no update on web sockets.
How do we want to proceed here?

Best regards,
Matteo

**Review by pierantoniomerlino — APPROVED** [review]

**Comment by ralight** [comment]
An update - sorry, I've been off with a new baby. Websockets is configured on the broker, on ports 80 and 443 when using the `/mqtt` url. At the moment the higher level infrastructure restricts access to these ports. I've opened a bug to have them allowed: https://bugs.eclipse.org/bugs/show_bug.cgi?id=550530

**Pull request merged**
