### PR TITLE
Windows support, part 1/2

### PR DESCRIPTION
**Pull request by malikm**
Signed-off-by: Martin Malik <Martin.Malik@eurotech.com>

### CODE REVIEW

**Comment by cdealti** [comment]
Well done!

**Comment by cdealti** [comment]
@kartben @dwoodard1 Do #313 and #319 require a CQ by Eclipse?

**Comment by dwoodard1** [comment]
They both exceed 2000 changed lines, so I would say yes, they both would need CQs.

**Comment by cdealti** [comment]
@dwoodard1 @kartben excuse my ignorance, where can I find concise information on how to file a CQ for a Github PR (versus a third-party library)?

Also, I would like to add to Kura some EPL-licensed jars and sources. Do I need to file a CQ for those as well (I mean from IPZilla)? I've found [this](http://blog.gmane.org/gmane.comp.ide.eclipse.incubation/month=20160301). Is it a must-to-read?

**Comment by cdealti** [comment]
@malikm @markcullen we have filed the CQ for your PRs.

**Comment by cdealti** [comment]
@malikm I have rebased your branch and I could update your PR if you grant me write access to your fork

**Comment by malikm** [comment]
@cdealti I have granted you access to my fork.

The missing exe file is the final installer. Would need to see the entire build output, but I assume the installer was not built. Missing NSIS compiler ?

**Pull request merged**
