### PR TITLE
Kura wires Core

### PR DESCRIPTION
**Pull request by amitjoy**

### CODE REVIEW

**Comment by LucaDazi** [comment]
Related to #158 
Waiting for CQ approval on #335

**Comment by cdealti** [comment]
Any volunteers for reviewing this contribution?

**Comment by amitjoy** [comment]
Fixes #163

**Comment by cdealti** [comment]
@amitjoy Can you please ``git rebase -i`` your PR and remove the merge commit?
Then ``git rebase`` your PR against the ``develop`` branch (as opposed to ``git merge``).
This will replay your commits on top of develop avoid the unnecessary merge commit.

**Comment by amitjoy** [comment]
@cdealti Done!

**Comment by amitjoy** [comment]
We need to close this PR as there will be a new PR comprising all the bundles required for` Kura Asset Model `and `Kura Wires` (except Web bundle changes). The new PR would inherently close all the open issues for `Kura Wires`.

**Comment by LucaDazi** [comment]
Closing, as it has been updated through #580

**Pull request closed without merging**
