### PR TITLE
Kura Container management (API - container.orchestrator) #1

### PR DESCRIPTION
**Pull request by GregoryIvo**
PR adds API's to allow for Kura to connect to a local docker image.

**Related Issue:** This PR fixes/closes {N/A}

**Description of the solution adopted:** 
Leverages a package called Docker-Java, which is a http connector for docker. 
Containers can be described as ContinerDescriptors, and this data-type can then be passed to the API to create/delete/modify containers existing on the docker-engine. 

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by GregoryIvo** [comment]
This is currently successfully building on my local computer, waiting for eclipse builds to verify implementation.

**Comment by GregoryIvo** [comment]
List of plugins used:

**com.github.docker-java**
 - docker-java 3.2.11
 - docker-java-core 3.2.12
 - docker-java-api 3.2.12
 - docker-java-transport 3.2.12
 - docker-java-transport-httpclient5 3.2.12
 
**commons-io**
 - commons-io 2.6
 
**org.apache.commons**
 - commons-compress 1.12
 - 
**commons-lang**
 - commons-lang 2.6
 
**com.fasterxml.jackson.core**
 - jackson-databind 2.10.3
 - jackson-core 2.10.3
 - jackson-annotations 2.10.3
 
**org.apache.httpcomponents.client5**
 - httpclient5 5.0.3
 - httpcore5 5.0.2
 
**net.java.dev.jna**
 - jna 5.8.0
 
**commons-codec**
 - commons-codec 1.13

**Comment by MMaiero** [comment]
It seems that one of the latest commits have broken the tests, so the build is failing.
@GregoryIvo Can you please have a check please? Thanks

**Comment by GregoryIvo** [comment]
Having some trouble with moving the dependencies but will hopefully get it working ASAP.

**Comment by GregoryIvo** [comment]
@MMaiero  Passes, Tested, and ready for review!

**Comment by MMaiero** [comment]
The Clearly Defined reports for the dependencies added:
Screenshot 2022-02-14 at 09 48 51
Screenshot 2022-02-14 at 09 49 26
Screenshot 2022-02-14 at 09 50 07
Screenshot 2022-02-14 at 09 50 40
Screenshot 2022-02-14 at 09 51 15
Screenshot 2022-02-14 at 09 52 40
Screenshot 2022-02-14 at 09 53 12
Screenshot 2022-02-14 at 09 53 40
Screenshot 2022-02-14 at 09 54 05
Screenshot 2022-02-14 at 09 54 35
Screenshot 2022-02-14 at 09 55 01
Screenshot 2022-02-14 at 09 59 59
Screenshot 2022-02-14 at 10 00 29
Screenshot 2022-02-14 at 10 00 58

The only dependency that requires attention is:
Screenshot 2022-02-14 at 10 02 48

This will require a CQ

**Comment by GregoryIvo** [comment]
> The Clearly Defined reports for the dependencies added: Screenshot 2022-02-14 at 09 48 51 Screenshot 2022-02-14 at 09 49 26 Screenshot 2022-02-14 at 09 50 07 Screenshot 2022-02-14 at 09 50 40 Screenshot 2022-02-14 at 09 51 15 Screenshot 2022-02-14 at 09 52 40 Screenshot 2022-02-14 at 09 53 12 Screenshot 2022-02-14 at 09 53 40 Screenshot 2022-02-14 at 09 54 05 Screenshot 2022-02-14 at 09 54 35 Screenshot 2022-02-14 at 09 55 01 Screenshot 2022-02-14 at 09 59 59 Screenshot 2022-02-14 at 10 00 29 Screenshot 2022-02-14 at 10 00 58
> 
> The only dependency that requires attention is: Screenshot 2022-02-14 at 10 02 48
> 
> This will require a CQ

**Comment by MMaiero** [comment]
@GregoryIvo Hello, why this PR was closed?
We have mapped the Eclipse CQ to this code contribution. It is important, indeed, to keep it open for the IP team to check.
Thanks

**Pull request closed without merging**
