### PR TITLE
Update to Equinox Neon.3

### PR DESCRIPTION
**Pull request by ctron**
This fixes the build issue due to the archived Neon.1 release

Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
I personally would not like to change the equinox we tested so far.
Is there no possibility to keep the Neon.1?

**Comment by cdealti** [comment]
@ctron obviously we cannot depend on these zip archives being "archived". Remember that you originally changed the build to fetch the target platform from "official" sources.
I would add the requirement that these sources are also "persistent".
The alternative is that we will have to upload the Equinox zip to one of our S3 buckets.

**Comment by ctron** [comment]
We can fall back to the archived version. But maybe there is a good reason why Neon.1 was archived while Neon.2, Neon.3 and Neon where not: [1].

If you want to switch to the archived version, it is here: [2]

[1] http://download.eclipse.org/equinox/drops/?d
[2] http://archive.eclipse.org/equinox/drops/R-Neon.1-201609071200/download.php?dropFile=equinox-SDK-Neon.1.zip

**Comment by ctron** [comment]
So, if you would like to stick to the archive version of Neon.1, then you can use PR #1235

**Comment by cdealti** [comment]
@ctron we agreed to upgrade to Oxygen. Can you close this?

**Comment by MMaiero** [comment]
@ctron Do you believe we can close this PR?

**Comment by ctron** [comment]
Sure, close it.

**Pull request closed without merging**
