### PR TITLE
Code formatting and cleanup

### LINKED ISSUE #324: Create code style guide/settings
Maybe there already is, but I did not find anything in the GitHub Wiki, the Eclipse Wiki, the `CONTRIBUTING.md` file or the `README.md` file.

What are the requirements for code style when submitting changes? And were do I find those?

Maybe it would also be nice to have an Eclipse code formatter settings file, so that I can be applied automatically on each save.

### PR DESCRIPTION
**Pull request by MMaiero**
This pull request closes #324 
It contains the formatting and cleanup of all the project's code (I've not touched the old classic-web).

### CODE REVIEW

**Comment by MMaiero** [comment]
I would like to merge this as soon as possible. Anything against it?

**Comment by MMaiero** [comment]
@ctron For the package-info we can try to format using Neon and see if it has the same issue (I'm running Mars).
Anyway, I think it's a really minor issue. What you think?

**Comment by ctron** [comment]
I don't think there is any improvement in Neon. But yes, let's ignore that an clean it up manually over time afterwards.

**Comment by MMaiero** [comment]
So, I proceed with merging?

**Comment by ctron** [comment]
+1

**Pull request merged**
