### PR TITLE
fix(log.filesystem.provider): prevent EOF ending incomplete lines and refactor of parser

### PR DESCRIPTION
**Pull request by marcellorinaldo**
Signed-off-by: Marcello Martina <martina.marcello.rinaldo@outlook.com>

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

The log files that we are reading can be written character by character. This could mislead the reader thread if the line has not been completely written, since once EOF is detected the [RandomAccessFile.readLine()](https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html#readLine()) returns the line read up to that point. On the next iteration, the read resumes from that point resulting in an unexpected start of line, thus causing a parse exception. As an example, consider the following case:

*First read, line not completely written by log4j but `readLine` called:*
```
2022-09-07T11:47:23,901 [qtp24668432-131] INFO  o.e.k.w.s.s.WiresBlinkServlet - unregiEOF
```
*Second read, resumes from the last read character and causes exception:*
```
stered
```

Sometimes parsing exceptions arise from the `log.filesystem.provider` component (https://github.com/eclipse/kura/issues/4133). This is due to the `KuraLogLineParser` which is implemented as a singleton but is concurrently accessed by all the instances of `FilesystemLogProvider`s.

**Related Issue:** [Error parsing Kura log timestamp](https://github.com/eclipse/kura/issues/4133).

**Description of the solution adopted:** Added a utility method to read lines until a new line is encountered. It stores a pointer to the last character read that is not an `EOF` so that we an `EOF` is encountered it can resume the reading and finish the line.

`KuraLogLineParser` has been refactored to not be a singleton.

**Screenshots:** N/A.

**Any side note on the changes made:** N/A.

### CODE REVIEW

**Review by salvatore-coppola — APPROVED** [review]

**Comment by marcellorinaldo** [comment]
Issue don't fixed yet, observed a `ParseException` while changing firewall settings.

**Comment by salvatore-coppola** [comment]
> Issue don't fixed yet, observed a `ParseException` while changing firewall settings.

try to add a debub log when the line is read so we can se the real read line

**Review by salvatore-coppola — APPROVED** [review]
I've some doubt on the UTF-8 characters over the first 256 but let's keept as it is for the moment.

**Comment by mstankovic** [comment]
Im not able to see errors anymore. Issue seems to be fixed.

**Pull request merged**
