### PR TITLE
Changed exists plugin default. Now it's disabled.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Steps to be completed after merge: 

- [ ] add profile to Hudson
- [ ] document the new check-exists-plugin profile

### CODE REVIEW

**Comment by cdealti** [comment]
@MMaiero is #1782 by @ctron doing the same thing?

**Comment by MMaiero** [comment]
this is slightly more up to date dealing also with the examples

**Comment by MMaiero** [comment]
@ctron Ok for you this version?

**Comment by ctron** [comment]
So my understanding is that when I check out the released version (e.g. from a tag) I can build it locally even though the release has been made, without the requirement to make any changes to the checked out code.

In this case: +1

**Comment by MMaiero** [comment]
Yes, that is the expected bahaviour

**Pull request merged**
