### PR TITLE
Add jdk.dio source files.

### PR DESCRIPTION
**Pull request by dwoodard1**
Signed-off-by: David Woodard <david.woodard@eurotech.com>

### CODE REVIEW

**Comment by dwoodard1** [comment]
@ctron Added JDK DIO source files, please have a look.

**Comment by ctron** [comment]
So I am currently trying to re-produce the build. As I see we now have two target anymore. armv6hf and x86_64. I do see a path (although I couldn't test it up until now) for the arm compilation. But how about the x86_64? There are no pi-tools for plain x86_64?!

**Comment by ctron** [comment]
Also for the arm target the README requests:
> Linaro GCC 4.7.2

Searching for "linaro" on the device gives me:
```
root@raspberrypi:/home/pi/kura/target-platform/jdk.dio-parent/src/dev# apt-cache search linaro
lava - Linaro Automated Validation Architecture metapackage
lava-coordinator - LAVA Coordinator daemon
lava-dev - Linaro Automated Validation Architecture developer support
lava-dispatcher - Linaro Automated Validation Architecture dispatcher
lava-server - Linaro Automated Validation Architecture server
lava-server-doc - Linaro Automated Validation Architecture documentation
lava-tool - command line utility for LAVA
lavapdu-client - LAVA PDU client
lavapdu-daemon - LAVA PDU control daemon
linaro-image-tools - collection of tools to work with Linaro images
python-linaro-image-tools - Python library for the manipulation of Linaro bootable media
```

But nothing with "gcc".

**Comment by LucaDazi** [comment]
JDK DIO is an OpenJDK project.
May I suggest of taking a look at their documentation in order to replicate the build?
http://openjdk.java.net/projects/dio/

**Comment by ctron** [comment]
Running the `Makefile.poky` results in:

```
root@raspberrypi:/home/pi/kura/target-platform/jdk.dio-parent/src/dev# make -f Makefile.poky libdio.so
find: `src/se/classes': No such file or directory
find: `src/share/classes': No such file or directory
Creating output directories
Compiling src/se/native/com/oracle/dio/uart/impl/jni_signal_dispatcher.cpp
src/se/native/com/oracle/dio/uart/impl/jni_signal_dispatcher.cpp: In function ‘jint Java_com_oracle_dio_uart_impl_ModemSignalDispatcher_startListening0(JNIEnv*, jobject, jint)’:
src/se/native/com/oracle/dio/uart/impl/jni_signal_dispatcher.cpp:71:17: note: #pragma message: !!!WARNING!!! UNSAFE cast to long to prevent the following error when building for x86_64:
 #pragma message "!!!WARNING!!! UNSAFE cast to long to prevent the following error when building for x86_64:"
                 ^
src/se/native/com/oracle/dio/uart/impl/jni_signal_dispatcher.cpp:72:17: note: #pragma message: error: cast from ‘javacall_handle {aka void*}’ to ‘jint {aka int}’ loses precision [-fpermissive]
 #pragma message "error: cast from ‘javacall_handle {aka void*}’ to ‘jint {aka int}’ loses precision [-fpermissive]"
                 ^
Compiling src/se/native/com/oracle/dio/uart/impl/jni_uart.cpp
Compiling src/se/native/com/oracle/dio/gpio/impl/jni_gpio.cpp
Compiling src/se/native/com/oracle/dio/dio_nio.cpp
Compiling src/se/native/com/oracle/dio/dio_exceptions.cpp
Compiling src/se/native/com/oracle/dio/spibus/impl/jni_spi.cpp
Compiling src/se/native/com/oracle/dio/dio_common.cpp
src/se/native/com/oracle/dio/dio_common.cpp: In function ‘javacall_dio_result saveDeviceReferenceToHandleObject(JNIEnv*, jobject, device_reference)’:
src/se/native/com/oracle/dio/dio_common.cpp:145:17: note: #pragma message: !!!WARNING!!! UNSAFE cast to long to prevent the following error when building for x86_64:
 #pragma message "!!!WARNING!!! UNSAFE cast to long to prevent the following error when building for x86_64:"
                 ^
src/se/native/com/oracle/dio/dio_common.cpp:146:17: note: #pragma message: error: cast from ‘device_reference {aka _device_reference*}’ to ‘jint {aka int}’ loses precision [-fpermissive]
 #pragma message "error: cast from ‘device_reference {aka _device_reference*}’ to ‘jint {aka int}’ loses precision [-fpermissive]"
                 ^
Compiling src/se/native/com/oracle/dio/i2cbus/impl/jni_i2c.cpp
Compiling src/se/native/com/oracle/dio/dio_event_queue.cpp
compiling src/se/native/com/oracle/dio/javautil_circular_buffer.c
compiling src/se/native/com/oracle/dio/javautil_linked_list.c
compiling src/se/native/com/oracle/dio/javacall_properties.c
compiling src/se/native/com/oracle/dio/javautil_unicode.c
compiling src/se/linux/native/com/oracle/dio/memory.c
compiling src/se/linux/native/com/oracle/dio/os.c
compiling src/share/linux/native/com/oracle/dio/uart/serial.c
compiling src/share/linux/native/com/oracle/dio/uart/uart.c
compiling src/share/linux/native/com/oracle/dio/gpio/gpio.c
compiling src/share/linux/native/com/oracle/dio/spibus/spi.c
compiling src/share/linux/native/com/oracle/dio/i2c/i2c.c
linking libdio.so
ld: unrecognized option '-Wl'
ld: use the --help option for usage information
Makefile.poky:192: recipe for target 'libdio.so' failed
make: *** [libdio.so] Error 1

```

**Comment by ctron** [comment]
Thanks @LucaDazi  ... but that page doesn't seem really helpful?!

**Comment by LucaDazi** [comment]
I know @ctron. What I mean is that probably asking the OpenJDK DIO team how to replicate the build would make more sense.

**Comment by ctron** [comment]
Downloading: https://releases.linaro.org/components/toolchain/binaries/latest/arm-linux-gnueabihf/

Running:

```
export PI_TOOLS=/home/jreimann/Downloads/linaro/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabihf
export JAVA_HOME=/usr/lib/jvm/java-1.8.0
make libdio.so
```

Fails with:
```
find: ‘src/se/classes’: No such file or directory
find: ‘src/share/classes’: No such file or directory
Creating output directories
Compiling src/se/native/com/oracle/dio/dio_event_queue.cpp
/home/jreimann/Downloads/linaro/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabihf/bin/arm-none-linux-gnueabi-gcc -fPIC -Wno-psabi -DJAVACALL_REPORT_LEVEL=4 -DENABLE_DEVICEACCESS -c -MMD -MF /home/jreimann/git/kura/target-platform/jdk.dio-parent/src/dev/build/obj/dio_event_queue.o.d -Isrc/se/linux/native/com/oracle/dio/ -Isrc/se/native/com/oracle/dio/ -Isrc/share/linux/native/com/oracle/dio/uart/ -Isrc/share/native/com/oracle/dio/ -I/usr/lib/jvm/java-1.8.0/include -I/usr/lib/jvm/java-1.8.0/include/linux src/se/native/com/oracle/dio/dio_event_queue.cpp -o /home/jreimann/git/kura/target-platform/jdk.dio-parent/src/dev/build/obj/dio_event_queue.o
make: /home/jreimann/Downloads/linaro/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabihf/bin/arm-none-linux-gnueabi-gcc: Command not found
make: *** [dio_event_queue.o] Error 127
```

I think it would be more helpful if you could provide some steps to re-produce this.

Btw, running simply `make` doesn't work at all because it seems there are file missing for that.

**Comment by ctron** [comment]
Well, as you are providing this executable, you are required by the GPL to provide this.

Btw, if there are sources missing, I think those have to added as well.

How are you compiling this?

**Review by ctron — CHANGES_REQUESTED** [review]
Currently I see to major issues here:
1. Source code is missing
2. It doesn't build

**Comment by cdealti** [comment]
@ctron I've build the native libraries for several architectures from these sources. Let me figure out how.
I believe the original code was meant to be compiled on the Raspberry Pi and there was nothing for cross-compiling.
I'll come up with a solution asap

**Comment by cdealti** [comment]
@ctron I've added the missing source code. It happened that this was in a ``classes`` directories and ignored by our ``.gitignore`` file.

I've also have a couple of Makefiles that worked better building the native libraries for me.
I have not committed these to avoid proliferation of Makefiles.

Maybe you will come up with a single Makefile working for every OS/architecture.

**Comment by ctron** [comment]
Just check in everything you have and I will give it a look tomorrow and maybe aggregate the Makefiles, if that is possible.

**Comment by ctron** [comment]
Running the updated PR on a Raspberry Pi again now successfully builds the Java part. But again fails with the native part:

```
compiling src/share/linux/native/com/oracle/dio/uart/uart.c
compiling src/share/linux/native/com/oracle/dio/gpio/gpio.c
compiling src/share/linux/native/com/oracle/dio/spibus/spi.c
compiling src/share/linux/native/com/oracle/dio/i2c/i2c.c
linking libdio.so
ld: unrecognized option '-Wl'
ld: use the --help option for usage information
Makefile.poky:192: recipe for target 'libdio.so' failed
make: *** [libdio.so] Error 1
```

So maybe you could provide the commands that you run on a Raspberry Pi in order to get a successful build.

**Comment by cdealti** [comment]
@ctron this not going to be merged on the release-3.0.0 branch.
I understand your frustration with the Makefiles and I'll try to find one that works.

However, I'll try to address these issues in the next development cycle if this is OK for you.

**Comment by ctron** [comment]
For me this is not ok. As this is overdue for several releases. And I also think that the GPL is quite clear in this area. As are the Eclipse policies around that.

**Comment by cdealti** [comment]
@ctron I agree that this is overdue but note that this PR is against the develop branch and we are on the release branch and in the process of completing the QA process.

The next release candidate on Hudson will be hopefully the release and as you know this is due by end of the week or very early next week. 

I'm not comfortable with moving this on the release branch included updating the jar and native libraries for JDK DIO.

**Comment by cdealti** [comment]
@ctron @dwoodard1 I've pushed an Makefile which should succeed in building the native libraries for x86_64. Cross compiling for the RPI is not much different and I'll work on that.
It would be great if you could check if this works for the x86_64 architecture because it shows at least that all the sources are in this PR.

**Comment by ctron** [comment]
@cdealti So before I test this again. Does this work for you? On which OS/distribution? Do I need to manually install anything before testing this.

**Comment by cdealti** [comment]
It builds the native lib on my old Ubuntu 12.04 Linux box.
Install anything? Nothing I'm aware of.

**Comment by ctron** [comment]
So with RHEL7 I run into the same error:

```
compiling src/share/linux/native/com/oracle/dio/spibus/spi.c
linking libdio.so
cc: error: unrecognized command line option ‘-Wl’
make: *** [libdio.so] Error 1
```

I will try Ubuntu 12.04 then.

**Comment by cdealti** [comment]
@ctron wait a moment, this -Wl option is not quite right but it works on mine.
In the meantime can you post the man gcc section describing the -Wl option. you should have it

**Comment by ctron** [comment]
That is why I posted this 22 days ago.

Sure here is the snippet from `man gcc`:
```
       -Wl,option
           Pass option as an option to the linker.  If option contains commas,
           it is split into multiple options at the commas.  You can use this
           syntax to pass an argument to the option.  For example,
           -Wl,-Map,output.map passes -Map output.map to the linker.  When
           using the GNU linker, you can also get the same effect with
           -Wl,-Map=output.map.
```

**Comment by ctron** [comment]
Compiling this on Ubuntu 12.04 works for me.

You need to setup up a virtual machine though as it seems that installing the JDK inside of an Ubuntu 12.04 docker container is not possible.

So if we could now fix this for the Raspberry Pi, that would be awesome. As we don't really ship x86_64.

**Comment by cdealti** [comment]
please try the last commit pushed on RHEL

**Comment by ctron** [comment]
That fixes it on RHEL7!

**Comment by ctron** [comment]
Should that work as well on Raspbian?

**Comment by ctron** [comment]
Running the `Makefile.x86_64` seems to work for Raspbian as well.

**Review by ctron — APPROVED** [review]

**Comment by dwoodard1** [comment]
@ctron Thanks! Is this enough to get a +1 for the review? Although you're not actually part of the review, I think they were waiting for you to approve this issue.

**Comment by ctron** [comment]
I agree, this is fine for building on two platforms. IMHO there is no need to have this automatically rebuild every time with the main build. As long as it **can** be build and the sources match the binaries used by Kura that is fine.

I would consider this issue closed once this is merged.

**Comment by cdealti** [comment]
@ctron You are the reviewer of this PR. You can merge it if you like it.

**Comment by ctron** [comment]
@cdealti  as there are a few commits, I guess it would be best if @dwoodard1 would to the merge and create a proper message. +1 from my side.

**Comment by cdealti** [comment]
@ctron I can squash the commits and provide a meaning full message. @dwoodard1 is busy with the Red Hat Summit 2017 CodeStarter. Are you OK with this plan?

**Comment by ctron** [comment]
Well ok, then squash and merge, don't wait for me.

**Pull request merged**
