### PR TITLE
Fix ip forwarding

### PR DESCRIPTION
**Pull request by ibinshtok**

### CODE REVIEW

**Comment by ibinshtok** [comment]
@MMaiero, @pierantoniomerlino I created this PR, but still working on it ...

**Comment by MMaiero** [comment]
@ibinshtok As far as you remember, is this PR ready for merge?
Do we have a corresponding issue?

Thanks

**Comment by ibinshtok** [comment]
@MMaiero sorry for not replying, I have not seen your comment. This PR was an attempt to fix the Kura issue #1195. These changes worked for me, but only on platforms that support rule tagging (e.g. -m comment --comment "pf1") added to 'Port Forward' and 'IP Forward' rules. If platform doesn't support this, firewall implementation would be broken. If I remember right, Eurotech platforms supported it, but not Raspberry Pi.

**Comment by nicolatimeus** [comment]
@ibinshtok just a quick question about your last comment:
When you say that this might break firewall on Raspberry Pi, do you mean that firewall will work with this PR, but it will still have issues described in #1195 or that merging this PR will result in a completely not working firewall implementation for that platform?

**Comment by ibinshtok** [comment]
@nicolatimeus No, the issue described in #1195 will be fixed, but if tagging is not supported on a particular platform, an iptables rule that contains something like '-m comment --comment "pf1"' will fail to apply. So that iptables, iptables-save, and iptables-restore commands will fail. If I remember right, I developed it on BoltMAR 20-28, so that it will work with Eurotech most recent bsp versions. But I believe it failed on Pi.

**Comment by cdealti** [comment]
@ibinshtok would you merge this if the only supported platform was the RPI?

**Comment by ibinshtok** [comment]
@cdealti I would not merge it unless all platforms support it.

**Comment by pierantoniomerlino** [comment]
The feature was added in #3334

**Pull request closed without merging**
