### PR TITLE
Fixed Karaf native libs loading.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by cdealti** [comment]
@ctron can you please review?

**Comment by ctron** [comment]
Running the distribution `rhel-7-x86_64` I get in the log:

```
2017-05-31 15:44:06,249 | ERROR |  Component Actor | usb                              | 139 - org.eclipse.kura.linux.usb - 1.0.100 | [org.eclipse.kura.usb.UsbService(25)] The activate method has thrown an exception
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.kura.linux.usb.LinuxUdevNative
	at org.eclipse.kura.linux.usb.UsbServiceImpl.activate(UsbServiceImpl.java:52)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_131]
	at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:222)
	at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:37)
	at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:615)
…
```

**Comment by cdealti** [comment]
#1321 needs to be merged too?

**Comment by MMaiero** [comment]
I've successfully tested it with a clean centos 7 installation and one of our gateways. But it's possible that #1321 could solve @ctron issue in his environment.

**Comment by MMaiero** [comment]
Also running on RHEL seems to work:
```
karaf@root()> list
START LEVEL 100 , List Threshold: 50
 ID | State    | Lvl | Version                | Name
--------------------------------------------------------------------------------------------------------------------------
 27 | Active   |  80 | 1.1.100                | Java API for working with Human Interface USB Devices (HID), Fragments: 28
 28 | Resolved |  80 | 1.1.100                | Native libraries for 'com.codeminders.hidapi' on x86_64, Hosts: 27
 29 | Active   |  80 | 1.0.100                | gwt-user
 33 | Active   |  80 | 1.0.100                | jdk.dio, Fragments: 34
 34 | Resolved |  80 | 1.0.100                | jdk.dio.x86_64, Hosts: 33
 35 | Active   |  80 | 0.9.4                  | minimal-json
 42 | Active   |  50 | 2.17.2                 | camel-catalog
 43 | Active   |  80 | 2.17.2                 | camel-commands-core
 44 | Active   |  50 | 2.17.2                 | camel-core
 45 | Active   |  50 | 2.17.2                 | camel-core-osgi
 46 | Active   |  80 | 2.17.2                 | camel-karaf-commands
 47 | Active   |  80 | 1.3.0                  | Apache Commons Exec
 48 | Active   |  80 | 1.3.2                  | Apache Commons FileUpload
 49 | Active   |  80 | 2.4.0                  | Commons IO
 50 | Active   |  80 | 3.4.0                  | Apache Commons Lang
 51 | Active   |  80 | 3.5.0                  | Apache Commons Net
 52 | Active   |  80 | 3.0.0                  | Apache Felix Dependency Manager
 53 | Active   |  80 | 0.9.6                  | Apache Felix Deployment Admin
 90 | Active   |  80 | 1.1.100.v20150430-1834 | IO Connector Service
 91 | Active   |  80 | 1.0.500.v20130404-1337 | Equinox Util Bundle
118 | Active   |  80 | 1.3.0.201706200926     | org.eclipse.kura.api
119 | Active   |  80 | 1.0.0                  | Asset Cloudlet
120 | Active   |  80 | 1.0.0                  | Asset Helper Service Provider
121 | Active   |  80 | 1.0.0                  | Kura Asset Accessor Provider
122 | Active   |  80 | 1.2.0                  | org.eclipse.kura.camel
123 | Active   |  80 | 1.1.0                  | Camel Cloud Factory
124 | Active   |  80 | 1.0.100                | org.eclipse.kura.core
125 | Active   |  80 | 1.1.0                  | org.eclipse.kura.core.cloud
126 | Active   |  80 | 1.0.100                | org.eclipse.kura.core.comm
127 | Active   |  80 | 1.1.0                  | org.eclipse.kura.core.configuration
128 | Active   |  80 | 1.0.100                | org.eclipse.kura.core.crypto
129 | Active   |  80 | 1.0.200.201706200926   | org.eclipse.kura.core.net
130 | Active   |  80 | 1.0.100                | org.eclipse.kura.core.status
131 | Active   |  80 | 1.0.100                | org.eclipse.kura.deployment.agent
132 | Active   |  80 | 1.0.0                  | Driver Helper Service Provider
133 | Active   |  80 | 1.0.100                | org.eclipse.kura.linux.bluetooth
134 | Active   |  80 | 1.0.100                | org.eclipse.kura.linux.clock
135 | Active   |  80 | 1.0.5                  | org.eclipse.kura.linux.command
136 | Active   |  80 | 1.0.100                | org.eclipse.kura.linux.gpio
137 | Active   |  80 | 1.0.200.201706200926   | org.eclipse.kura.linux.net
138 | Active   |  80 | 1.0.200.201706200926   | org.eclipse.kura.linux.position
139 | Active   |  80 | 1.0.200.201706200926   | org.eclipse.kura.linux.usb, Fragments: 140
140 | Resolved |  80 | 1.0.200.201706200926   | Native libraries for 'org.eclipse.kura.linux.usb' on x86_64, Hosts: 139
141 | Active   |  80 | 1.0.100                | org.eclipse.kura.linux.watchdog
142 | Active   |  80 | 1.0.100.201706200926   | Kura Localization, Fragments: 143
143 | Resolved |  80 | 1.0.0                  | Localization Resources, Hosts: 142
144 | Active   |  80 | 1.0.0                  | Kura Base Utilities
145 | Active   |  80 | 2.0.200.201706200926   | org.eclipse.kura.web2
146 | Active   |  80 | 1.0.100.201706200926   | Different Wire Components Provider
147 | Active   |  80 | 1.0.0                  | Kura Wires Helper Service Provider
148 | Active   |  80 | 1.0.0                  | Kura Wires Topology Management
149 | Active   |  80 | 1.2.100                | Comm (Incubation), Fragments: 150
150 | Resolved |  80 | 1.2.100                | bundle.name, Hosts: 149
151 | Active   |  80 | 2.3.0                  | HSQLDB
157 | Active   |  80 | 1.1.0.201505202023     | org.osgi:org.osgi.service.deploymentadmin
158 | Active   |  80 | 1.0.0.201505202023     | org.osgi:org.osgi.service.io
159 | Active   |  80 | 1.0.1.201505202024     | org.osgi:org.osgi.service.wireadmin
160 | Active   |  80 | 1.0.1.201505202026     | org.osgi:org.osgi.util.measurement
161 | Active   |  80 | 1.0.1.201505202026     | org.osgi:org.osgi.util.position
162 | Active   |  80 | 1.2.100                | usb4java
164 | Active   |  80 | 1.2.100                | usb4java-javax
karaf@root()> 
```

**Comment by MMaiero** [comment]
Merging to speed up a little bit the things. If the issue occurs again, we will reopen.

**Pull request merged**
