### PR TITLE
Fix container orchestrator logging so it doesn't pollute the log-file

### PR DESCRIPTION
**Pull request by GregoryIvo**
This fix changes the way container pull state is reported. Only the delta is printed resulting in significantly less logger noise. 

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to inderstand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by GregoryIvo** [comment]
@MMaiero What do you think about this as a logger solution?  
Now it will only print the state when it changes, this way the user has some sort of feedback that the container pull is working, and the logs are not absolutely polluted like before?  😆

**Comment by MMaiero** [comment]
Hello,
here my logs out of this PR:
```
2022-03-10T09:10:13,172 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Pulling from library/nginx
2022-03-10T09:10:13,760 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Pulling fs layer
2022-03-10T09:10:13,764 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Waiting
2022-03-10T09:10:14,320 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:14,444 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Download complete
2022-03-10T09:10:14,873 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:15,874 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Verifying Checksum
2022-03-10T09:10:15,877 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Download complete
2022-03-10T09:10:16,025 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:17,502 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Verifying Checksum
2022-03-10T09:10:17,505 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Download complete
2022-03-10T09:10:17,750 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:18,922 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Verifying Checksum
2022-03-10T09:10:18,924 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Download complete
2022-03-10T09:10:19,203 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:25,137 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Verifying Checksum
2022-03-10T09:10:25,139 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:25,141 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Download complete
2022-03-10T09:10:25,207 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Downloading
2022-03-10T09:10:27,424 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Download complete
2022-03-10T09:10:27,813 [docker-java-stream-1663653280] INFO  o.e.k.c.o.p.i.DockerServiceImpl - Container Layer Pull State: Extracting
```

It is a big improvement compared to the previous, but do you believe we can add more detail on this log? I mean we have different pull states Downloading, but it is not clear what is downloading, what layer or whatever is there. Same for the other messages.
Do you believe we can have more in depth logs? I believe that more details in each line will make easy also to provide support for users when something breaks.

**Comment by GregoryIvo** [comment]
new more detailed log, + error text
Screen Shot 2022-03-10 at 4 39 21 PM

new more detailed log, + success text
image

trailing } to be removed in next commit

﻿

**Comment by MMaiero** [comment]
@GregoryIvo Please check the sonar results: https://github.com/eclipse/kura/pull/3840/checks?check_run_id=5505231207

**Comment by MMaiero** [comment]
Plus, check the formatting

**Comment by MMaiero** [comment]
Closing as superseded by #3896

**Pull request closed without merging**
