### PR TITLE
build: Update usb4java to 1.3.0

### PR DESCRIPTION
**Pull request by MMaiero**
> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

maven/mavencentral/org.usb4java/libusb4java/1.3.0, , restricted, clearlydefined
maven/mavencentral/org.usb4java/usb4java/1.3.0, MIT, approved, clearlydefined

### CODE REVIEW

**Comment by MMaiero** [comment]
Opened CQ: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/3087

**Comment by MMaiero** [comment]
Approved: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/3087#note_957845

**Review by pierantoniomerlino — APPROVED** [review]

**Comment by MMaiero** [comment]
I think we decided to keep this on hold for 5.3.0. If we want to merge, let's check that dependent projects still work and that the notice file is updated properly to reflect the new dependencies.

**Comment by pierantoniomerlino** [comment]
@MMaiero I wasn't aware of this. We can revert the commit, if you prefer.

**Pull request merged**
