### PR TITLE
Added Proper Javadoc to INTERNAL_ERROR for discouraged access

### LINKED ISSUE #841: Add Discouraged Access in Javadoc for INTERNAL_ERROR error code
We need to deprecate the use of `KuraErrorCode#INTERNAL_ERROR`

### PR DESCRIPTION
**Pull request by amitjoy**
Fixes #841

### CODE REVIEW

**Comment by ctron** [comment]
We agreed upon not technically deprecating internal error. And I would be against it as long as we don't clear up all references to it at the same time.

Marking it as deprecated will cause numerous warnings in the IDE, which would then hide other warnings.

So as long as we stick to the original idea, please do not deprecate it.

Also I think there is something wrong with the code formatter. I had the feeling that something went wrong in the big code formatter commit, but please do double check if you are using the correct one.

**Comment by amitjoy** [comment]
👍 Yeah I missed that conversation. No problem. There will be some amount of refactoring here and there. I will start with the refactoring in Kura Wires first which I can do with less effort then would like to cover the other areas.

I don't know if something has happened to the formatter in my Eclipse. I can still see in Eclipse Configurations that I have the Kura Code Formatter and CleanUp Formatter set.

**Comment by ctron** [comment]
Do you have the version checked in by @MMaiero in the "setups/formatting" folder?

**Comment by amitjoy** [comment]
@ctron All the formatters are in place.

**Pull request merged**
