### PR TITLE
#1132: Tests for org.eclipse.kura.protocol.modbus

### PR DESCRIPTION
**Pull request by djurod**
- Extracted Communicate, SerialCommunicate and EthernetCommunicate from
  ModbusProtocolDevice class.
- Prepared unit tests for Crc16 and ModbusProtocolDevice classes.

Signed-off-by: Djuro Drljaca <djuro.drljaca@comtrade.com>

### CODE REVIEW

**Comment by djurod** [comment]
Communicate, SerialCommunicate and EthernetCommunicate classes had to be extracted from ModbusProtocolDevice class, without this it was mostly impossible to write any tests for it...

The additional benefit is also decoupling of the classes and reduction in complexity, but there should still be some additional refactoring or cleanup done in the classes.

The extracted classes are almost unchanged, the only changes were related to the decoupling from the ModbusProtocolDevice class (I think that just a few flags were referenced directly).

ModbusProtocolDevice tests in the pull request cover just the some of the methods and the Communicate class is mocked. The reason for this was to first check if the approach is good or not before I covered all methods.

Hopefully with these classes extracted it should now be easier to test also their implementation ... hopefully this can be done without requiring an actual modbus device.

I am aware that this pull request is too big to be merged in the current state, but it could easily be split into multiple pull requests.

**Review by pierrepitiot — COMMENTED** [review]
It looks good for me.  And for sure it will be more "readable" :-)

**Comment by djurod** [comment]
OK, so I will continue working on it.

I will make a few more commits and when I am done, I will split it into multiple pull requests

**Comment by djurod** [comment]
The pull request should be complete now. Could someone review it before I split it into multiple PRs?

**Comment by MMaiero** [comment]
@pierrepitiot Do you have some time for a full review?

**Comment by pierrepitiot** [comment]
Yes I can do a full review

**Review by pierrepitiot — APPROVED** [review]
I am not a specialist for Mockito but everything looks ok for me.

**Comment by djurod** [comment]
OK.

I will start preparing pull requests based on this branch.

**Comment by cdealti** [comment]
@djuro this modbus bundle exported its package and so the implementation.
Your changes are maybe backward compatible but I need to take a closer look

**Comment by cdealti** [comment]
@markoer what should we do with this PR? The plan was to start deprecating ``org.eclipse.kura.protocol.modbus`` favoring a Driver-based implementation based on _j2mod_.
This PR introduces potential breaking changes (because the bundle does not hide the implementation - bad design) and it's too long.

**Comment by markoer** [comment]
Then I suppose we could skip merging the PR in favor of tests of the new implementation. Besides, @darionct  also prepared some modbus tests and that PR has already been merged.

**Comment by MMaiero** [comment]
Closing, as superseded

**Pull request closed without merging**
