### PR TITLE
Upgrade to GWT 2.8.2

### PR DESCRIPTION
**Pull request by ctron**
This upgrades GWT to 2.8.0

**Note:** Don't merge until CQ12311 [1] has been approved

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12311

### CODE REVIEW

**Comment by ctron** [comment]
I did re-base it. Could you please have a look.

**Comment by MMaiero** [comment]
Did you try it with Eclipse? It is giving me a lot of exceptions, especially in the bootstrap part, even if it is compiling in maven. Maybe there is something I've missed

**Comment by ctron** [comment]
Yes I did and it worked fine. As well as with a `build-all.sh` build.

I can retest though. Maybe some later commit has messed things up.

**Comment by MMaiero** [comment]
I've used the oomph setup. Don't know if this could be a possible cause.

**Comment by amitjoy** [comment]
@ctron Any update?

**Comment by MMaiero** [comment]
It is not in the plans for Kura 3.0.0. To discuss for Kura 4.0.0, but we need to consider the change (in terms of requirements of memory, upgrader, bandwidth) compared to the advantages

**Comment by ctron** [comment]
As just discussed on the weekly Kura call, I will rebase this PR so that we can merge this for the next Kura release. We aim to go with GWT 2.8.2, which is covered by this CQ as 2.8.2 only is a service release to 2.8.0 and we do have an approved CQ for that.

**Comment by ctron** [comment]
So from a first look that was easy. It compiles, but I haven't tested it after rebasing and switching to 2.8.2.

I will continue with this next week, because I think we can close this rather quickly.

**Comment by ctron** [comment]
@MMaiero  @dwoodard1 The change works for me. I think this is ready to be merged.

**Comment by MMaiero** [comment]
Testing it now

**Comment by MMaiero** [comment]
The only strange thing I've seen so far moving across all the pages is that the list of snapshots is not available

**Comment by ctron** [comment]
> The only strange thing I've seen so far moving across all the pages is that the list of snapshots is not available

I can reproduce the issue. There is an exception in the browser log. However GWT stack traces are not very helpful. But I will try to find the root cause of this.

**Comment by ctron** [comment]
I just pushed a fix for this issue. I think this actually could already be an issue with previous GWT versions. As it is not really clear to which type to cast. However there already was an explicitly typed version of the same operation and so I simply used that.

The issue is now solved for me.

**Pull request merged**
