### PR TITLE
Error appears after changing console username/password

### LINKED ISSUE #2565: Error appears after changing console username/password
**Describe the bug**
Error message appears after changing console username and password 
error message is `404 ProxyServlet: /admin/denali/xsrf` 

**To Reproduce**
1. Go to WebConsole
2. Change values for username and password
3. Click on Apply button
4. Click "Yes" to confirm changing

**Expected behavior**
Username and password should be changed without error appearing 

**Screenshots**
console_password

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3 (also able to reproduce on RG10-20)
 - Kura version: 4.2-SNAPSHOT 

**Additional context**
- username and password are changed 
- there is no error in kura.log
- unable to reproduce on Kura 4.1

### PR DESCRIPTION
**Pull request by spnettec**
Fix #2565

### CODE REVIEW

**Comment by MMaiero** [comment]
Thank you for the change. But now, if I'm not wrong, a change in the session timeout will not be reflected immediately, right? As well as for the app root.

**Comment by MMaiero** [comment]
Other than that, please apply to the updated code the Kura formatter and cleanup profiles, to match the code style.

**Comment by spnettec** [comment]
> Thank you for the change. But now, if I'm not wrong, a change in the session timeout will not be reflected immediately, right? As well as for the app root.

Yes. I think session timeout and app root is not necessary reflected immediately. If you want i can do that.

**Comment by spnettec** [comment]
I just fixed the cleanup and format. Why the travis-ci failed?

**Comment by MMaiero** [comment]
It reports an error with one of the tests. I have tried to restart the build.

**Comment by MMaiero** [comment]
The original issue should be fixed now in develop branch. Closing for now.

**Pull request closed without merging**
