### PR TITLE
Allow to monitor more than two Ethernet interfaces

### PR DESCRIPTION
**Pull request by ibinshtok**
Signed-off-by: ibinshtok <ilya.binshtok@eurotech.com>

### CODE REVIEW

**Comment by ibinshtok** [comment]
@MMaiero please take a look at this PR that is an attempt to fix Kura issue #1971 that I created today.

**Comment by MMaiero** [comment]
@ibinshtok I have some concerns on this solution: it is not enough general and based on the fact that the interfaces will be named eth* or tun*. But that could be not the case in nowadays operating systems with the consistent device naming. Couldn't we find another idea to achieve this?

**Comment by MMaiero** [comment]
Furthermore, there are test failures

**Comment by ibinshtok** [comment]
@MMaiero I have replaced the newFixedThreadPool with the newCachedThread pool in the activate() method of the EthernetMonitorServiceImpl. It seems to work fine; please take a look.

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
