### PR TITLE
feat: Updated OPC-UA driver to support Milo 0.6.8

### PR DESCRIPTION
**Pull request by nicolatimeus**
> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

* Updated Milo to 0.6.8
* Included new transitive dependencies of Milo 0.6.8
* Removed no longed necessary dependencies
* Replaced empty `netty-all` jar with the Netty component Jars
* Adapted driver code for the new version

This PR adds the following dependency updates:

New dependencies:

* maven/mavencentral/com.google.guava/guava/31.0-jre, Apache-2.0, approved, clearlydefined
* maven/mavencentral/com.google.guava/failureaccess/1.0, Apache-2.0, approved, CQ22654
* maven/mavencentral/com.digitalpetri.fsm/strict-machine/0.6, Apache-2.0, approved, clearlydefined
* maven/mavencentral/com.digitalpetri.netty/netty-channel-fsm/0.8, Apache-2.0, approved, #6168

Updated dependencies:

* maven/mavencentral/org.eclipse.milo/sdk-client/0.6.8, EPL-2.0, approved, iot.milo
* maven/mavencentral/org.eclipse.milo/sdk-core/0.6.8, EPL-2.0, approved, iot.milo
* maven/mavencentral/org.eclipse.milo/stack-client/0.6.8, EPL-2.0, approved, iot.milo
* maven/mavencentral/org.eclipse.milo/stack-core/0.6.8, EPL-2.0, approved, iot.milo

Removed dependencies:

* maven/mavencentral/org.jooq/jool/0.9.10, Apache-2.0, approved, clearlydefined
* maven/mavencentral/com.google.code.findbugs/jsr305/3.0.1, Apache-2.0, approved
* maven/mavencentral/org.eclipse.milo/bsd-parser-core/0.2.4, EPL-2.0, approved, iot.milo
* maven/mavencentral/org.eclipse.milo/bsd-parser-gson/0.2.4, EPL-2.0, approved, iot.milo

### CODE REVIEW

**Comment by nicolatimeus** [comment]
Use Rebase and Merge for merging to preserve the build(deps) commits

**Comment by heyoulin** [comment]
I have done this long long ago. I don't know what's the diffrence. see [https://github.com/spnettec/kura.git](url)

**Comment by MMaiero** [comment]
@nicolatimeus Can you please rebase? Thanks

**Comment by nicolatimeus** [comment]
> I have done this long long ago. I don't know what's the diffrence. see [https://github.com/spnettec/kura.git](url)

Hi @heyoulin, I can't access the provided link.. What are you referring to with "I don't know what's the diffrence"?
If you are referring to the comment about merging using rebase and merge, it is just related to the fact that we are using conventional commits to automate the generation of the release notes.

The comment is about avoiding to squash the `build(deps)` commits so that their message is added to the release notes to track the dependency changes.

**Comment by MMaiero** [comment]
https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&sinceLeakPeriod=true&branch=PR-4374&id=org.eclipse.kura%3Akura

**Review by marcellorinaldo — APPROVED** [review]

**Comment by spnettec** [comment]
> > I have done this long long ago. I don't know what's the diffrence. see [https://github.com/spnettec/kura.git](url)
> 
> Hi @heyoulin, I can't access the provided link.. What are you referring to with "I don't know what's the diffrence"? If you are referring to the comment about merging using rebase and merge, it is just related to the fact that we are using conventional commits to automate the generation of the release notes.
> 
> The comment is about avoiding to squash the `build(deps)` commits so that their message is added to the release notes to track the dependency changes.

I mean i don't compare this pull request and don't know what's diffrence with mine. I think we should use p2-maven-plugin to manage third-party dependency management in the Eclipse RCP environment. You can check my repo heyoulin-kura branch https://github.com/spnettec/kura.git

**Comment by MMaiero** [comment]
@nicolatimeus Please check the sonar results

**Pull request merged**
