### PR TITLE
Identities UI fixes

### LINKED ISSUE #3223: "Menu" Button Showed When Window Resized, Although User has no Permissions
If you create a user without permissions, and login as thi user, there is still icon with three horizontal lines in top left that shows menu, when browser window is resized. The problem is that there is nothing to be displayed. Is this the desired behaviour? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add an identity
3. Add password to the identity, login as this user
4. Observe the menu button on top left when browser window is resized 

**Expected behavior**
Should "menu" button be displayed, if user has no permissions? 

**Screenshot:**
issue8

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

### PR DESCRIPTION
**Pull request by marcellorinaldo**
Brief description of the PR. Several fixes to the UI section named "Identities"

**Related Issue:** This PR fixes/closes #3223 #3257 #3220 #3222 #3219 #3228 #3221 #3224 #3227 #3241.

**Description of the solution adopted:** Besides the mentioned solved issues, this PR also solves the empty permissions user login error (if user with no permissions logins, then he will see a blank page), and password format restrictions not working (wrong regular expressions that are used to check passwords).

**Screenshots:** N/A.

**Any side note on the changes made:** N/A.

### CODE REVIEW

**Review by MMaiero — COMMENTED** [review]
Regarding #3223 it seems correct the fix when the page is with a limited size. When, instead, the page is large enough the logo of the product is hidden

**Comment by MMaiero** [comment]
Please also update the changed file copyrights to set 2021 as the end date

**Comment by marcellorinaldo** [comment]
> Regarding #3223 it seems correct the fix when the page is with a limited size. When, instead, the page is large enough the logo of the product is hidden

Corrected.

**Comment by marcellorinaldo** [comment]
> Please also update the changed file copyrights to set 2021 as the end date

Corrected.

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
