### PR TITLE
build: update docker build process, to reduce container compile time

### PR DESCRIPTION
**Pull request by GregoryIvo**
Modified docker build step to create a 'base' container containing compiled sources

2) added new distrib for ubi8, based on this base container.

3) added new distrib for alpine, based on the 'base' container.

 Basically, one compile, 2 containers. 

To build all containers the activation "buildAllContainers" can be used.
```mvn clean install -DbuildAllContainers```

Using this will build 3 Profiles:
 1) docker-x86_64-nn ```mvn clean install -Pdocker-x86_64-nn```
 2) docker-ubi8-x86_64-nn ```mvn clean install -Pdocker-ubi8-x86_64-nn```
 3) docker-alpine-x86_64-nn ```mvn clean install -Pdocker-alpine-x86_64-nn``
 
 
 **note:** With these changes ```mvn clean install -DbuildAll``` will no longer build the base docker container (docker-x86_64-nn)

**Related Issue:** 

**Description of the solution adopted:**

**Screenshots:** 

**Any side note on the changes made:**

### CODE REVIEW

**Comment by MMaiero** [comment]
@GregoryIvo I don't think that we are currently building the docker images using the Eclipse CI. Most likely the profiles need to be not enabled by default so that they can be selected for building separately from the rest of Kura. @nicolatimeus please correct me if I am wrong.
Also, I am not sure if other Eclipse projects are using the Eclipse CI to build their docker images. Maybe we should investigate

**Comment by GregoryIvo** [comment]
> @GregoryIvo I don't think that we are currently building the docker images using the Eclipse CI. Most likely the profiles need to be not enabled by default so that they can be selected for building separately from the rest of Kura. @nicolatimeus please correct me if I am wrong. Also, I am not sure if other Eclipse projects are using the Eclipse CI to build their docker images. Maybe we should investigate

Based on this comment, I will leave this branch as a WIP, and start a new branch just modifying the Standalone Dockerfiles, to use the builder for this sprint. 

Thoughts?

**Comment by MMaiero** [comment]
No, maybe you can play with maven and profiles so that the docker images profiles are not enabled by default

**Comment by GregoryIvo** [comment]
> No, maybe you can play with maven and profiles so that the docker images profiles are not enabled by default

Sounds like a good plan. Will do.

**Comment by GregoryIvo** [comment]
> No, maybe you can play with maven and profiles so that the docker images profiles are not enabled by default

Also important to ask. 

Are we happy with the the way this build system is set up? 

Having a "base image" that contains the bins from the mvn docker profile (copied from the system running mvn) Then using this base image to make customized installs? 

Basically 1 compile n variants of x86 images? 


Then later we can also add a base for other architects. So at a max we will have to compile at least once per different arch? 


Just Making sure I am on the right track with this.

**Comment by MMaiero** [comment]
@nicolatimeus @salvatore-coppola What are your thoughts here?

**Comment by GregoryIvo** [comment]
This is so close.  Having some weird issues with the Pom, where my docker Execs execute reliably.

Sometimes they are out of order, or sometimes they don't execute at all.

**Comment by MMaiero** [comment]
@salvatore-coppola Can you help @GregoryIvo on this?

**Comment by salvatore-coppola** [comment]
> @salvatore-coppola Can you help @GregoryIvo on this?

Yes, of course if the problem is still open

**Review by salvatore-coppola — APPROVED** [review]

**Comment by salvatore-coppola** [comment]
@GregoryIvo pls update the copyright header in https://github.com/eclipse/kura/blob/6ae02265449a846d09181bd355de473f338f7781/kura/distrib/pom.xml

**Comment by MMaiero** [comment]
@GregoryIvo Are we done with this PR?
Can we set it to ready for review?

**Comment by GregoryIvo** [comment]
@salvatore-coppola  do you think we can merge this?

Build issues seem to be un-related

**Comment by MMaiero** [comment]
Build and sonar pass. The error reported in the checks is mainly related to an IT issue already reported to Eclipse and where the Eclipse IT team is currently working.
Screenshot 2023-02-16 at 10 55 29

Proceeding with the merge as all the required checks are ok.

**Pull request merged**
