### PR TITLE
Implement new Cloud Client API

### PR DESCRIPTION
**Pull request by ctron**
This change implements the new cloud client API and adds a few fixes.

### CODE REVIEW

**Comment by MMaiero** [comment]
Could you please resolve conflicts with the apis? Could you also squash the commits? Thanks

**Comment by ctron** [comment]
@MMaiero Is it ready to merge then? I would keep the number of rebases for this PR to a minimum.

You can also squash the commit during the merge process. So there is no need to do this right now.

**Comment by MMaiero** [comment]
> Is it ready to merge then? I would keep the number of rebases for this PR to a minimum.

That was my purpose, and for that reason I've asked. 😄 

> You can also squash the commit during the merge process. So there is no need to do this right now.

I prefer if you do that because, being your commits, you know how to better squash them, so they are self-contained and separately make the build properly working.

**Comment by ctron** [comment]
Done

**Pull request merged**
