### PR TITLE
Refactoring Apache Camel XML router

### PR DESCRIPTION
**Pull request by ctron**
This change upgrades to Apache Camel 2.17.2 and does remove the
unnecessary workarounds for older Camel versions. Languages and
components get auto-detected by OSGi now.

Also are the Kura related CamelRouter classes being split up in:
* A basic Kura based Camel component
* A basic XML routes based component
* A basic XML routes component which gets configured as OSGi service
component
* A generic Kura component based on a single XML snippet with UI support

This change also fixes the "sun.misc" import issue in a way that the
bootdelegation is not required.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by cdealti** [comment]
@ctron thanks for the effort. It would be great if you could also address (and comment) the following github issues related to the Camel integration:

#221, #125, #200 

If you install the zebhub plugin for Chrome, filter by the ``kura-camel`` label and looking at the ``Backlog`` and ``Todo`` pipelines you should have a better picture of the status.

**Comment by ctron** [comment]
@cdealti I will have a look at those issues.

I am using Firefox. Is there an addon for it?

**Comment by ctron** [comment]
So checking all three issues, I think that #200 is fixed by this change, I would strongly recommend against #221 and #125 is an issue, not sure what causes it, I will dig into this. But then again it would be a bug fix on top of this change.

**Comment by ctron** [comment]
I just saw that #204 and #205 should be solved by this upgrade of camel as well.

**Comment by ctron** [comment]
I am closing this PR in favor of splitting it up into smaller ones.

**Pull request closed without merging**
