### PR TITLE
fix(setups): Fix oomph setup

### PR DESCRIPTION
**Pull request by salvatore-coppola**
Fix the oomph setup replacing m2e-tycho and eclemma repositories.

This eliminates the need to use older versions of Eclipse.

If merged the main README need an update

### CODE REVIEW

**Comment by MMaiero** [comment]
Did you find anything useful in terms of this issue? https://github.com/eclipse-tycho/tycho/issues/146
So that we are able to use the upstream repo instead of a generic fork?

**Comment by MMaiero** [comment]
Testing with the latest Eclipse it seems that we still have problems. Maybe I've missed something, but even after setting the target platform everything is marked as error:

image

**Comment by salvatore-coppola** [comment]
> Testing with the latest Eclipse it seems that we still have problems. Maybe I've missed something, but even after setting the target platform everything is marked as error:
> 
> image

I'll check.

**Comment by salvatore-coppola** [comment]
@MMaiero now everything should be fine

**Comment by GregoryIvo** [comment]
I just gave this a try on my system and I have encountered this:
image
and after setting the target platform:
image

**Comment by salvatore-coppola** [comment]
> I just gave this a try on my system and I have encountered this: image and after setting the target platform: image

very strange, on my system works without problem, let's check together later

**Comment by marcellorinaldo** [comment]
Works on my PC.

**Review by marcellorinaldo — APPROVED** [review]
Works on my setup. MacOS 13.4 x86, Java 1.8.

**Pull request merged**
