### PR TITLE
[#1952]: Process Designate as OSGi expects it

### PR DESCRIPTION
**Pull request by ctron**
This change uses either the PID or the factory PID. It doesn't require both anymore and also fixes the NPE.

### CODE REVIEW

**Comment by dwoodard1** [comment]
@MMaiero @cdealti Do you see any problems merging this into the v3.2.0 release? It doesn't appear that it should affect the existing behavior and will add support for BND tooling.

**Comment by nicolatimeus** [comment]
I've performed some tests and this does not seem to cause any obvious regression. @ctron if you retarget this PR to the `release-3.2.0` branch we can merge it and perform further testing during the QA phase.

**Comment by ctron** [comment]
@dwoodard1 @nicolatimeus So if that PR is good to go, I could simply merge it into release-3.2.0 and develop myself.

**Comment by nicolatimeus** [comment]
That's ok for me

**Comment by MMaiero** [comment]
@ctron When done, I'll start the milestone creation process.

**Comment by ctron** [comment]
Ok. Done.

**Comment by ctron** [comment]
Closing as this has been cherry-picked.

**Pull request closed without merging**
