### PR TITLE
#1911: Upgrade Artemis to 2.5.0

### PR DESCRIPTION
**Pull request by ctron**
**Note:** There are a bunch of CQs pending for this PR. Please do not merge before they have been approved:

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16131
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16132
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16133
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16134
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16135
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16136
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16137
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16138
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16139
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16140
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16141

### CODE REVIEW

**Comment by ctron** [comment]
I switched to using Netty 4.1.22, as we could piggy back on an existing CQ.

**Comment by ctron** [comment]
@dwoodard1 @cdealti @MMaiero We have checking permission for all CQs. Is it ok to merge this in?

**Comment by ctron** [comment]
Please note, the upgraded Netty version is also a pre-requiste for updating the Camel version. So this is also a blocker on the work of upgrading Camel.

**Comment by ctron** [comment]
As there are no objections, I will merge this tomorrow.

**Comment by MMaiero** [comment]
Agreed. Thanks for the effort.

**Comment by MMaiero** [comment]
@ctron Could you please have a look why, after this merge, the Hudson build fails?
Thanks

**Comment by ctron** [comment]
I don't think it does after the merge. It fails anyway as there is another commit after the merge which succeeded: 73121e9068406fb52ae470e2cf25571cb4cd9d97

**Comment by MMaiero** [comment]
I was looking that from this build: https://hudson.eclipse.org/kura/job/kura-develop/1357/ it is failing.
I believe this is due to the fact that the develop build caused by your PR pushed an artefact to the releases repo. Obviously, from that moment on, due to the repo policy it is not possible to push again final versions of an artefact.

**Comment by ctron** [comment]
Interesting .. as the original version for "2.1" was "2.1.0" … Which should have triggered the same issue. I will have a look at this.

**Comment by ctron** [comment]
I just created PR #2077 which should (still testing) fix this issue.

**Pull request merged**
