### PR TITLE
#779: Unit tests for EthernetInterfaceConfigImpl class

### PR DESCRIPTION
**Pull request by djurod**
- Prepared unit tests for EthernetInterfaceConfigImpl class from package
  org.eclipse.kura.core.net
- Fixed or implemented comparison of classes: AbstractNetInterface,
  EthernetInterfaceConfigImpl, and NetInterfaceAddressConfigImpl

Signed-off-by: Djuro Drljaca <djuro.drljaca@comtrade.com>

### CODE REVIEW

**Comment by djurod** [comment]
So there appears to be an issue with use of Java 1.8...

@cdealti @ctron any ideas how to solved this? According to @markoer one solution could be to change the compiler version in manifest_pom.xml, since apparently the next version of Kura will require minimal Java 1.8.

**Comment by cdealti** [comment]
@djurod I'd agree with @markoer

**Comment by ctron** [comment]
@djurod What problem is there?

**Comment by djurod** [comment]
I now resolved the merge conflict and rebased to upstream again. Hopefully if will now build, but since it doesn't appear that anything changed in the build system I would expect that the build will fail again. If it does I increase the compiler version in manifest_pom.xml from 1.6 to 1.8 and try again.

**Comment by ctron** [comment]
Can you explain what the problem is?

**Comment by djurod** [comment]
Build is failing because of use of java features that are not present in java 1.6 (see build log on Travis CI):

> ERROR] /home/travis/build/eclipse/kura/kura/test/org.eclipse.kura.core.net.test/src/test/java/org/eclipse/kura/core/net/EthernetInterfaceConfigImplTest.java:[294,104] diamond operator is not supported in -source 1.6
>
>  (use -source 7 or higher to enable diamond operator)

Manifest for the project is configured to use java 1.8, but for some reason build still fails. I don't see any reason why it should except maybe because the java compiler version is set to 1.6 in manifest_pom.xml...

**Comment by ctron** [comment]
I will look into this. For the moment just set source and target to 1.8.

**Comment by ctron** [comment]
I just gave it a try. And this is exactly what I mean. To me it looks like the "src/test/java" code is compiled with settings from the "maven-compiler-plugin" while the "src/main/java" code is compiled with the "tycho-compiler-plugin".

If you use the diamond operator in "src/main/java" it works for me.

Please don't mix those two constructs. This will cause problems more problems than it will solve.

**Comment by djurod** [comment]
With the latest commit the build no longer fails. Please review the changes.

**Comment by ctron** [comment]
And yet the original problem still exists.

If you do that, at least set all BREE of all bundles  to Java 8 as well.

**Comment by djurod** [comment]
I see these possibilities to solve this issue:
- Someone needs to create a new pull request that properly ports Kura to java 1.8 and I wait with this pull request until that is done.
- We merge this pull request (if there are no other issues with it) and require of all future pull requests to set the BREE of the changed bundles to java 1.8 (if it is not already). This could be checked during review phase.

Setting BREE to java 1.8 in all bundles inside this pull request does not make sense to me, as it is way out of context of what is being done here...

@cdealti could you also comment on this?

**Comment by ctron** [comment]
There is a third option: Use the tools as they were intended to be used and only create `.test` fragment/bundles for testing. Using tycho-surefire only.

**Comment by djurod** [comment]
@ctron your last comment probably fits into discussion regarding testing in issue #833. Should we first resolve that and then return to this?

**Comment by djurod** [comment]
With the last commit I added a few more tests for the EthernetInterfaceConfigImpl class and I added unit tests for NetInterfaceAddressConfigImpl.

**Pull request merged**
