### PR TITLE
correcting some minor typos

### PR DESCRIPTION
**Pull request by nizuliani**

### CODE REVIEW

**Comment by dwoodard1** [comment]
@nizuliani Thanks for the typo fixes. Any contributions to the Kura project have to follow the guidelines outlined here [1]. Specifically, you need to sign the CLA. Once done, we'll be happy to merge. Thanks again for contributing!

[1] https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Comment by nizuliani** [comment]
@dwoodard1 Thanks for the feedback. The request is now signed

**Comment by dwoodard1** [comment]
@nizuliani Since this is limited to documentation cleanup, I will merge the request. But if you plan to commit code in the future, which would be great, you need to sign the commit with your email address that you used to sign the Eclipse CLA. This is currently how the commit is signed:

Signed-off-by: Nicola Zuliani <nicolazuliani@MacBook-Air-di-Nicola.local>

**Comment by ctron** [comment]
@dwoodard1 please take care then of manually updating the IP log according to https://www.eclipse.org/projects/handbook/#ip-iplog

**Pull request merged**
