### PR TITLE
WiFi switching between Station and Access Point is unreliable

### PR DESCRIPTION
**Pull request by pierantoniomerlino**
This PR fixes the issue related to the switching between WiFi Station Mode and Access Point.
The isKernelModuleLoadedForMode method in LinuxNetworkUtil is implemented to check what driver is loaded by the kernel.
In WifiMonitorServiceImpl some lines are added to correctly update the current wifi status.

### CODE REVIEW

**Comment by MMaiero** [comment]
@pierantoniomerlino Could you squash the merge commits?

**Comment by pierantoniomerlino** [comment]
@MMaiero I squashed the commits.

**Comment by cdealti** [comment]
@pierantoniomerlino please amend the commit messages to conform to our guidelines

**Comment by pierantoniomerlino** [comment]
@cdealti Done. But you know what I think about this...

**Pull request merged**
