### PR TITLE
Applied a patch to identify a corner case where only separators where…

### LINKED ISSUE #2888: Where is The DNS Server List?
If user sets wlan0's status to "Enabled for WAN", the "DNS Servers" option gets enabled. If user hoovers above the field, it says: 
"List of DNS servers. New servers can be added by entering an address and clicking apply.
To remove a server, delete the address from the list and click apply". 
Is this list meant to be in the UI or on the device itself, and thereofre deletable only if user ssh's itself onto the device?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> TCP/IP
3. Set Status to "Enabled for WAN"
4. Hoover above the DNS Servers and observe the description of the field on the right

**Expected behavior**
Should there be a list of DNS servers in the UI?

**Screenshot:**
Screenshot 2020-05-20 at 09 48 51

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

### PR DESCRIPTION
**Pull request by MMaiero**
… provided

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2888

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this PR and it looks ok, I only have one comment. 
If user enters DNS addresses in form "1.2.3.4      ;;;;;;;;;;;;       1.2.3.4" they are sorted out after clickng "Apply" button. 
But if user uses commas instead of semicolons (e.g. "1.2.3.4,            1.2.3.4,                     1.2.3.4,1.2.3.4"), then the addresses do not get lined up as in previous case (see screenshot bellow). 
Screenshot 2020-07-03 at 13 54 35

This is not a critical issue but rather a UI flaw, that does not affect the functionality - so I think we can merge this. 
What do you think? Should we leave it like this?

**Comment by MMaiero** [comment]
No idea on what happened, but this is what I see inserting 1.2.3.4, 1.2.3.4, 1.2.3.4,1.2.3.4 and after applying

Screenshot 2020-07-03 at 15 43 48

**Comment by LeoNerdoG** [comment]
Which browser and what version are you using? I am not able to replicate your behaviour.

**Comment by MMaiero** [comment]
Chrome for Mac. If it has not updated itself in the meantime, the version is 83.0.4103.116

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I can't replicate your outcome, i get: 
Screenshot 2020-07-06 at 10 43 07

if I enter the IP addresses in this fassion in the DNS field. This is from Chrome, its version is the same as yours. 
The same happens on Firefox.

**Comment by MMaiero** [comment]
Don't know Leonardo. I just rebuilt everything from scratch and made again the test with "1.2.3.4, 1.2.3.4, 1.2.3.4,1.2.3.4" and I get the same result as before with the addresses correctly parsed.

**Comment by LeoNerdoG** [comment]
Ok cool, I will retest it and ask @mstankovic for help. If you two wont be able to reproduce it, then we can close it.

**Comment by mstankovic** [comment]
hey @LeoNerdoG , Im not able to reproduce this issue. Im getting the same results as @MMaiero 

Capture

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this again and found out that if user changes views, e.g. to "wlan0" if the changes are made on "eth0", then the list is in form as expected. So the question here is just why does the list not get parsed after clicking apply, but rather when the view is changed.
Nevertheless, it seems that this is not a critical issue and you guys with @mstankovic are not experiecning it, so i think this can be merged. 

@mstankovic thanks for your input and help!

**Comment by MMaiero** [comment]
I believe it's a matter of refresh. I believe we can improve on that, but for now I believe we can move on. What do you think?

**Comment by LeoNerdoG** [comment]
Yes, I think we can go ahead with the merge.

**Pull request merged**
