### PR TITLE
Fixed paho websockets issue including a patched version of paho.

### PR DESCRIPTION
**Pull request by MMaiero**
Not updated the target-platform version due to the fact that the dependency set there is just to
build the target-definition and not used in distributions.

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
Closes #2412

**Review by markoer — COMMENTED** [review]
The only difference now is that it takes ~2.5 minutes for the client to disconnect.

```
2019-04-02T13:46:35,952 [qtp7557361-113] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connected!
2019-04-02T13:46:35,953 [qtp7557361-113] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2019-04-02T13:46:35,953 [pool-17-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2019-04-02T13:46:35,953 [qtp7557361-113] INFO  o.e.k.c.d.DataServiceImpl - Notified connected
2019-04-02T13:46:35,954 [pool-17-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED on
2019-04-02T13:46:35,954 [qtp7557361-113] INFO  o.e.k.c.d.DataServiceImpl - New session established. Unpublishing all in-flight messages. Disregarding the QoS level, this may cause duplicate messages.
2019-04-02T13:46:36,314 [qtp7557361-113] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: $EDC/#account-name/#client-id/MQTT/BIRTH, priority: 0
2019-04-02T13:46:36,352 [qtp7557361-113] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: $EDC/#account-name/#client-id/MQTT/BIRTH, priority: 0
2019-04-02T13:46:36,375 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: $EDC/.../B8:27:EB:33:A7:1A/MQTT/BIRTH with QoS: 0
2019-04-02T13:46:36,402 [qtp7557361-113] INFO  o.e.k.c.d.t.m.MqttDataTransport - Subscribing to topic: $EDC/.../B8:27:EB:33:A7:1A/# with QoS: 1
2019-04-02T13:46:36,598 [qtp7557361-113] INFO  o.e.k.c.d.t.m.MqttDataTransport - Subscribing to topic: .../B8:27:EB:33:A7:1A/W1/A1/# with QoS: 0
...
2019-04-02T13:49:17,267 [MQTT Ping: B8:27:EB:33:A7:1A] WARN  o.e.k.c.d.t.m.MqttDataTransport - Connection Lost
Timed out waiting for a response from the server (32000)
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:741)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:816)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:802)
        at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:79)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2019-04-02T13:49:17,269 [MQTT Ping: B8:27:EB:33:A7:1A] INFO  o.e.k.c.d.DataServiceImpl - connectionLost
```

**Comment by MMaiero** [comment]
Is that consistently reproducible?
Was that also the case for 4.0.0?

If not, probably we need to open another bug...

**Comment by MMaiero** [comment]
In my Raspberry, after 10 minutes, the connection never dropped

**Comment by markoer** [comment]
The issue didn't appear in 4.0.0 release.
I reproduced it twice with the updated Paho - with an updated core bundle on an existing installation. I now reinstalled and updated the bundle and I cannot reproduce it any longer. So I guess you actually can merge it.

**Pull request merged**
