### PR TITLE
Upgrade to Camel 2.21.1

### LINKED ISSUE #208: Include camel-amqp component jar in base distribution

### PR DESCRIPTION
**Pull request by ctron**
This PR upgrades Camel to version 2.21.1 (#2057). It also fixes #208 and adds some Wires integration with Camel.

**Note:** Do not merge this PR unless all CQs of #2057 are approved.

### CODE REVIEW

**Comment by MMaiero** [comment]
From a fast look, it seems to be ok.
After the merge of Benjamin's PR, the manifest in wire.camel needs to be updated in this way: `org.eclipse.kura.wire;version="[1.1,1.2)",`.
It would be interesting to associate the PR with an update of the documentation with some examples of usage of Camel in association with Wires.

**Comment by ctron** [comment]
Yes I know that Benjamin's PR did introduce a problem with this one. But I have the fixes prepared and can cherry-pick them on this branch now that his PR is merged.

> It would be interesting to associate the PR with an update of the documentation with some examples of usage of Camel in association with Wires.

Yes, sounds liks a good idea. I will do that.

**Comment by ctron** [comment]
As there only one CQ left for this PR, is there anything to do on this PR (aside from the documentation) or can this PR be merged once the CQ is approved?

**Comment by MMaiero** [comment]
For me it's ok to merge

**Comment by ctron** [comment]
The last of the CQs has been approved. As @MMaiero was fine with the PR, I will re-base and then merge the PR today.

**Pull request merged**
