### PR TITLE
feat: Limit the UI certificate add to a single PEM cert

### PR DESCRIPTION
**Pull request by MMaiero**
Tested in raspberry PI

### CODE REVIEW

**Comment by salvatore-coppola** [comment]
@MMaiero we need to add the japanase translation for the new strings added on message.properties

**Comment by MMaiero** [comment]
> @MMaiero we need to add the japanase translation for the new strings added on message.properties

@marcellorinaldo how do you usually manage this?

**Comment by marcellorinaldo** [comment]
> > @MMaiero we need to add the japanase translation for the new strings added on message.properties
> 
> @marcellorinaldo how do you usually manage this?

Google translate usually works fine. We then ask a japanese collegue if the translation is OK.

**Review by salvatore-coppola — APPROVED** [review]

**Comment by MMaiero** [comment]
Reviewed by Yuki san

**Comment by MMaiero** [comment]
Forcing merge.
The build succeeds locally but we are facing an issue in the CI connection to Sonar. An issue has been raised few weeks ago to the Eclipse Team: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4422

**Pull request merged**
