### PR TITLE
Added support for container registry auth

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: Maiero <matteo.maiero@eurotech.com>

@nicolatimeus @GregoryIvo Can you please have a look?

### CODE REVIEW

**Comment by GregoryIvo** [comment]
`2022-03-17T17:14:46,236 [pool-27-thread-1] ERROR o.e.k.c.p.ContainerInstance - Error managing microservice state
org.eclipse.kura.KuraException: Generic Error - IO_ERROR: {1}
	at org.eclipse.kura.container.orchestration.provider.impl.ContainerOrchestrationServiceImpl.pullImage(ContainerOrchestrationServiceImpl.java:344)
	at org.eclipse.kura.container.orchestration.provider.impl.ContainerOrchestrationServiceImpl.startContainer(ContainerOrchestrationServiceImpl.java:296)
	at org.eclipse.kura.container.provider.ContainerInstance$Starting.startMicroservice(ContainerInstance.java:249)
	at org.eclipse.kura.container.provider.ContainerInstance$Starting.lambda$0(ContainerInstance.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-17T17:14:46,237 [pool-27-thread-1] INFO  o.e.k.c.p.ContainerInstance - Tentative number: 1
2022-03-17T17:14:46,697 [qtp1220121931-153] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1647537286204.xml... Done.
2022-03-17T17:14:46,699 [qtp1220121931-153] INFO  o.e.k.c.c.ConfigurationServiceImpl - Snapshots Garbage Collector. Deleted /opt/eclipse/kura/user/snapshots/snapshot_1647536785152.xml`

image


Getting this same result with docker hub and AWS

**Comment by MMaiero** [comment]
Is this with an authenticated repo or just plain docker hub?

**Comment by MMaiero** [comment]
Sorry, I've seen later on the image

**Comment by GregoryIvo** [comment]
> Is this with an authenticated repo or just plain docker hub?

Authenticated docker hub. and after doing some more tests, it looks like unauthenticated ones are not working either.

**Comment by GregoryIvo** [comment]
Looks like everything works!
1) unauthenticated containers from docker hub
2) authenticated containers from docker hub
3) authenticated container from was

image

**Review by GregoryIvo — APPROVED** [review]

**Review by GregoryIvo — APPROVED** [review]

**Pull request merged**
