### PR TITLE
Added support for aarch64 arch

### PR DESCRIPTION
**Pull request by feclare**
Added new octeontx target, using aarch64(arm 64 bits)
Added aarch64 native libraries for:
org.eclipse.kura.linux.usb
com.codeminders.hidapi
jdk-dio
org.eclipse.soda.dk.comm

Update usb version in kura.build.properties

Signed-off-by: Federico Claramonte <fede.claramonte@caviumnetworks.com>

### CODE REVIEW

**Comment by feclare** [comment]
I run this command in my computer to solve the same problem travis ci is having with the compilation.
mvn install:install-file -DgroupId=org.eclipse.kura -DartifactId=org.eclipse.kura.linux.usb.aarch64 -Dversion=1.0.100 -Dpackaging=jar -Dfile=kura/org.eclipse.kura.linux.usb.aarch64/target/org.eclipse.kura.linux.usb.aarch64-1.0.200-SNAPSHOT.jar

**Comment by MMaiero** [comment]
Hi, 
first of all, thank you for the contribution.
I think that, to solve your issue, you'll need to update the version of org.eclipse.kura.linux.usb, in kura.build.properties, to 1.0.200-SNAPSHOT.

Best regards,
Matteo

**Comment by feclare** [comment]
Hi Matteo,
The change of the linux.usb version was missing in the first pull request, but I fixed it in this one.  But it still needs the mvn install:install-file command. 

Regards,
Fede

**Comment by feclare** [comment]
Hi Matteo,

There are also hidapi, jdk-dio and soda also needed the SNAPSHOT in the version string.
I will create a new pull request with this fixed.

Thanks for the help,
Fede

**Pull request closed without merging**
