### PR TITLE
Fix username displayed null in WebUI Device Status.

### PR DESCRIPTION
**Pull request by pierrepitiot**
This PR solves issue #296 and replace PR #349 .

### CODE REVIEW

**Comment by MMaiero** [comment]
@pierrepitiot Why we are not doing the same check also for getBrokerUrl()?

**Comment by pierrepitiot** [comment]
Because the other fields can be empty but there is a check on broker URL that prohibits an empty value (you cannot apply it). Do you think we should check it also?

**Comment by MMaiero** [comment]
I would do it, just to keep consistency: the empty value check is performed by the web ui, but a third party app can rely on mqttdatatransport and get null value, if someone programmatically set it

**Comment by pierrepitiot** [comment]
Ok I will fix it.

**Pull request merged**
