### PR TITLE
Bump Kura API bundle version

### PR DESCRIPTION
**Pull request by cdealti**
Signed-off-by: Cristiano De Alti <cristiano.dealti@eurotech.com>

### CODE REVIEW

**Comment by ctron** [comment]
This would also mean that we bump the version on  `develop` to 1.2.0 in addition.

**Comment by cdealti** [comment]
It should be caught by #685 if it's merged and when release-2.1.0 is merged on develop

**Comment by ctron** [comment]
We had to increment the kura.api bundle on develop to 1.1.0 in order to fix build errors. Now it release gets incremented  to 1.1.0 as well, we will again have an issue on the develop branch. And this we need to increment the version to 1.2.0.

**Comment by cdealti** [comment]
@ctron please do that on develop.

@MMaiero please merge this.

**Pull request merged**
