### PR TITLE
Added base Camel jars

### PR DESCRIPTION
**Pull request by hekonsek**
This time applied to a proper branch and with signed commit.

Signed-off-by: Henryk Konsek <hekonsek@gmail.com>

### CODE REVIEW

**Comment by hekonsek** [comment]
This is clean pull request for issue #69.

**Comment by cdealti** [comment]
Hi Henryk, can you squash the last two commits into one (too many changes)?

Can you also squash the first two in a single one?

**Comment by kartben** [comment]
@cdealti @dwoodard1  please make sure you open CQs for the Camel libs :-)

**Comment by cdealti** [comment]
@kartben sure. Thanks!

**Comment by hekonsek** [comment]
I have squashed all commits into one. Can we proceed with merge or do we have to wait for CQ to pass before?

**Comment by cdealti** [comment]
@hekonsek Thanks. We have to open the CQs. Let us discuss the best strategy internally

**Comment by kartben** [comment]
@cdealti 

> Let us discuss the best strategy internally

I think you mean on the Kura mailing list? ;-)

**Comment by dwoodard1** [comment]
CQs for this pull request have been filed:

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10810
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10811
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10812

**Comment by hekonsek** [comment]
Many thanks, Dave!

**Comment by cdealti** [comment]
All CQs have been approved. I believe this can be merged.

**Comment by hekonsek** [comment]
Awesome! Let me know if you need anything from me.

**Comment by dwoodard1** [comment]
Hi Henryk,

The merge has a conflict. Let me know if you want to modify the PR or I can merge manually. 

Thanks,
--Dave

**Comment by hekonsek** [comment]
Hi Dave. If merging manually is not a big problem for you, I'd highly appreciate it. Otherwise I can handle it myself.

It's up to you :) .

**Comment by dwoodard1** [comment]
The pull request has been manually merged.

https://github.com/eclipse/kura/commit/06dd9c232682d0c5aa7d668d6593be355ee7bc4e

--Dave

**Comment by hekonsek** [comment]
Many thanks, David!

**Pull request closed without merging**
