### PR TITLE
Added contributing page

### PR DESCRIPTION
**Pull request by salvatore-coppola**
Added contributing page

### CODE REVIEW

**Comment by GregoryIvo** [comment]
What if we add a line like this:

Instructions to set up a Kura development environment on your machine: https://github.com/eclipse/kura#development-environment

**Comment by GregoryIvo** [comment]
Assuming that your change will add a new tab on the gh-pages doc?

**Comment by salvatore-coppola** [comment]
> 
> 
> Assuming that your change will add a new tab on the gh-pages doc?

yes a new menu item named Contributing will be added.

**Comment by GregoryIvo** [comment]
Maybe even also add?:

Feel free to reach out for any questions at your community Gitter: https://gitter.im/eclipse/kura

**Comment by salvatore-coppola** [comment]
> 
> 
> What if we add a line like this:
> 
> Instructions to set up a Kura development environment on your machine: https://github.com/eclipse/kura#development-environment

Mmm that instructions are already linked here: https://eclipse.github.io/kura/dev/kura-setup.html

**Comment by salvatore-coppola** [comment]
> 
> 
> Maybe even also add?:
> 
> Feel free to reach out for any questions at your community Gitter: https://gitter.im/eclipse/kura

Sure, we can also add a link to our support forum. https://www.eclipse.org/forums/index.php/f/273/ 

Do yo want to make the changes ?

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
