### PR TITLE
Asset blinking feature seems not to work

### PR DESCRIPTION
**Pull request by spnettec**
see #2585

### CODE REVIEW

**Comment by MMaiero** [comment]
Hi @spnettec to make things more clear and self contained, could rebase this PR to contain just the fix for Issue #2585?

Thanks

**Comment by spnettec** [comment]
> Hi @spnettec to make things more clear and self contained, could rebase this PR to contain just the fix for Issue #2585?
> 
> Thanks

Done

**Comment by MMaiero** [comment]
thank you but is it just me or I still see the commit for the console path change?

**Comment by spnettec** [comment]
> thank you but is it just me or I still see the commit for the console path change?

To make things more clear I'll recreate a new PR for this.

**Pull request closed without merging**
