### PR TITLE
Upgrade to Camel 2.17.2

### PR DESCRIPTION
**Pull request by ctron**
This change will upgrade dependencies to Apache Camel 2.17.2 and will
remove code which was required in versions of Camel before 2.17.0.

In addition it will add the "camel-stream" module for easier testing.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

---

**Note:** This PR requires updated CQs for the final release on Camel and a new CQ for "camel-stream"

### CODE REVIEW

**Comment by cdealti** [comment]
@hekonsek can you please create the needed CQs ASAP? It might take some time before they are approved. In the meantime this PR will be kept on hold.

**Comment by hekonsek** [comment]
@ctron Jens, Have you created CQ for the jars we need?

**Comment by ctron** [comment]
No, I can't do that since I am not a committer on the project.

**Comment by hekonsek** [comment]
I have created the following CQs:
- Camel Core - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11774
- Camel OSGI - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11775
- Camel Kura - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11776
- Camel Stream - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11777

Jens, can you +1 them? :)

**Comment by ctron** [comment]
Done.

**Comment by cdealti** [comment]
Please do not merge this yet. The next Kura 2.0.1 release will be a service release.

**Comment by ctron** [comment]
All Camel 2.17.2 CQs are approved.

@cdealti  Can this be merged now?

**Comment by cdealti** [comment]
@ctron we have created the release-2.0.1 branch.
Please coordinate with @dwoodard1 for the merges on develop next week.

**Comment by ctron** [comment]
:+1:

**Pull request merged**
