### PR TITLE
fix(web2): Replaced marketplace url with the updated https url (avoiding redirect). Updated Eclipse Marketplace certificate in the keystore..

### PR DESCRIPTION
**Pull request by salvatore-coppola**
Replaced marketplace url with the updated https url (avoiding redirect). 
Updated Eclipse Marketplace certificate in the keystore..

### CODE REVIEW

**Comment by salvatore-coppola** [comment]
Need to add the support for the sslmanagerservice. DO NOT MERGE

**Comment by nicolatimeus** [comment]
Please also add a configuration option to customize the sslmanagerservice target, otherwise we will pick a random one

**Comment by salvatore-coppola** [comment]
> Please also add a configuration option to customize the sslmanagerservice target, otherwise we will pick a random one

I forgot that we can have more than one

**Review by mattdibi — CHANGES_REQUESTED** [review]
Not working for me right now.

I tried installing the "[Wires Script Filter for Kura 4/5](https://marketplace.eclipse.org/content/wires-script-filter-kura-45)" using the drag and drop but received an error.

```
2023-04-07T13:46:47,653 [pool-9-thread-1] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1680871607602.xml...
2023-04-07T13:46:47,670 [pool-9-thread-1] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1680871607602.xml... Done.
2023-04-07T13:46:50,463 [qtp1924205267-1099] INFO  o.e.j.s.h.C.ROOT - org.eclipse.kura.web.server.GwtPackageServiceImpl: Trying /www/denali/944BA50707ED33E8E951724BD969931E.gwt.rpc
2023-04-07T13:47:05,257 [qtp1924205267-1099] INFO  o.e.k.c.s.SslManagerServiceImpl - Creating a new SSLSocketFactory instance
2023-04-07T13:47:05,265 [qtp1924205267-1099] WARN  o.e.k.w.s.GwtPackageServiceImpl - failed to get deployment package descriptior from Eclipse Marketplace
java.io.IOException: org.eclipse.kura.KuraException: Bad request. Failed to get the KeyStore
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getTrustManagers(SslManagerServiceImpl.java:399)
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getSSLContextInternal(SslManagerServiceImpl.java:342)
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getSSLContext(SslManagerServiceImpl.java:229)
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getSSLContext(SslManagerServiceImpl.java:208)
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getSSLContext(SslManagerServiceImpl.java:199)
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getSSLSocketFactory(SslManagerServiceImpl.java:234)
	at org.eclipse.kura.web.server.GwtPackageServiceImpl.getMarketplacePackageDescriptor(GwtPackageServiceImpl.java:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.processCall(OsgiRemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1459)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:159)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:67)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.dispatch(ProxyServlet.java:147)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.preprocess(ProxyServlet.java:115)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:305)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.kura.KuraException: Bad request. Failed to get the KeyStore
	at org.eclipse.kura.core.keystore.FilesystemKeystoreServiceImpl$KeystoreLoader.loadKeystore(FilesystemKeystoreServiceImpl.java:369)
	at org.eclipse.kura.core.keystore.FilesystemKeystoreServiceImpl.loadKeystore(FilesystemKeystoreServiceImpl.java:325)
	at org.eclipse.kura.core.keystore.FilesystemKeystoreServiceImpl.loadKeystore(FilesystemKeystoreServiceImpl.java:158)
	at org.eclipse.kura.core.keystore.BaseKeystoreService.getKeyStore(BaseKeystoreService.java:123)
	at org.eclipse.kura.core.ssl.SslManagerServiceImpl.getTrustManagers(SslManagerServiceImpl.java:394)
	... 64 more
```

See also:


https://user-images.githubusercontent.com/22748355/230611692-94e176c8-785c-4e73-94dc-a028777652f8.mov

**Comment by salvatore-coppola** [comment]
@mattdibi tested successfully on docker alpine container

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
