### PR TITLE
Clean up the build process - Part 1

### PR DESCRIPTION
**Pull request by ctron**
This change does:
- Download dependencies from official locations
- Create the final version map for "distrib" from actual OSGi BSN + Version
- Allow the use of source bundles
- Build P2 features and repository
- Remove the old web(1) bundle
- Create DP packages using a Maven plugin

### CODE REVIEW

**Comment by cdealti** [comment]
@ctron I've just started taking a look to this (OK, I'm cloning your fork ;).
I've noticed that this PR comes from your Kura fork. This probably happens because you started the feature before your election to Kura committer.

Some time ago @dwoodard1 asked @kartben if this model (which we prefer over creating gazillions of PR branches on the upstream Kura repo) is acceptable/encouraged.

What are your thoughts on this?

**Comment by cdealti** [comment]
I've not been able to build the target platform.
I usually get socket timeouts. It also looks like that downloading a jar can block for a while.

```
build:
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
      [get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.net_3.1.0.v201205071737.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.net_3.1.0.v201205071737.jar
      [get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.net.source_3.1.0.v201205071737.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.net_3.1.0.v201205071737.jar
      [get] Not modified - so not downloaded
      [get] Getting: http://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.6.0/protobuf-java-2.6.0.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/protobuf-java-2.6.0.jar
      [get] Getting: http://repo1.maven.org/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.0.2/org.eclipse.paho.client.mqttv3-1.0.2.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.eclipse.paho.client.mqttv3-1.0.2.jar
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
      [get] Getting: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/slf4j-api-1.6.4.jar
      [get] Getting: http://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.6.4/slf4j-jdk14-1.6.4.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/slf4j-jdk14-1.6.4.jar
      [get] Getting: http://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.0/slf4j-log4j12-1.6.0.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/slf4j-log4j12-1.6.0.jar
      [get] Getting: http://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/log4j-1.2.17.jar
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
      [get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.fileupload_1.2.2.v20111214-1400.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.fileupload_1.2.2.v20111214-1400.jar
      [get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.fileupload.source_1.2.2.v20111214-1400.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.fileupload_1.2.2.v20111214-1400.jar
      [get] Error getting http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.fileupload.source_1.2.2.v20111214-1400.jar to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.fileupload_1.2.2.v20111214-1400.jar
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
      [get] Getting: http://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/commons-io-2.4.jar
      [get] Getting: http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/commons-lang3-3.4.jar
      [get] Getting: http://repo1.maven.org/maven2/org/apache/camel/camel-core/2.17.2/camel-core-2.17.2.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/camel-core-2.17.2.jar
      [get] Getting: http://repo1.maven.org/maven2/org/apache/camel/camel-core-osgi/2.17.2/camel-core-osgi-2.17.2.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/camel-core-osgi-2.17.2.jar
      [get] Getting: http://repo1.maven.org/maven2/org/apache/camel/camel-kura/2.17.2/camel-kura-2.17.2.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/camel-kura-2.17.2.jar
      [get] Getting: http://repo1.maven.org/maven2/org/apache/camel/camel-stream/2.17.2/camel-stream-2.17.2.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/camel-stream-2.17.2.jar
      [get] Getting: http://repo1.maven.org/maven2/org/hsqldb/hsqldb/2.3.0/hsqldb-2.3.0.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/hsqldb-2.3.0.jar
      [get] Getting: http://repo1.maven.org/maven2/org/hsqldb/hsqldb/2.3.0/hsqldb-2.3.0.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/hsqldb-2.3.0.jar
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
      [get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.json_1.0.0.v201011060100.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.json_1.0.0.v201011060100.jar
      [get] Error getting http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.json_1.0.0.v201011060100.jar to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.json_1.0.0.v201011060100.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Camel :: Core :: Import sun.misc .................. SUCCESS [3.845s]
[INFO] System extension fragment for 'sun.misc' .......... SUCCESS [0.425s]
[INFO] target-platform ................................... SUCCESS [0.005s]
[INFO] Java API for working with Human Interface USB Devices (HID)  SUCCESS [3.637s]
[INFO] usb4java .......................................... SUCCESS [0.696s]
[INFO] usb4java-javax .................................... SUCCESS [0.448s]
[INFO] Serial Device based on SODA DK comm ............... SUCCESS [0.859s]
[INFO] gwt-user .......................................... SUCCESS [4.561s]
[INFO] p2-repos .......................................... SUCCESS [0.005s]
[INFO] common ............................................ FAILURE [2:47.634s]
[INFO] equinox_3.8.1 ..................................... SKIPPED
[INFO] manifest .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:03.616s
[INFO] Finished at: Tue Aug 30 10:05:21 CEST 2016
[INFO] Final Memory: 27M/482M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (download) on project common: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/build-p2.ant:52: The following error occurred while executing this line:
[ERROR] /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/lib.ant:77: The following error occurred while executing this line:
[ERROR] /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/lib.ant:43: java.net.ConnectException: Connection timed out
[ERROR] around Ant part ...<ant antfile="build-p2.ant"/>... @ 4:32 in /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common
```

**Comment by ctron** [comment]
Not sure what could be wrong on your end. It works fine for me and on the Travis CI environment.

**Comment by ctron** [comment]
Regarding the fork. I am working on my fork of Kura which I update from eclipse/kura every now and then. Once the change is complete I issue the PR. The feature branch can be deleted after the PR is merged. I don't see anything wrong with that since the Eclipse IP check is still triggered.

**Comment by ctron** [comment]
Btw you can set the env-var `KURA_BUILD_CACHE=/tmp/kura.build` during the build in order to locally cache downloaded artifacts. This should speed up the build process if you have a slow internet connection. However you need to ensure that downloaded artifacts are intact.

**Comment by cdealti** [comment]
I don't see anything wrong either. @kartben: @dwoodard1 sent you an email one month ago or something rising this concern. Can you please check and give feedback?

**Comment by cdealti** [comment]
About building the target platform, it can succeed or fail. Apparently I don't have network issue on my side when it fails.
It might get stuck for minutes downloading the JSON bundle or the eclipse SDK zip (which is large).

**Comment by ctron** [comment]
The last build came through fine: https://travis-ci.org/eclipse/kura/builds/154704902 and I just build it through three times myself in the last few hours since I needed a Java 8 capable version of Kura.

Did you try the caching option?

**Comment by cdealti** [comment]
Still timeout fetching the target platform:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building common 2.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ common ---
[INFO] Deleting /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (download) @ common ---
[INFO] Executing tasks

main:

init:
    [mkdir] Created dir: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/download
    [mkdir] Created dir: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/unpack
    [mkdir] Created dir: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
     [echo] ${env.KURA_BUILD_CACHE}

build:
     [copy] Copying 1 file to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins
      [get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.net_3.1.0.v201205071737.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.net_3.1.0.v201205071737.jar
      [get] Error getting http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.apache.commons.net_3.1.0.v201205071737.jar to /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.apache.commons.net_3.1.0.v201205071737.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Camel :: Core :: Import sun.misc ................... SUCCESS [  7.417 s]
[INFO] System extension fragment for 'sun.misc' ........... SUCCESS [  0.340 s]
[INFO] target-platform .................................... SUCCESS [  0.056 s]
[INFO] Java API for working with Human Interface USB Devices (HID) SUCCESS [  6.357 s]
[INFO] usb4java ........................................... SUCCESS [  1.287 s]
[INFO] usb4java-javax ..................................... SUCCESS [  0.916 s]
[INFO] Serial Device based on SODA DK comm ................ SUCCESS [  1.311 s]
[INFO] gwt-user ........................................... SUCCESS [  5.469 s]
[INFO] p2-repos ........................................... SUCCESS [  0.217 s]
[INFO] common ............................................. FAILURE [01:05 min]
[INFO] equinox_3.8.1 ...................................... SKIPPED
[INFO] manifest ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:31 min
[INFO] Finished at: 2016-09-13T10:09:58+02:00
[INFO] Final Memory: 29M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (download) on project common: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/build-p2.ant:13: The following error occurred while executing this line:
[ERROR] /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/lib.ant:77: The following error occurred while executing this line:
[ERROR] /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/lib.ant:43: java.net.ConnectException: Connection timed out
[ERROR] around Ant part ...<ant antfile="build-p2.ant"/>... @ 4:32 in /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common
```

**Comment by ctron** [comment]
Can you try to download the URL with a browser?

**Comment by cdealti** [comment]
The build is stuck now on:

```
[get] Getting: http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/plugins/org.json_1.0.0.v201011060100.jar
      [get] To: /home/cristiano/dev/git/ctron/kura/target-platform/p2-repos/common/target/source/plugins/org.json_1.0.0.v201011060100.jar
```

It has been in this state for half an our or so.

But I can download it from a browser.

**Comment by ctron** [comment]
So I don't know what is wrong then. I will let travis re-test once again to see if they have any issues.

Are you using any proxy?

**Comment by cdealti** [comment]
No but I use a wireless connection. However I haven't ever experienced download problems of any sort on this connection. Now I've restarted the third build setting the env var ``KURA_BUILD_CACHE=/tmp/kura.build``
This build eventually succeeded

**Comment by cdealti** [comment]
@ctron one silly question. Does this PR provide support to publish the Kura target platform p2 repo (I mean to some remote repo)? If so can you point me to the relevant pom file?

**Comment by ctron** [comment]
Yes, but the final repository does not contain everything. It was only for assembling the DP packages based on Eclipse Features.

So check out the "features" projects and the "org.eclipse.kura-p2" module.

**Comment by ctron** [comment]
Btw, travis build is fine.

**Comment by cdealti** [comment]
OK, I'll try to explain my understanding of the new build.

# target-platform project
Uses official "locations" for the Kura target platform bundles:
1. [Eclipse Orbit](http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/)
2. Maven Central
3. [Equinox 3.8.1](http://archive.eclipse.org/equinox/drops/R-3.8.1-201209141800)

* The build seems to honor the versions in target-platform/config/download.version.properties,
at least for the common bundles. The name of some .version properties has changed and it's likely (but I need to check) that this breaks the build of dependent projects, e.g. ESF.

* The target-platform build is heavily based on ANT. I've experienced download issues due to timeouts of stuck downloads.

* To prevent downloading the files every time, the build can use a cache:
```
export KURA_BUILD_CACHE=/tmp/kura.build; mvn clean install
```

* Create the final version map for "distrib" from actual OSGi BSN + Version. @ctron **does this mean that the jar file names that will be copied in the installers and in the config.ini have changed compared to the current build?**

* The local p2 repos are still assembled for the Tycho build as before.

# kura project

* The ``org.eclipse.kura.web2`` project is now built manifest-first (i.e. by ``manifest_pom.xm``). This is good because I've never understood why it was pom-first and its pom was a mess.

* New projects for building features in the ``features`` directory:
  * org.eclipse.kura.protocol.can.feature
  * org.eclipse.kura.protocol.modbus.feature
  * org.eclipse.kura.runtime.common.feature
  * org.eclipse.kura.runtime.equinox_3.8.1.feature
  * org.eclipse.kura.web.feature

* A new ``org.eclipse.kura-p2`` project for building the Kura p2 repository aggregating all the features above but the ``org.eclipse.kura.protocol.can.feature``. **Question:** when deployed on Nexus, is this p2 repo immediately consumable? 

* Create DP packages using a Maven plugin (**I still need to understand the details**)

* Java 8 is needed for the maven build
* It requires maven > 3.3 otherwise:
   ``Failed to execute goal de.dentrassi.maven:osgi-dp:0.0.3:build (default) on project org.eclipse.kura.protocol.modbus: The plugin de.dentrassi.maven:osgi-dp:0.0.3 requires Maven version 3.3 -> [Help 1]``. As a note the dependent ESF build does not work with Maven 3.3.

**Comment by ctron** [comment]
IIRC the JAR file names should be made up from the BSN + version. If that means a change from the existing names, then yes. This would be a change.

I don't know how nexus handles P2. So I cannot tell.

Actually you can just write `KURA_BUILD_CACHE=/tmp/kura.build mvn clean install`, so you only set this for this one call.

**Comment by ctron** [comment]
Beside the fact that Kura dependency still are downloaded from some mirrored locations I think most of the other changes are finally in Kura 3.0.0.

**Pull request closed without merging**
