### PR TITLE
Fixed potential ArrayIndexOutOfBoundsException in IBeacon decoder

### LINKED ISSUE #1863: IBeacon decoder index out of bounds
If by any chance this check:

https://github.com/eclipse/kura/blob/961029abd4c86aa6c738f2b2aaf733d1c3bdedbc/kura/org.eclipse.kura.ble.ibeacon.provider/src/main/java/org/eclipse/kura/internal/ble/ibeacon/BluetoothLeIBeaconDecoderImpl.java#L68

succeeds on the first pass, an ArrayIndexOutOfBoundsException (-1) is bound to be thrown here:

https://github.com/eclipse/kura/blob/961029abd4c86aa6c738f2b2aaf733d1c3bdedbc/kura/org.eclipse.kura.ble.ibeacon.provider/src/main/java/org/eclipse/kura/internal/ble/ibeacon/BluetoothLeIBeaconDecoderImpl.java#L73

I guess this could be a problem.

The other thing is that the Decoder cannot decode Encoder's output. This may be OK, if they were not designed to be used one for the other.
The good thing is that somehow it all works...

As before, if I'm missing something, close the issue freely.

### PR DESCRIPTION
**Pull request by pierantoniomerlino**
Closes #1863 
Signed-off-by: pierantoniomerlino <pierantonio.merlino@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
I believe that the kura.build.properties needs to be updated too, right?

**Comment by pierantoniomerlino** [comment]
@MMaiero I was doing it when you commented my PR...

**Comment by MMaiero** [comment]
:-D

**Review by markoer — APPROVED** [review]
OK, that would work.

**Review by markoer — APPROVED** [review]

**Pull request merged**
