### PR TITLE
Changed wires db implementation adding table size limit.

### PR DESCRIPTION
**Pull request by MMaiero**
Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

### CODE REVIEW

**Review by amitjoy — APPROVED** [review]

**Comment by amitjoy** [comment]
This PR causes 2 test cases to fail - `testCleanupSequence` and  `testSequence`.

Could you kindly make the necessary amendments to these test cases?

**Comment by MMaiero** [comment]
The PR was created only for tracking. As you can see, it is not prioritized because the work is in progress and currently under long running test.

**Comment by MMaiero** [comment]
Closes #1212

**Comment by MMaiero** [comment]
Ok on closing this?

**Comment by amitjoy** [comment]
It looks fine to me 👍

**Pull request merged**
