### PR TITLE
Changed FirewallConfigurationServiceImpl activation

### LINKED ISSUE #3385: Snaphot_0 Firewall rules are not processed by Kura
**Describe the bug**
In the snapshot_0 we add some rules for a second Ethernet port and they are simply ignored. So we need to add the rules manually.

Some rules for ports seems to be generated automatically like opening the ports for network 10.234.0.0/16 that is creating a security hazard.

**To Reproduce**
Here is the snapshot_0 firewall property
<esf:properties>
	    <esf:property array="false" encrypted="false" name="firewall.open.ports" type="String">
                <esf:value>22,tcp,,,,,,#;443,tcp,,eth0,,,,#;443,tcp,,wlan0,,,,#;4443,tcp,,eth0,,,,#;4443,tcp,,wlan0,,,,#;1450,tcp,,eth0,,,,#;1450,tcp,,wlan0,,,,#;502,tcp,127.0.0.1/32,,,,,#;53,udp,,eth0,,,,#;53,udp,,wlan0,,,,#;67,udp,,eth0,,,,#;67,udp,,wlan0,,,,#;8000,tcp,,eth0,,,,#;8000,tcp,,wlan0,,,,#;53,udp,,eth1,,,,#;63,udp,,eth1,,,,#;443,tcp,,eth1,,,,#;4443,tcp,,eth1,,,,#</esf:value>
            </esf:property>
	    <esf:property array="false" encrypted="false" name="firewall.port.forwarding" type="String">
                <esf:value></esf:value>
            </esf:property>
	    <esf:property array="false" encrypted="false" name="firewall.nat" type="String">
                <esf:value></esf:value>
            </esf:property>
	</esf:properties>

**Expected behavior**
All rules for Eth1 are not executed by Kura

**Screenshots**
See attached screenshot
Capture

**Target Environment (please complete the following information):**
 - Board IMX6
 - OS version: Linux 5.4

 - Additional info: 

**Additional context**

### PR DESCRIPTION
**Pull request by pierantoniomerlino**
The `FirewallConfigurationServiceImpl` is modified to apply the properties at the activation.

**Related Issue:** This PR fixes/closes #3385 

Signed-off-by: pierantoniomerlino <pierantonio.merlino@eurotech.com>

### CODE REVIEW

**Comment by MMaiero** [comment]
@pierantoniomerlino Is this ready for review?

**Comment by pierantoniomerlino** [comment]
@MMaiero Yes, you can check it.

**Review by MMaiero — APPROVED** [review]

**Comment by MMaiero** [comment]
Do we have changes to the documentation? I believe this is a behaviour change that needs to be documented before merging.

**Comment by pierantoniomerlino** [comment]
We don't have any entry in the documentation about this feature... the user expects to change a snapshot_0.xml and this should be applied. We can add some notes on the documentation.

**Pull request merged**
