### PR TITLE
[Testing][Refactoring] Refactored linux.clock service and providers, added tests

### PR DESCRIPTION
**Pull request by markoer**
* refactored services and providers for improved testability
* added tests

Part of #1639.

### CODE REVIEW

**Comment by markoer** [comment]
Please consider the `FIXME?` comments before merging. There is one already merged in the `init` method of `GpsClockSyncProvider.java`.

**Comment by MMaiero** [comment]
@pierrepitiot Could you give a look at this PR?

**Comment by pierrepitiot** [comment]
Sure I will do that today

**Comment by pierrepitiot** [comment]
As far as I can see it looks ok to me but I don't know how to test the test part :-)

**Comment by MMaiero** [comment]
@pierrepitiot What about the comment made here? https://github.com/eclipse/kura/pull/1649/files#diff-78d58ace83429f76a47a95b554b4ebceR203

**Comment by pierrepitiot** [comment]
@MMaiero I don't know how to test the GPS time,  the GPS option is not included in clock.provider config, and I agree with the FIXME remark:

                                if (procTime.exitValue() == 0) {
                                    logger.info("System Clock Synchronized with GPS, time = {}", gpsTime);
                                    this.lastSync = new Date();
                                    this.waitForLocked = false;
                                } else {
                                    logger.error("Unexpected error while Synchronizing System Clock with GPS");
                                    // FIXME? this value gets overwritten immediately and it likely makes no sense as
                                    // the date command failed, not GPS
                                    this.waitForLocked = true;
                                }
                            }
                            **this.waitForLocked = false;**

**Comment by cdealti** [comment]
@markoer I think this is ready to go. The GPS clock provider can be removed as it's there since the first Kura release but never used. Unless you need to add something else, I'd squash the two commits and merge it.

**Comment by markoer** [comment]
I guess it's no longer ready to go :( I rebased from develop to update distrib config file and managed to merge too much. Will try to clean up.

**Comment by markoer** [comment]
Replaced by #1774.

**Pull request closed without merging**
